Repository wso2/product-microgateway, pull requests merged in 2019-10, with the labels that each got.

#829 Fix #827 - NPE when open API used without wso2 extensions
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
Labels: Affected/3.0.1, Type/Bug

#831 Fix #830: ETCD base path hard coded issue
  components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/gateway/utils/etcd_util.bal
Labels: Affected/3.0.1, Type/Bug

#833 Introduce default subscription policy
  components/micro-gateway-core/src/main/ballerina/gateway/basicAuth.bal
  components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/gateway/dtos/gateway_dtos.bal
  distribution/resources/definitions/policies.yaml
  tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
  tests/src/test/resources/policies.yaml
Labels: Affected/3.0.1, Type/Improvement

#834 Fix issues in executables
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  distribution/resources/bin/gateway.bat
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
Labels: Docs/No Impact, Priority/Normal, Type/Improvement

#835 Update development version
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-core/pom.xml
  components/micro-gateway-tools/pom.xml
  components/pom.xml
  distribution/pom.xml
  distribution/src/main/assembly/filter.properties
  pom.xml
  tests/pom.xml
Labels: Docs/No Impact, Priority/High, Type/Task

#836 Prepare resources for 3.0.2 release
  README.md
  distribution/LICENSE-RUNTIME.txt
  distribution/LICENSE-TOOLKIT.txt
  distribution/src/main/assembly/filter.properties
  release-notes.html
Labels: Priority/High, Type/Task

#819 Fix #818 : Initial commit to support APIM v3
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/RESTServiceConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/TokenManagementConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Token.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  distribution/resources/ballerinaTruststore.p12
  distribution/resources/cli-conf/toolkit-config.toml
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockAPIPublisher.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/model/API.java
  tests/src/test/resources/confs/default-cli-test-config.toml
Labels: Type/Improvement

#826 Add new issue templates
  .github/ISSUE_TEMPLATE/documentation_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: Priority/Normal, Type/Docs, Type/Task

#843 Update microgw docker file
  docker/Dockerfile
Labels: Affected/3.0.1, Type/Improvement

#844 Front port fixes from 3.0.x to jballerina branch
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/gateway_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
  distribution/resources/definitions/policies.yaml
  tests/src/test/resources/policies.yaml
Labels: Type/Bug, Type/Improvement

#848 Fix #847 - Support open API without extensions
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaPath.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
Labels: Affected/3.0.2, Docs/Has Impact, Priority/Normal, Type/Improvement

#849 Fix #837 - Subscription validation configurable
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
  distribution/resources/conf/micro-gw.conf
Labels: Affected/3.0.2, Type/Improvement

#850 Add CII best practices badge
  README.md
Labels: Priority/Normal, Type/Task
