Repository wso2/product-microgateway, pull requests merged in 2019-08, with the labels that each got.

#719 Add ignore config for spotbugs in jenkins
  pom.xml
Labels: Priority/Normal, Type/Task

#723 Introduce new handlers and providers for authentication framework
  components/micro-gateway-core/src/main/ballerina/src/gateway/basicAuth.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/gateway_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/key_validation_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/jwt_authentication_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Priority/High, Type/Improvement

#725 Fix the bug when there is an executable path including a space in windows
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
Labels: Docs/No Impact, Priority/Normal

#724 Fix the bug when there is an executable path including a space in windows
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
Labels: Priority/Normal, Severity/Minor, Type/Bug

#726 Update listerners, and caches related files
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/gateway_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/api_gateway_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authz_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/key_validation_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/mutualSSL_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_secure_listener.bal
Labels: Type/Task

#729 Add temporary string utils
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/usagedata_uploader.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/lang_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/subscription_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
Labels: Docs/No Impact, Priority/Normal

#728 Add integration tests for endpoints
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointOverrideTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointWithSecurityTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointsByReferenceTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/CookieAuthTestCase.java
  tests/src/test/resources/openAPIs/endpoints/endpoint_override.yaml
  tests/src/test/resources/openAPIs/endpoints/endpoint_security.yaml
  tests/src/test/resources/openAPIs/endpoints/endpoints_by_reference.yaml
  tests/src/test/resources/testng.xml
Labels: Docs/No Impact, Priority/Normal

#730 Fixes for compilation issues
  components/micro-gateway-core/src/main/ballerina/src/gateway/faults_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Type/Improvement

#732 remove unwanted symbol
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Priority/High

#731 Fixe #717 - migrate subscription filter and authn filter
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authz_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
Labels: Type/Improvement

#733 Fix compilation issues
  components/micro-gateway-core/src/main/ballerina/src/gateway/cookie.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/executiontime_util.bal
Labels: Type/Improvement

#735 fixes for endpoint bals
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/api_gateway_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/etcd_endpoint.bal
Labels: Type/Improvement

#739 More jballerina fixes
  components/micro-gateway-core/src/main/ballerina/src/gateway/annotation.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/data_writer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/lang_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/token_revocation_etcd_util.bal
Labels: Priority/Normal, Type/Task

#740 fixes for compilation failures
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/api_security_constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/etcd_token_revocation_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/key_validation_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Type/Improvement

#742 adding fixes for ExecutionTimeDTO
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/analytics_dtos.bal
Labels: Priority/Normal, Type/Task

#745 Fix #743 : Define k8s service names in deployment toml file
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Kubernetes.java
  components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
  components/micro-gateway-cli/src/main/resources/templates/kubernetesService.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceHttp.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceHttps.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceToken.mustache
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
Labels: Affected/3.0.1, Type/Bug

#744 Fix #743 : Define k8s service names in deployment toml file
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Kubernetes.java
  components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
  components/micro-gateway-cli/src/main/resources/templates/kubernetesService.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceHttp.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceHttps.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceToken.mustache
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
Labels: Affected/3.0.1, Type/Bug

#747 WIP: comment out the code to continue
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/file_rotating_timer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/responsetime_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/token_revocation_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/upload_files_timer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/etcd_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/token_revocation_etcd_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/validation_util.bal
Labels: Type/Improvement

#750 Fix for #717 - jBallerina migration
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/key_validation_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/subscription_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Type/Improvement

#752 Add new badges to README
  README.md
Labels: Priority/Normal, Type/Task

#753 Initial migration of templates
  components/micro-gateway-cli/src/main/resources/templates/httpEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/httpEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/httpResourceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  distribution/resources/tokenServices/authorize_endpoint.bal
  distribution/resources/tokenServices/revoke_endpoint.bal
  distribution/resources/tokenServices/token_endpoint.bal
  distribution/resources/tokenServices/user_info_endpoint.bal
Labels: Priority/Normal, Type/Task

#754 Update spotbugs configs
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/HelpCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesConfigMapConfigItem.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesSecretItem.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/MutualSSL.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointListDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/oauth/DCRRequest.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/oauth/OAuthTokenRequest.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIDetailedDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  pom.xml
Labels: Priority/Normal, Type/Task

#756 Migration of templates to work with jwt flow
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/data_writer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/api_gateway_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/usagedata_uploader.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/conf/micro-gw.conf
  distribution/resources/tokenServices/authorize_endpoint.bal
  distribution/resources/tokenServices/revoke_endpoint.bal
  distribution/resources/tokenServices/token_endpoint.bal
  distribution/resources/tokenServices/user_info_endpoint.bal
  docker/conf/micro-gw.conf
Labels: Type/Improvement

#755 Fixes for compilation issues in local throttling
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
Labels: Type/Improvement

#727 Add integration tests for endpoints
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointOverrideTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointWithSecurityTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointsByReferenceTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/CookieAuthTestCase.java
  tests/src/test/resources/openAPIs/endpoints/endpoint_override.yaml
  tests/src/test/resources/openAPIs/endpoints/endpoint_security.yaml
  tests/src/test/resources/openAPIs/endpoints/endpoints_by_reference.yaml
  tests/src/test/resources/testng.xml
Labels: Priority/Normal, Type/Task

#757 Folder structure changes to execute at init cmd phase
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  distribution/resources/grpc/wso2CustomOptions.proto
  distribution/src/main/assembly/bin.xml
Labels: Type/New Feature

#758 Initial migration for 1.0.0-alpha3
  components/micro-gateway-cli/src/main/resources/templates/jwtRevocation.mustache
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-cli/src/main/resources/templates/main.mustache
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/api_security_constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/cookie.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/data_writer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/analytics_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/etcd_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/etcd_token_revocation_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/executiontime_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authz_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/gateway_conf.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/cookie_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/key_validation_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/mutualSSL_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/http2.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_secure_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/usagedata_uploader.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/subscription_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Type/Improvement

#759 Migrate templates to alpha3
  components/micro-gateway-cli/src/main/resources/templates/endpointReinit.mustache
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-cli/src/main/resources/templates/main.mustache
  components/micro-gateway-cli/src/main/resources/templates/noProdAvailableError.mustache
  components/micro-gateway-cli/src/main/resources/templates/noSandAvailableError.mustache
  components/micro-gateway-cli/src/main/resources/templates/policy.mustache
  components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-cli/src/main/resources/templates/useAPIProdEp.mustache
  components/micro-gateway-cli/src/main/resources/templates/useApiSandEp.mustache
  components/micro-gateway-cli/src/main/resources/templates/useResourceProdEp.mustache
  components/micro-gateway-cli/src/main/resources/templates/useResourceSandEp.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/throttle_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
  distribution/resources/filters/extension_filter.bal
  distribution/resources/filters/token_revocation_extension.bal
  distribution/resources/tokenServices/authorize_endpoint.bal
  distribution/resources/tokenServices/revoke_endpoint.bal
  distribution/resources/tokenServices/token_endpoint.bal
  distribution/resources/tokenServices/user_info_endpoint.bal
Labels: Type/Improvement

#760 Update jaballerina with master
  README.md
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/HelpCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Kubernetes.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesConfigMapConfigItem.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesSecretItem.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/MutualSSL.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointListDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/oauth/DCRRequest.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/oauth/OAuthTokenRequest.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIDetailedDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
  components/micro-gateway-cli/src/main/resources/templates/kubernetesService.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceHttp.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceHttps.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceToken.mustache
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  pom.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointOverrideTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointWithSecurityTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointsByReferenceTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/CookieAuthTestCase.java
  tests/src/test/resources/openAPIs/endpoints/endpoint_override.yaml
  tests/src/test/resources/openAPIs/endpoints/endpoint_security.yaml
  tests/src/test/resources/openAPIs/endpoints/endpoints_by_reference.yaml
  tests/src/test/resources/testng.xml
Labels: Priority/Normal, Type/Task

#762 Change spotbugs version property
  pom.xml
Labels: Docs/No Impact, Priority/Normal, Type/Task

#761 Fixes for the compilation issues in analytics
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/data_writer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/analytics_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/file_rotating_timer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/responsetime_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/upload_files_timer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/etcd_util.bal
  distribution/resources/conf/micro-gw.conf
Labels: Type/Improvement

#765 Fix micro-gw build command
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  pom.xml
Labels: Docs/No Impact, Priority/Normal, Type/Task

#766 Re write java siddhi extension in ballerina
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-cli/src/main/resources/templates/policy.mustache
  components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/throttle_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/emitOnStateChange.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/time_batch.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
Labels: Type/Task

#770 Fix toolkit exec files
  components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/emitOnStateChange.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/time_batch.bal
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
Labels: Docs/No Impact, Priority/Normal, Type/Task

#769 Rename few classes
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/CliCommands.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/HelpCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/InitCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/LauncherCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ResetCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/ThrottlePolicyGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/RESTServiceConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/hashing/HashUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/logging/CLILogConfigReader.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/logging/CLILogManager.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesDeployment.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesIngress.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/SecureKubernetesIngress.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Token.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/ListenerEndpoint.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ZipUtils.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java
Labels: Priority/Normal, Type/Task
