Repository wso2/product-microgateway, pull requests merged in 2019-09, with the labels that each got.

#771 Update 'BUG' issue template
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: Priority/Normal, Type/Task

#777 Migrate to jabl 1.0.0-beta
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/executiontime_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/file_rotating_timer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_secure_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/responsetime_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/emitOnStateChange.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/subscription_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/filters/extension_filter.bal
Labels: Type/Improvement

#776 Temoprarily fix the maven build for jballerina
  .gitignore
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
  components/micro-gateway-core/assembly/bin.xml
  components/micro-gateway-core/assembly/bir.xml
  components/micro-gateway-core/assembly/jar.xml
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/scripts/ballerina-build.bat
  components/micro-gateway-core/scripts/ballerina-build.sh
  components/micro-gateway-core/src/main/java/org/ballerina/gateway/models/APIModel.java
  components/micro-gateway-core/src/main/java/org/ballerina/gateway/models/TierModel.java
  components/micro-gateway-core/src/main/java/org/ballerina/gateway/siddhi/extension/EmitOnStateChange.java
  components/micro-gateway-core/src/main/java/org/ballerina/gateway/siddhi/extension/ThrottleStreamProcessor.java
  components/micro-gateway-core/src/main/resources/META-INF/services/org.ballerinalang.compiler.plugins.CompilerPlugin
  distribution/pom.xml
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/src/main/assembly/bin.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
  distribution/src/main/assembly/platform_zip.xml
  distribution/src/main/assembly/runtime_zip.xml
  pom.xml
Labels: Type/Task

#778 Remove unused code
  README.md
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/APIDefinition.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/APIDefinitions.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/DefinitionConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/EndpointListDefinition.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/PathsDefinition.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/ResourceDefinition.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/Endpoint.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/EndpointConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/EndpointList.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/APIRouteEndpointConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/EndpointListRouteDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/ResourceRouteRouteEndpointConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/RouteEndpointConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/JsonProcessingUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionBuilder.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
Labels: Priority/Normal, Type/Task

#780 Fix project structure related issues
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
Labels: Docs/No Impact, Priority/Normal, Type/Improvement

#781 Fix template issues
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-cli/src/main/resources/templates/useAPIProdEp.mustache
  components/micro-gateway-cli/src/main/resources/templates/useApiSandEp.mustache
  components/micro-gateway-cli/src/main/resources/templates/useResourceProdEp.mustache
  components/micro-gateway-cli/src/main/resources/templates/useResourceSandEp.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/executiontime_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/file_rotating_timer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_secure_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/responsetime_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/emitOnStateChange.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/subscription_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/filters/extension_filter.bal
  pom.xml
Labels: Type/Improvement

#784 Include entire extensions directory in mgw build
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
Labels: Docs/No Impact, Priority/Normal, Type/Improvement

#786 Use all src in extensions dir for build
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
Labels: Docs/No Impact, Priority/Normal, Type/Improvement

#782 Create MGW runtime with jballerina
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
  distribution/pom.xml
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
  distribution/src/main/assembly/gw_runtimes/gw_runtime.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
  distribution/src/main/assembly/platform_zip.xml
  distribution/src/main/assembly/runtime_zip.xml
  pom.xml
Labels: Type/Improvement

#787 Update DockerFile
  docker/Dockerfile
  docker/README.md
  docker/conf/micro-gw.conf
  docker/license/COPYRIGHT
  docker/license/LICENSE.txt
  docker/runtime/.empty.txt
  docker/security/ballerinaTruststore.p12
Labels: Type/Improvement

#791 Fix integration test failures
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/resources/templates/basicAuth.mustache
  components/micro-gateway-cli/src/main/resources/templates/basicAuthHandler.mustache
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-cli/src/main/resources/templates/openAPIJsonConstants.mustache
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/key_validation_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/bin/gateway
  pom.xml
  tests/pom.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/common/BaseTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/context/ServerInstance.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointOverrideTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointWithSecurityTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/prepare/PreRequisites.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithOAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/CookieAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/DisableSecurityAndCustomAuthHeaderTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/serviceDiscovery/EtcdSupportTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/OpenApiThrottlingTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/ThrottlingTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/util/TokenUtil.java
  tests/src/test/resources/openAPIs/interceptor/interceptPerAPIRequest.bal
  tests/src/test/resources/openAPIs/interceptor/interceptPerAPIResponse.bal
  tests/src/test/resources/openAPIs/interceptor/validateRequest.bal
  tests/src/test/resources/openAPIs/interceptor/validateResponse.bal
  tests/src/test/resources/policies.yaml
  tests/src/test/resources/testng.xml
Labels: Type/Improvement, test-improvements

#795 Add sample github action
  .github/workflows/maven.yml
Labels: Priority/Normal, Type/Task

#792 Fix basic auth issues
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/ThrottlePolicyGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/ThrottlePolicyMapper.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/policy/ThrottlePolicy.java
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/annotation.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/conf/micro-gw.conf
  tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithOAuth2andBasicAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/OpenApiThrottlingTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/ThrottlingTestCase.java
  tests/src/test/resources/confs/default-test-config.conf
  tests/src/test/resources/policies.yaml
  tests/src/test/resources/testng.xml
Labels: Type/Improvement

#800 Add CLI message for distribution initialization
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
  components/micro-gateway-tools/src/main/go/tools/distribution.go
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
Labels: Docs/No Impact, Priority/Normal, Type/Improvement

#799 Add distribution init log
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
  components/micro-gateway-tools/src/main/go/tools/distribution.go
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
Labels: Docs/No Impact, Priority/Normal, Type/Improvement

#801 Fix analytics issues
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/data_writer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/executiontime_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/faults_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/file_rotating_timer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/responsetime_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/upload_files_timer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/usagedata_uploader.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/compression.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/compression/Compress.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/utils/ErrorUtils.java
  distribution/pom.xml
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/src/main/assembly/bin.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
  pom.xml
Labels: Type/Improvement

#797 Update maven build action
  .github/workflows/maven.yml
Labels: Priority/Normal, Type/Task

#794 Change build command output
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
Labels: Docs/No Impact, Priority/Normal, Type/Improvement

#796 Fix issues with SOAP endpoints
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
Labels: Docs/No Impact, Priority/Normal

#798 Update build command output
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
Labels: Docs/No Impact, Priority/Normal, Type/Improvement

#804 Replace only basepath
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
Labels: Priority/Normal, Type/Bug

#807 Fix #806 : Resource level global throttling issue
  components/micro-gateway-core/src/main/ballerina/gateway/filters/throttle_filter.bal
Labels: Affected/3.0.1, Priority/High, Type/Bug

#809 Fix #808: Analytics filter improvements
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal
  components/micro-gateway-core/src/main/ballerina/gateway/utils/analytics_util.bal
Labels: Affected/3.0.1, Type/Improvement

#813 Fix k8s labels, secrets and annotations
  components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
  components/micro-gateway-cli/src/main/resources/templates/kubernetesDeployment.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesHpa.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesIngress.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesJob.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesSecret.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesService.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceHttp.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceHttps.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceToken.mustache
  components/micro-gateway-cli/src/main/resources/templates/secureKubernetesIngress.mustache
Labels: Docs/Has Impact, Priority/Normal, Type/Bug

#816 Avoid use of extenal ballerina installation
  distribution/resources/bin/gateway.bat
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
Labels: Docs/No Impact, Priority/Normal, Type/Bug

#817 Avoid use of host ballerina installation
  distribution/resources/bin/gateway.bat
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
Labels: Docs/No Impact, Priority/Normal, Type/Bug

#812 Fix issues in k8s configs
  components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
  components/micro-gateway-cli/src/main/resources/templates/kubernetesDeployment.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesHpa.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesIngress.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesJob.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesSecret.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesService.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceHttp.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceHttps.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceToken.mustache
  components/micro-gateway-cli/src/main/resources/templates/secureKubernetesIngress.mustache
Labels: Docs/Has Impact, Priority/Normal, Type/Bug

#805 Fix issues in service discovery
  components/micro-gateway-cli/src/main/resources/templates/endpointReinit.mustache
  components/micro-gateway-cli/src/main/resources/templates/failoverEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/failoverEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/httpEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/etcd_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  tests/pom.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/serviceDiscovery/EtcdSupportTestCase.java
  tests/src/test/resources/openAPIs/serviceDiscovery/etcd_test.yaml
Labels: Type/Improvement

#820 Add next step tips to CLI Commands
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/InitCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
Labels: Docs/Has Impact, Priority/Normal, Type/Improvement

#822 Add next step tips to toolkit commands
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/InitCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
Labels: Docs/Has Impact, Priority/Normal, Type/Improvement
