Repository wso2/product-microgateway, pull requests merged in 2019-05, with the labels that each got.

#507 Introduce Go tool for runtime distribution
  components/micro-gateway-core/pom.xml
  components/micro-gateway-tools/assembly/bin.xml
  components/micro-gateway-tools/pom.xml
  components/micro-gateway-tools/src/main/go/tools/distribution.go
  components/micro-gateway-tools/src/main/go/tools/util/util.go
  components/pom.xml
  distribution/pom.xml
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
  pom.xml
Labels: 3.0.0, Docs/No Impact

#509 Remove runtime.zip from toolkit
  README.md
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/APIDefinition.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APICorsConfigurationDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/ext/ExtendedAPI.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/EndpointListRouteDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionBuilder.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
  components/micro-gateway-cli/src/main/resources/definition-schema.json
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/gateway/jwt_authentication_handler.bal
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
  distribution/src/main/assembly/bin.xml
  pom.xml
  samples/cors_sample.yaml
  samples/interceptors_sample.yaml
  samples/per_resource_endpoint.yaml
  samples/petstore_basic.yaml
  samples/petstore_swagger3.yaml
  samples/policies_sample.yaml
  tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/context/ServerInstance.java
  tests/src/test/resources/testapi.json
Labels: 3.0.0, Docs/No Impact

#510 Restructure mgw distribution and build
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
  components/micro-gateway-core/pom.xml
  components/micro-gateway-tools/assembly/bin.xml
  components/micro-gateway-tools/pom.xml
  components/micro-gateway-tools/src/main/go/tools/distribution.go
  components/micro-gateway-tools/src/main/go/tools/util/util.go
  components/pom.xml
  distribution/pom.xml
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
  distribution/resources/exec/empty.txt
  distribution/resources/runtime_logs/access_logs
  distribution/src/main/assembly/ballerina_runtimes/runtime_linux_zip.xml
  distribution/src/main/assembly/ballerina_runtimes/runtime_macos_zip.xml
  distribution/src/main/assembly/ballerina_runtimes/runtime_windows_zip.xml
  distribution/src/main/assembly/bin.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
  pom.xml
  tests/pom.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/context/ServerInstance.java
Labels: 3.0.0, Docs/Has Impact

#511 Add jenkins build status to README
  README.md
Labels: 3.0.0, Docs/No Impact

#514 Copy mgw artifacts to ballerina runtime
  components/micro-gateway-cli/src/main/resources/distribution/bin/gateway
  components/micro-gateway-cli/src/main/resources/distribution/bin/gateway.bat
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
Labels: 3.0.0, Docs/No Impact

#515 runtime: Fix issue in gateway sh
  distribution/resources/bin/gateway
Labels: 3.0.0, Docs/No Impact, Type/Bug

#517 Remove unused cmd commands
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/AddAPICmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/AddRouteCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/DescResourceCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/FunctionCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ListAPIsCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ListResourcesCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/RunCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetProjectCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/UpdateRouteCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/hashing/LibHashUtils.java
Labels: 3.0.0, Type/Task

#518 Remove un used GRPC files
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/grpc/GRPCUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/grpc/GrpcGen/BalFileGenerationUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/grpc/GrpcGen/BalGenToolException.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/grpc/GrpcGen/BalGenerationConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/grpc/GrpcGen/DescriptorsGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/grpc/GrpcGen/OSDetector.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/grpc/GrpcGen/ProtocCommandBuilder.java
Labels: 3.0.0, Docs/No Impact, Type/Task

#519 Fix warnings in maven build
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/YamlValidator.java
  distribution/pom.xml
  distribution/src/main/assembly/bin.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
  pom.xml
Labels: 3.0.0, Docs/No Impact, Type/Improvement

#521 Update README.md
  README.md
Labels: Docs/No Impact, Type/Improvement

#533 Move generates src to target folder
  README.md
  architecture-new.png
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/EndpointType.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/dockerConfig.mustache
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
Labels: Docs/No Impact, Priority/Normal, Type/Improvement

#536 Add startup log for listening ports
  components/micro-gateway-core/src/main/ballerina/gateway/endpoints/api_gateway_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_secure_listener.bal
Labels: Docs/No Impact, Type/Improvement

#538 Add trust store with stream processor public cert to run times and toolkit
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/InitCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
  components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
  distribution/src/main/assembly/ballerina_runtimes/runtime_linux_zip.xml
  distribution/src/main/assembly/ballerina_runtimes/runtime_macos_zip.xml
  distribution/src/main/assembly/ballerina_runtimes/runtime_windows_zip.xml
  distribution/src/main/assembly/platform_zip.xml
Labels: Type/Improvement

#534 Support for etcdkeys as endpoints
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/InitCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointListDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/EndpointListRouteDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
  components/micro-gateway-cli/src/main/resources/templates/endpointReinit.mustache
  components/micro-gateway-cli/src/main/resources/templates/failoverEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/failoverEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/failoverResourceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/httpEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/httpEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/httpResourceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbResourceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/noProdAvailableError.mustache
  components/micro-gateway-cli/src/main/resources/templates/noSandAvailableError.mustache
  components/micro-gateway-cli/src/main/resources/templates/prodEndpointReinit.mustache
  components/micro-gateway-cli/src/main/resources/templates/sandEndpointReinit.mustache
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-cli/src/main/resources/templates/useAPIProdEp.mustache
  components/micro-gateway-cli/src/main/resources/templates/useApiSandEp.mustache
  components/micro-gateway-cli/src/main/resources/templates/useResourceProdEp.mustache
  components/micro-gateway-cli/src/main/resources/templates/useResourceSandEp.mustache
  components/micro-gateway-core/src/main/ballerina/gateway/utils/etcd_util.bal
Labels: Docs/No Impact, Priority/High, Type/Improvement

#544 Fix test cases
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  pom.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/APIInvokeWithBasicAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/APIInvokeWithOAuth2andBasicAuthTestCase.java
  tests/src/test/resources/api-definition.json
Labels: Docs/No Impact, Type/Bug

#546 Fix test failures
  tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/ThrottlingTestCase.java
  tests/src/test/resources/policies.yaml
Labels: Docs/No Impact, Type/Improvement

#547 Pack open jdk to run times
  distribution/pom.xml
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/src/main/assembly/ballerina_runtimes/runtime_linux_zip.xml
  distribution/src/main/assembly/ballerina_runtimes/runtime_macos_zip.xml
  distribution/src/main/assembly/ballerina_runtimes/runtime_windows_zip.xml
  pom.xml
Labels: Type/Task

#549 Update README
  README.md
Labels: Docs/Has Impact, Type/Improvement

#550 Update license for 3.0.0
  LICENSE.txt
  distribution/LICENSE-RUNTIME.txt
  distribution/LICENSE-TOOLKIT.txt
  distribution/src/main/assembly/bin.xml
  distribution/src/main/assembly/filter.properties
  distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
Labels: Docs/No Impact, Type/Task

#569 setting the sslVerifyClient property to "optional" as default in micro-gw.conf
  distribution/resources/conf/micro-gw.conf
Labels: Docs/No Impact, Priority/Normal

#570 Fix 3.0.0 RC1 issues
  README.md
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/HashingConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/hashing/HashUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  components/micro-gateway-cli/src/main/resources/templates/failoverEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-core/src/main/ballerina/gateway/constants/api_throttle_out_constants.bal
  components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/gateway/endpoints/api_gateway_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/gateway/endpoints/etcd_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/gateway/endpoints/etcd_token_revocation_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/gateway/endpoints/throttle_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_secure_listener.bal
  components/micro-gateway-core/src/main/ballerina/gateway/utils/throttle_util.bal
  distribution/resources/conf/micro-gw.conf
  docker/conf/micro-gw.conf
Labels: Docs/No Impact

#573 Fix jcommander usage and help issues
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/GatewayLauncherCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/HelpCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/InitCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ResetCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/exception/CliLauncherException.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
Labels: Docs/No Impact, Priority/Normal

#576 Fix #575 - baspath trailing / character issue
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
Labels: Affected/3.0.0, Priority/Normal, Severity/Minor, Type/Bug, bug

#574 Fix issues in analytics data
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-cli/src/main/resources/templates/useAPIProdEp.mustache
  components/micro-gateway-cli/src/main/resources/templates/useApiSandEp.mustache
  components/micro-gateway-cli/src/main/resources/templates/useResourceProdEp.mustache
  components/micro-gateway-cli/src/main/resources/templates/useResourceSandEp.mustache
  components/micro-gateway-core/src/main/ballerina/gateway/responsetime_util.bal
  components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
Labels: Docs/No Impact, Priority/High

#577 Update License for 3.0.1
  distribution/LICENSE-RUNTIME.txt
  distribution/LICENSE-TOOLKIT.txt
Labels: Docs/No Impact, Priority/Normal

#554 Prevent building project without valid api definition
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
Labels: Docs/No Impact, Priority/High

#578 Update product version property
  distribution/src/main/assembly/filter.properties
Labels: Docs/No Impact, Priority/Normal

#586 Revert back to 3.0.1-SNAPSHOT
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-core/pom.xml
  components/micro-gateway-tools/pom.xml
  components/pom.xml
  distribution/pom.xml
  pom.xml
  tests/pom.xml
Labels: Docs/No Impact, Priority/Highest

#581 Fix #580: Change Open API extensions
  README.md
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GeneratorConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-cli/src/main/resources/templates/openAPIJsonConstants.mustache
  components/micro-gateway-core/src/main/ballerina/gateway/filters/validation_filter.bal
  samples/cors_sample.yaml
  samples/endpoint_by_reference_sample.yaml
  samples/interceptors_sample.yaml
  samples/per_resource_endpoint.yaml
  samples/petstore_basic.yaml
  samples/policies_sample.yaml
  samples/security_sample.yaml
  tests/src/test/java/org/wso2/micro/gateway/tests/common/BaseTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/context/ServerInstance.java
  tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/OASAPIInvokeTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/ValidationTestCase.java
  tests/src/test/resources/PizzaShackAPI_swagger.json
  tests/src/test/resources/api-definition.json
  tests/src/test/resources/testapi.json
Labels: Docs/No Impact, Priority/High

#583 Add mgw truststore to docker image
  docker/Dockerfile
  docker/security/ballerinaTruststore.p12
Labels: Docs/No Impact, Priority/Normal

#585 Add contriubtion docs
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  issue_template.md
Labels: Affected/3.0.1, Docs/Has Impact, Priority/Normal

#584 fix validator swagger3
  components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/gateway/filters/validation_filter.bal
  components/micro-gateway-core/src/main/ballerina/gateway/utils/validation_util.bal
  tests/src/test/resources/api-definition.json
Labels: Docs/No Impact, Priority/Normal

#588 Fix #587 : startup extension for gateway
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  components/micro-gateway-cli/src/main/resources/templates/main.mustache
  distribution/resources/filters/startup_extension.bal
  tests/src/test/java/org/wso2/micro/gateway/tests/context/ServerInstance.java
Labels: Priority/Normal, Type/Improvement
