Repository wso2/product-microgateway, pull requests merged in 2019-11, with the labels that each got.

#869 support cors config for /token and other endpoints
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GeneratorConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
  distribution/resources/tokenServices/authorize_endpoint.bal
  distribution/resources/tokenServices/revoke_endpoint.bal
  distribution/resources/tokenServices/token_endpoint.bal
  distribution/resources/tokenServices/user_info_endpoint.bal
  distribution/src/main/assembly/bin.xml
Labels: Affected/3.0.2, Type/Improvement

#870 Fix #858 - insecure -k option does not neglect ssl validations
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/TokenManagementConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthServiceImpl.java
  distribution/resources/ballerinaTruststore.p12
Labels: Affected/3.0.2, Type/Bug

#872 Fix #871 - Error when empty authorization header is provided
  components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
Labels: Affected/3.0.2, Type/Bug

#876 Fix issue in proxying with ssl bump and path parameters containing special characters
  pom.xml
  tests/pom.xml
Labels: Affected/3.0.2, Type/Bug

#878 Prepare for release 3.0.3
  README.md
  distribution/LICENSE-RUNTIME.txt
  distribution/LICENSE-TOOLKIT.txt
  distribution/src/main/assembly/filter.properties
  docker/Dockerfile
  release-notes.html
Labels: Priority/Normal, Type/Task

#882 Fix #879 #880 - Disbale cors by default and improve reset command
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ResetCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  components/micro-gateway-cli/src/main/resources/cli-help/cli-help.help
  components/micro-gateway-cli/src/main/resources/cli-help/cli-reset.help
  distribution/resources/cli-conf/toolkit-config.toml
Labels: Affected/3.0.2, Type/Bug

#883 Rollback to 3.0.3-SNAPSHOT
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-core/pom.xml
  components/micro-gateway-tools/pom.xml
  components/pom.xml
  distribution/pom.xml
  pom.xml
  tests/pom.xml
Labels: Docs/No Impact, Priority/Normal, Type/Task

#862 Fix Docker and Kubernetes import issues
  components/micro-gateway-cli/src/main/resources/templates/dockerCopyFiles.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesDeployment.mustache
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  distribution/pom.xml
  distribution/src/main/assembly/bin.xml
Labels: Type/Bug

#893 Update .github resources
  .github/ISSUE_TEMPLATE/documentation_template.md
  .github/workflows/maven.yml
  .gitignore
Labels: Priority/High, Type/Task

#892 Add github security policy
  .github/SECURITY.md
Labels: Type/Task
