Repository wso2/product-microgateway, pull requests merged in 2019-12, with the labels that each got.

#887 Fixes for Distributed throttling and JWT revocation
  components/micro-gateway-cli/src/main/resources/policies/throttle_policy_initializer.bal
  components/micro-gateway-cli/src/main/resources/templates/jwtRevocation.mustache
  components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
  components/micro-gateway-core/assembly/jms_zip.xml
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/token_revocation_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
  distribution/pom.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
  pom.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/jwtRevocation/JWTRevocationSupportTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/prepare/PreRequisites.java
  tests/src/test/resources/testng.xml
Labels: Type/Improvement

#898 Fix #896 - Expose token, revoke endpoints in 9095 port
  components/micro-gateway-cli/src/main/resources/templates/main.mustache
  components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
  components/micro-gateway-core/src/main/ballerina/gateway/annotation.bal
  components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal
  components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/gateway/filters/authz_filter.bal
  components/micro-gateway-core/src/main/ballerina/gateway/filters/mutualSSL_filter.bal
  components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal
  components/micro-gateway-core/src/main/ballerina/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/gateway/filters/validation_filter.bal
  components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
Labels: Affected/3.0.2

#899 Fix comments in PR #898
  components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
  components/micro-gateway-core/src/main/ballerina/gateway/annotation.bal
  components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
Labels: Priority/High, Type/Task

#900 Fix invalid config samples
  components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
Labels: Affected/3.0.2, Priority/Normal

#906 Prepare for 3.0.4 toolkit release
  distribution/LICENSE-RUNTIME.txt
  distribution/LICENSE-TOOLKIT.txt
  distribution/src/main/assembly/filter.properties
  docker/Dockerfile
  docker/license/LICENSE.txt
  release-notes.html
Labels: Priority/High, Type/Task

#907 Fix formatting issues in #889
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/api_gateway_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/etcd_token_revocation_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/filter_wrappers/validation_filter_wrapper.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/handler_wrappers/key_validation_handler_wrapper.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/handler_wrappers/mutualSSL_handler_wrapper.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/mutualSSL_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/etcd_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/observability_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/subscription_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/UnzipUtility.java
  pom.xml
Labels: Priority/Normal

#865 Introduce new toolkit command options
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/InitCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/TokenManagementConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthServiceImpl.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
  components/micro-gateway-cli/src/main/resources/cli-help/cli-build.help
  components/micro-gateway-cli/src/main/resources/cli-help/cli-init.help
  pom.xml
Labels: Docs/Has Impact, Priority/Normal

#909 Fix #879 #880 jballerina - CORS support for token services and improve reset command
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ResetCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GeneratorConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
  components/micro-gateway-cli/src/main/resources/cli-help/cli-help.help
  components/micro-gateway-cli/src/main/resources/cli-help/cli-reset.help
  components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
  distribution/resources/cli-conf/toolkit-config.toml
  distribution/resources/tokenServices/authorize_endpoint.bal
  distribution/resources/tokenServices/revoke_endpoint.bal
  distribution/resources/tokenServices/token_endpoint.bal
  distribution/resources/tokenServices/user_info_endpoint.bal
  distribution/src/main/assembly/bin.xml
Labels: Type/Bug

#910 Fix #871 jballerina - Error when empty authorization header is provided
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
Labels: Type/Bug

#911 Fix #896 jballerina - Expose token, revoke endpoints in 9095 port
  components/micro-gateway-cli/src/main/resources/templates/main.mustache
  components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/annotation.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authz_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Docs/Has Impact, Type/Improvement

#679 Fixing formatting issue
  components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_secure_listener.bal
Labels: Priority/Normal, Type/Task

#912 Fixes and tests for #884 and #891
  pom.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/resource/GH884PathParamWithSuffixTestCase.java
  tests/src/test/resources/openAPIs/resource/884_path_param_suffix.yaml
  tests/src/test/resources/testng.xml
Labels: Docs/No Impact, Priority/Normal, Type/Improvement
