Repository wso2/product-microgateway, pull requests merged in 2019-07, with the labels that each got.

#682 Fix config value name for JWT token revocation with etcd 3.0.x
  components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/gateway/utils/token_revocation_etcd_util.bal
Labels: Docs/No Impact, Priority/Normal

#681 Fix config value name for JWT token revocation with etcd
  components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/gateway/utils/token_revocation_etcd_util.bal
Labels: Docs/No Impact, Priority/Normal

#692 Fix #676 : Build error when k8s ingress is used
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/SecureKubernetesIngress.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
Labels: Affected/3.0.1, Type/Bug

#694 Fix #693 : Error when k8s environment variables used
  components/micro-gateway-cli/src/main/resources/templates/kubernetesDeployment.mustache
Labels: Affected/3.0.1, Type/Bug

#695 Fix #693 : Error when k8s environment variables used
  components/micro-gateway-cli/src/main/resources/templates/kubernetesDeployment.mustache
Labels: Affected/3.0.1, Type/Bug

#697 Temporary Fix for #696: Disable spotbugs
  pom.xml
Labels: Build-Issues

#641 Use runtime/toolkit distribution for integration tests
  tests/pom.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/common/BaseTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/HTTP2Server/MockHttp2Server.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/context/Constants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/context/Server.java
  tests/src/test/java/org/wso2/micro/gateway/tests/context/ServerInstance.java
  tests/src/test/java/org/wso2/micro/gateway/tests/context/Utils.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/MultipleEndpointsTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/ResourceLevelEndpointsTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/extensions/OASAPIInvokeTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/http2/HTTP2RequestsWithHTTP1BackEndTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/http2/HTTP2RequestsWithHTTP2BackEndTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/interceptor/InterceptorTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/jwtRevocation/JWTRevocationSupportTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/prepare/PreRequisites.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithBasicAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithOAuth2andBasicAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithOAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/AuthenticationFailureTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/CookieAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/DisableSecurityAndCustomAuthHeaderTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/MutualSSLTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/serviceDiscovery/EtcdSupportTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/DistributedThrottlingTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/ThrottlingTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/validation/ValidationTestCase.java
  tests/src/test/resources/confs/base.conf
  tests/src/test/resources/confs/default-test-config.conf
  tests/src/test/resources/confs/mutualSSL-test.conf
  tests/src/test/resources/confs/startup.conf
  tests/src/test/resources/confs/throttle-test-config.conf
  tests/src/test/resources/confs/validation.conf
  tests/src/test/resources/keyStores/ballerinaTruststore.p12
Labels: Docs/No Impact, Priority/Normal

#700 Possible fix to test failures
  tests/src/test/resources/openAPIs/interceptor/PerAPIInterceptor.yaml
Labels: Build-Issues

#706 Update readme with correct download url
  README.md
Labels: Type/Docs

#707 Fix #701 : Analytics error when http port is used
  components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/gateway/filters/mutualSSL_filter.bal
  components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
Labels: Affected/3.0.1, Severity/Major, Type/Bug

#705 Fix #701 : Analytics error when http port is used
  components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/gateway/filters/mutualSSL_filter.bal
  components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
Labels: Affected/3.0.1, Priority/High, Severity/Critical, Type/Bug

#704 Fix: returning 0 as exit code for runtime exceptions during build process
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
Labels: Docs/No Impact, Priority/Normal

#703 Fix: returning 0 as exit code for runtime exceptions during build process
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
Labels: Docs/No Impact, Priority/Normal

#712 Fix #635 - Multiple scope validation issue
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
Labels: Affected/3.0.1, Priority/High, Type/Bug

#713 Add test cases to the 3.0.x branch
  pom.xml
  tests/pom.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/common/BaseTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/HTTP2Server/MockHttp2Server.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/context/Constants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/context/Server.java
  tests/src/test/java/org/wso2/micro/gateway/tests/context/ServerInstance.java
  tests/src/test/java/org/wso2/micro/gateway/tests/context/Utils.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/MultipleEndpointsTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/ResourceLevelEndpointsTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/extensions/OASAPIInvokeTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/http2/HTTP2RequestsWithHTTP1BackEndTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/http2/HTTP2RequestsWithHTTP2BackEndTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/interceptor/InterceptorTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/jwtRevocation/JWTRevocationSupportTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/prepare/PreRequisites.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithBasicAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithOAuth2andBasicAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithOAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/AuthenticationFailureTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/CookieAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/DisableSecurityAndCustomAuthHeaderTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/MutualSSLTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/ScopesTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/serviceDiscovery/EtcdSupportTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/services/PreRequisites.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/DistributedThrottlingTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/OpenApiThrottlingTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/ThrottlingTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/util/HttpClientRequest.java
  tests/src/test/java/org/wso2/micro/gateway/tests/util/TestConstant.java
  tests/src/test/java/org/wso2/micro/gateway/tests/util/TokenUtil.java
  tests/src/test/java/org/wso2/micro/gateway/tests/validation/ValidationTestCase.java
  tests/src/test/resources/confs/base.conf
  tests/src/test/resources/confs/default-test-config.conf
  tests/src/test/resources/confs/mutualSSL-test.conf
  tests/src/test/resources/confs/startup.conf
  tests/src/test/resources/confs/throttle-test-config.conf
  tests/src/test/resources/confs/validation.conf
  tests/src/test/resources/keyStores/ballerinaTruststore.p12
  tests/src/test/resources/openAPIs/common_api.yaml
  tests/src/test/resources/openAPIs/endpoints/fail_over.yaml
  tests/src/test/resources/openAPIs/endpoints/load_balance.yaml
  tests/src/test/resources/openAPIs/interceptor/PerAPIInterceptor.yaml
  tests/src/test/resources/openAPIs/interceptor/interceptPerAPIRequest.bal
  tests/src/test/resources/openAPIs/interceptor/interceptPerAPIResponse.bal
  tests/src/test/resources/openAPIs/interceptor/interceptor.yaml
  tests/src/test/resources/openAPIs/interceptor/validateRequest.bal
  tests/src/test/resources/openAPIs/interceptor/validateResponse.bal
  tests/src/test/resources/openAPIs/security/disable_security.yaml
  tests/src/test/resources/openAPIs/validation/PizzaShackAPI_swagger.json
  tests/src/test/resources/policies.yaml
  tests/src/test/resources/testapi.json
  tests/src/test/resources/testng.xml
  tests/src/test/resources/testngEtcd.xml
Labels: test-improvements
