Repository wso2/product-microgateway, pull requests merged in 2019-06, with the labels that each got.

#591 Bug fix related to default URL in etcd endpoints
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointDTO.java
Labels: Affected/3.0.1, Docs/No Impact, Type/Bug

#590 Fix #556 : Custom auth header in open API
  README.md
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/failoverEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/failoverEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/failoverResourceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/httpEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/httpEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/httpResourceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbResourceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/secureSocket.mustache
  components/micro-gateway-core/src/main/ballerina/gateway/constants/api_security_constants.bal
  components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
  docker/conf/micro-gw.conf
Labels: Docs/No Impact, Priority/High, Type/Improvement

#599 Add http2 template to failover and load balance templates
  components/micro-gateway-cli/src/main/resources/templates/failoverEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/failoverEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/failoverResourceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbResourceEndpoint.mustache
Labels: Affected/3.0.1, Docs/No Impact, Type/Improvement

#602 Avoid unwanted error message
  components/micro-gateway-core/src/main/ballerina/gateway/uploade_files_timer.bal
Labels: Docs/No Impact

#603 Fix stat event appending issue
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-core/src/main/ballerina/gateway/data_writer.bal
  components/micro-gateway-core/src/main/ballerina/gateway/upload_files_timer.bal
  pom.xml
Labels: Docs/No Impact, Type/Bug

#604 removes swagger-to-ballerina-generator-0.990.5 jar
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
Labels: Affected/3.0.1, Docs/No Impact

#607 Update LICENSE for 3.0.1-rc2
  distribution/LICENSE-RUNTIME.txt
  distribution/LICENSE-TOOLKIT.txt
Labels: Docs/No Impact, Priority/Normal

#612 Revert dev version
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-core/pom.xml
  components/micro-gateway-tools/pom.xml
  components/pom.xml
  distribution/pom.xml
  pom.xml
  tests/pom.xml
Labels: Docs/No Impact, Priority/Normal

#611 remove non blocking parameter from startup scripts
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/src/main/assembly/gw_runtimes/gw_runtime.xml
Labels: Docs/No Impact, Type/Improvement

#610 Update docker file after b7a upgrade
  docker/Dockerfile
  docker/conf/micro-gw.conf
  docker/license/COPYRIGHT
  docker/license/LICENSE.txt
Labels: Docs/No Impact, Priority/Normal

#618 Revert dev version
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-core/pom.xml
  components/micro-gateway-tools/pom.xml
  components/pom.xml
  distribution/pom.xml
  pom.xml
  tests/pom.xml
Labels: Docs/No Impact, Priority/Normal, Type/Task

#619 Update release notes for 3.0.1
  release-notes.html
Labels: Docs/No Impact, Priority/Normal, Type/Task

#621 Cleaning up the README
  README.md
Labels: Docs/No Impact, Priority/Normal

#623 Remove unused methods
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/APIDefinition.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/APIDefinitions.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/DefinitionConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/EndpointListDefinition.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/PathsDefinition.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/ResourceDefinition.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/Endpoint.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/EndpointConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/EndpointList.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/APIRouteEndpointConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/EndpointListRouteDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/ResourceRouteRouteEndpointConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/RouteEndpointConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/JsonProcessingUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionBuilder.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
Labels: Docs/No Impact, Priority/Normal, Type/Improvement

#628 Remove unused code
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/APIDefinition.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/APIDefinitions.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/DefinitionConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/EndpointListDefinition.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/PathsDefinition.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/ResourceDefinition.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/Endpoint.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/EndpointConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/EndpointList.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/APIRouteEndpointConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/EndpointListRouteDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/ResourceRouteRouteEndpointConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/RouteEndpointConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/JsonProcessingUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionBuilder.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
Labels: Docs/No Impact, Priority/Normal, Type/Improvement

#626 Initailly restructure test cases for #625
  tests/src/test/java/org/wso2/micro/gateway/tests/extensions/OASAPIInvokeTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/http2/HTTP2RequestsWithHTTP1BackEndTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/http2/HTTP2RequestsWithHTTP2BackEndTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithBasicAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithOAuth2andBasicAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithOAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/AuthenticationFailureTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/CookieAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/MutualSSLTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/DistributedThrottlingTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/PreRequisites.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/ThrottlingTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/validation/ValidationTestCase.java
  tests/src/test/resources/testng.xml
  tests/src/test/resources/testngEtcd.xml
Labels: Docs/No Impact, Priority/Normal

#634 Add new github templates
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/PULL_REQUEST_TEMPLATE/feature_pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
Labels: Docs/No Impact, Priority/Normal, Type/Task

#638 Update github templates
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/PULL_REQUEST_TEMPLATE/feature_pr_template.md
  .github/pull_request_template.md
Labels: Docs/No Impact, Priority/Normal, Type/Task

#643 Add spotbugs plugin to maven build
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cipher/AESCipherTool.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/HelpCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/hashing/HashUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/logging/CLILogConfigReader.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesConfigMapConfigItem.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesSecretItem.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/MutualSSL.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointListDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/oauth/Application.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/oauth/DCRRequest.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/oauth/OAuthTokenRequest.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APICorsConfigurationDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIDetailedDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIMaxTpsDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/ClientCertificatesDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/LabelDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/SequenceDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/ApplicationThrottlePolicyListDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/BandwidthLimitDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/SubscriptionThrottlePolicyListDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/ThrottlePolicyMapper.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/policy/ThrottlePolicy.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/policy/ThrottlePolicyInitializer.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/ListenerEndpoint.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthServiceImpl.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ZipUtils.java
  pom.xml
Labels: Docs/No Impact, Priority/Normal

#644 Changes needed to update assembly plugin version
  components/micro-gateway-core/pom.xml
  components/micro-gateway-tools/pom.xml
  distribution/pom.xml
  pom.xml
Labels: Docs/No Impact, Priority/Normal, Type/Improvement, dependencies

#646 Enable spotbugs for whole project
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java
  components/micro-gateway-core/src/main/java/org/ballerina/gateway/GatewayAnnotationPlugin.java
  components/micro-gateway-core/src/main/java/org/ballerina/gateway/GatewayExtensionProvider.java
  pom.xml
Labels: Docs/No Impact, Priority/Normal, Type/Task

#648 Update andes version
  pom.xml
  tests/pom.xml
Labels: Type/Task, dependencies

#649 Enable checkstyle on org.wso2.apimgt.gateway.cli.utils
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthServiceImpl.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RESTAPIUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ZipUtils.java
  pom.xml
Labels: Docs/No Impact, Priority/Normal

#653 Fix more checkstyle issues
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cipher/AESCipherTool.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cipher/AESCipherToolException.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/config/TOMLConfigParser.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/exception/CLIInternalException.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/exception/CLIRuntimeException.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/hashing/HashUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/logging/CLILogManager.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthServiceImpl.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/builder/DCRRequestBuilder.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/builder/OAuthTokenRequestBuilder.java
  pom.xml
Labels: Docs/No Impact, Priority/Normal, Type/Task

#654 Fix #652: K8s push docker image
  components/micro-gateway-cli/src/main/resources/templates/kubernetesDeployment.mustache
Labels: Affected/3.0.1, Type/Bug

#655 Fix #652: K8s push docker image
  components/micro-gateway-cli/src/main/resources/templates/kubernetesDeployment.mustache
Labels: Affected/3.0.1, Type/Bug, toolkit

#656 Fix more checkstyle issues
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/GatewayCliCommands.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/GatewayLauncherCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/ThrottlePolicyGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GeneratorConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/RESTServiceConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/TokenManagementConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/policy/ThrottlePolicy.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/policy/ThrottlePolicyInitializer.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  pom.xml
Labels: Docs/No Impact, Priority/Normal, Type/Task

#657 add test case for API/Resource level interceptors
  tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/interceptor/InterceptorTestCase.java
  tests/src/test/resources/openAPIs/interceptor/PerAPiInterceptor.yaml
  tests/src/test/resources/openAPIs/interceptor/interceptPerAPIRequest.bal
  tests/src/test/resources/openAPIs/interceptor/interceptPerAPIResponse.bal
  tests/src/test/resources/openAPIs/interceptor/interceptor.yaml
  tests/src/test/resources/openAPIs/interceptor/validateRequest.bal
  tests/src/test/resources/openAPIs/interceptor/validateResponse.bal
  tests/src/test/resources/testng.xml
Labels: Docs/No Impact, Priority/Normal, Type/Task

#659 Fix some javadoc issues
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerationContext.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/ThrottlePolicyGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesIngress.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/SecureKubernetesIngress.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Token.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointConfigDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointListDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/oauth/Application.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/oauth/DCRRequest.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/oauth/OAuthTokenRequest.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIBusinessInformationDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APICorsConfigurationDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIDetailedDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIEndpointSecurityDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIInfoDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIListDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIListPaginationDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIMaxTpsDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIMetadataDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/ClientCertMetadataDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/ClientCertificatesDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/LabelDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/ResourceRepresentation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/SequenceDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/ext/ExtendedAPI.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/ApplicationThrottlePolicyDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/ApplicationThrottlePolicyListDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/BandwidthLimitDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/CustomAttributeDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/RequestCountLimitDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/SubscriptionThrottlePolicyDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/SubscriptionThrottlePolicyListDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/ThrottleLimitDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/ThrottlePolicyDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/ThrottlePolicyListMapper.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/ThrottlePolicyMapper.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/EndpointListRouteDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/EndpointType.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/policy/ThrottlePolicy.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/policy/ThrottlePolicyInitializer.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/ListenerEndpoint.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  pom.xml
Labels: Docs/No Impact, Priority/Normal, Type/Task

#667 Fix assembly syntax issue in Windows
  components/micro-gateway-core/assembly/balo.xml
  components/micro-gateway-core/assembly/bin.xml
  components/micro-gateway-tools/assembly/bin.xml
  distribution/src/main/assembly/ballerina_runtimes/runtime_zip.xml
  distribution/src/main/assembly/platform_zip.xml
Labels: Docs/No Impact, Priority/Normal, Type/Bug

#668 improves the interceptor error message
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
Labels: Docs/No Impact, Priority/Low, Type/Improvement

#669 fixes for error message: #664
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
Labels: Docs/No Impact, Priority/Low, Type/Improvement

#663 fix the issue of running java command twice during build command
  distribution/resources/bin/micro-gw.bat
Labels: Docs/No Impact, Priority/Normal

#670 Fix assembly in windows
  components/micro-gateway-core/assembly/balo.xml
  components/micro-gateway-core/assembly/bin.xml
  components/micro-gateway-tools/assembly/bin.xml
  distribution/src/main/assembly/ballerina_runtimes/runtime_zip.xml
  distribution/src/main/assembly/platform_zip.xml
Labels: Docs/No Impact, Priority/Normal

#672 avoid Java cmd being executed two times during build Cmd in windows
  distribution/resources/bin/micro-gw.bat
Labels: Docs/No Impact, Priority/Normal

#673 Fix all checkstyle issues
  README.md
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/BasicAuth.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Client.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Config.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/ContainerConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/CopyFile.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/CopyFileConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Docker.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/DockerConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Etcd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Kubernetes.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesConfigMap.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesConfigMapConfigItem.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesDeployment.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesHpa.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesIngress.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesJob.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesPersistentVolumeClaim.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesSecret.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesSecretItem.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/MutualSSL.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/SecureKubernetesIngress.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Token.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/TokenBuilder.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APICorsConfigurationDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIEndpointSecurityDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/kubernetesDeployment.mustache
  components/micro-gateway-core/assembly/balo.xml
  components/micro-gateway-core/assembly/bin.xml
  components/micro-gateway-core/src/main/java/org/ballerina/gateway/models/APIModel.java
  components/micro-gateway-tools/assembly/bin.xml
  distribution/resources/bin/micro-gw.bat
  distribution/src/main/assembly/ballerina_runtimes/runtime_zip.xml
  distribution/src/main/assembly/platform_zip.xml
  pom.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/interceptor/InterceptorTestCase.java
  tests/src/test/resources/openAPIs/interceptor/PerAPiInterceptor.yaml
  tests/src/test/resources/openAPIs/interceptor/interceptPerAPIRequest.bal
  tests/src/test/resources/openAPIs/interceptor/interceptPerAPIResponse.bal
  tests/src/test/resources/openAPIs/interceptor/interceptor.yaml
  tests/src/test/resources/openAPIs/interceptor/validateRequest.bal
  tests/src/test/resources/openAPIs/interceptor/validateResponse.bal
  tests/src/test/resources/testng.xml
Labels: Docs/No Impact, Priority/Normal

#675 Fix incomple java docs
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Token.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/ClientCertificatesDTO.java
Labels: Docs/No Impact, Priority/High

#678 Fix #676 : build error when k8s ingress is used
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/SecureKubernetesIngress.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
  components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
Labels: Affected/3.0.1, Priority/Normal, Type/Bug
