Repository wso2/product-microgateway, pull requests merged in 2020-07, with the labels that each got.

#1307 Fix #1258 - Remove tenentwise data and add jwks endpoint
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/api_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/application_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/key_mapping_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_data_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/subscription_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/gateway_jms_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/conf/default-micro-gw.conf.template
Labels: Type/Improvement

#1311 Fix #1258 - Add individual service calls when validating subscriptions
  components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/api_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/application_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/key_mapping_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_data_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/subscription_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
Labels: Type/Improvement

#1310 Add Subscription validation implementation for Opaque token flow.
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/token_introspection_handler.bal
  distribution/resources/conf/micro-gw.conf
  tests/src/test/java/org/wso2/micro/gateway/tests/common/KeyValidationInfo.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockAPIPublisher.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithOAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/AuthenticationFailureTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/DistributedThrottlingTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/ThrottlingTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/util/TestConstant.java
  tests/src/test/resources/api-definition.json
  tests/src/test/resources/api-get-response.json
  tests/src/test/resources/application-get-response.json
  tests/src/test/resources/confs/api-key.conf
  tests/src/test/resources/confs/base.conf
  tests/src/test/resources/confs/default-test-config.conf
  tests/src/test/resources/confs/http2-test.conf
  tests/src/test/resources/confs/mutualSSL-test.conf
  tests/src/test/resources/confs/throttle-test-config.conf
  tests/src/test/resources/introspection-response.json
  tests/src/test/resources/key-mapping-response.json
  tests/src/test/resources/subscription-get-response.json
Labels: Type/Improvement

#1315 Fix #1258 - add new subscription states
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
Labels: Type/Improvement

#1317 Fix #1316 - Build microgateway projects without internet connection using toolkit
  components/micro-gateway-core/assembly/balo.xml
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
Labels: Type/Improvement

#1320 Update ballerina version to 1.2.6
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  distribution/resources/version.txt
  pom.xml
Labels: Type/Task

#1322 Fix #1321 - Multiple jwt issuer subscription validation issue
  components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/api_key_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  tests/src/test/resources/confs/default-test-config.conf
Labels: Type/Bug

#1328 Fix #1327 - Add apim jwt revocation persisitant service
  components/micro-gateway-cli/src/main/resources/templates/jwtRevocation.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/etcd_token_revocation_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/revocation/revoked_jwt_retriever_task.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/revocation/revoked_token_map.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/token_revocation_etcd_util.bal
  distribution/resources/conf/default-micro-gw.conf.template
  tests/src/test/resources/confs/default-test-config.conf
Labels: Type/Improvement

#1319 Support analytics versioning.
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/executiontime_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/faults_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/responsetime_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/analytics_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/throttle_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/token_introspection_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/conf/default-micro-gw.conf.template
Labels: Type/Improvement

#1331 Remove unnecessary subscription allowed check.
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/token_introspection_handler.bal
  tests/src/test/java/org/wso2/micro/gateway/tests/security/AuthenticationFailureTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/util/TestConstant.java
  tests/src/test/resources/introspection-response.json
Labels: Type/Bug

#1324 Fix version * subscribed apis validation
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
Labels: Type/Bug

#1296 Implement Tests for Binary Throttle Event Publishing
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/globalThrottleEventPublisher.bal
  tests/pom.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/common/BaseTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/BinaryTestServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/DataPublisherTestUtil.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/DistributedThrottlingTestCase.java
  tests/src/test/resources/confs/throttle-test-binary-publishing-failover-tm.conf
  tests/src/test/resources/confs/throttle-test-binary-publishing-loadbalance-tm.conf
  tests/src/test/resources/confs/throttle-test-binary-publishing-multiple-tm.conf
  tests/src/test/resources/confs/throttle-test-binary-publishing-single-tm.conf
  tests/src/test/resources/distributedThrottling/stream-definition.json
  tests/src/test/resources/distributedThrottling/wso2carbon.jks
  tests/src/test/resources/testng.xml
Labels: Type/Task

#1334 Fix #1333 - Improvements for subscription validation logic
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/RESTServiceConstants.java
  components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_data_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/subscription_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/token_revocation_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
  distribution/resources/cli-conf/toolkit-config.toml
  distribution/resources/conf/default-micro-gw.conf.template
  distribution/resources/conf/micro-gw.conf
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java
Labels: Type/Improvement

#1330 Backend JWT generation compatible with OAuth2 flow and API Manager non selfcontained JWT Token
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/usagedata_uploader.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/backend_jwt_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/api_gateway_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/token_introspection_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/jwt_generator/claim_retriever.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/jwt_generator/jwt_gen_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/jwtGenerator.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/jwt/generator/MGWJWTGeneratorInvoker.java
  components/micro-gateway-interceptor/pom.xml
  components/micro-gateway-jwt-generator/pom.xml
  components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/AbstractMGWClaimRetriever.java
  components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/AbstractMGWJWTGenerator.java
  components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/ClaimDTO.java
  components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/MGWJWTGeneratorImpl.java
  distribution/resources/conf/default-micro-gw.conf.template
Labels: Type/Improvement

#1304 Implement Log4j Implementation as a custom ConfigurationFactory
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/logConfiguration.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/logging/Log4j2Configuration.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/logging/MgwLog4j2ConfigurationFactory.java
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
Labels: Type/Bug

#1314 Add www-Authenticate header in the Error response
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/mutualSSL_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Type/Bug

#1337 Add method comments
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Type/Bug

#1339 Fix #1338 - Application level throttling issue
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/application_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
  distribution/resources/conf/default-micro-gw.conf.template
Labels: Type/Bug

#1340 Prepare for 3.2.0-beta release
  distribution/src/main/assembly/filter.properties
  docker/alpine/Dockerfile
  docker/ubuntu/Dockerfile
Labels: Type/Task

#1341 populate api tier and api name in backend jwt header
  components/micro-gateway-core/src/main/ballerina/src/gateway/jwt_generator/jwt_gen_util.bal
  components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/MGWJWTGeneratorImpl.java
Labels: Type/Improvement

#1344 Fix 1176
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointsByReferenceTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/MultipleEndpointsTestCase.java
  tests/src/test/resources/openAPIs/endpoints/resource_endpoints_only.yaml
Labels: Docs/No Impact, Priority/Normal, Type/Improvement

#1346 Fix custom claim and issues
  components/micro-gateway-cli/src/main/resources/cli-help/cli-import.help
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
  components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/AbstractMGWJWTGenerator.java
  distribution/resources/conf/default-micro-gw.conf.template
Labels: Type/Bug

#1347 Read the api definition content and pass in to the OpenAPIV3Parser.
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
Labels: Resolution/Fixed, Type/Bug

#1350 Remove the external key manager configuration.
  distribution/resources/conf/default-micro-gw.conf.template
  distribution/resources/conf/micro-gw.conf
Labels: Type/Task

#1352 Add sample JWT generator project
  samples/sample-jwt-generator/pom.xml
  samples/sample-jwt-generator/src/main/java/sample/jwt/generator/SampleJWTGenerator.java
Labels: Priority/Normal, Type/Task

#1357 Revert Code Generator Changes.
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  tests/pom.xml
Labels: Priority/High, Type/Bug

#1359 Make the jms and throttle publishers start asynchronously.
  components/micro-gateway-cli/src/main/resources/policies/throttle_policy_initializer.bal
  components/micro-gateway-cli/src/main/resources/templates/main.mustache
  components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
  distribution/resources/conf/default-micro-gw.conf.template
Labels: Type/Bug

#1360 Fix #1263 - ballerina methods to acces gateway internal cache objects
  components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
Labels: Type/Improvement
