Repository wso2/product-microgateway, pull requests merged in 2020-01, with the labels that each got.

#918 Add travis build configuration
  .travis.yml
Labels: Priority/Normal, Type/Task

#922 upgrade ballerina version to 1.1.0
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
  components/micro-gateway-cli/src/main/resources/templates/basicAuthHandler.mustache
  components/micro-gateway-core/assembly/balo.xml
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/scripts/ballerina-build.bat
  components/micro-gateway-core/scripts/ballerina-build.sh
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/upload_files_timer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_secure_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/revoked_token_map.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/time_batch.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/etcd_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/pom.xml
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
  distribution/resources/conf/Ballerina.toml
  distribution/src/main/assembly/bin.xml
  pom.xml
  tests/src/test/resources/testng.xml
Labels: Type/Improvement

#924 Update travis config
  .travis.yml
Labels: Docs/No Impact, Priority/Normal, Type/Task

#920 Fix #919 - support standard introspection
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/observability_constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/handler_wrappers/key_validation_handler_wrapper.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/key_validation_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  distribution/resources/conf/micro-gw.conf
Labels: Affected/3.0.2, Docs/Has Impact, Priority/Normal, Type/New Feature

#931 API Level auth providers as an Array
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/BasicAuth.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Config.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
Labels: Docs/No Impact, Priority/Normal

#942 Fix bugs
  README.md
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
Labels: Docs/No Impact, Priority/Normal, Type/Bug

#939 Fix issues with the distributed throttling feature
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
  distribution/pom.xml
  distribution/resources/conf/Ballerina.toml
  distribution/resources/conf/micro-gw.conf
  distribution/src/main/assembly/bin.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
  pom.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/DistributedThrottlingTestCase.java
  tests/src/test/resources/testng.xml
Labels: Type/Bug

#945 Port some fixes from 3.0.x
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
  components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
  components/micro-gateway-cli/src/main/resources/templates/httpEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
Labels: Docs/No Impact, Priority/Normal

#948 Set default values for configs
  components/micro-gateway-cli/src/main/resources/templates/jwtRevocation.mustache
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-cli/src/main/resources/templates/secureSocket.mustache
  components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/api_gateway_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/etcd_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/etcd_token_revocation_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authz_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/key_validation_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/http2.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_secure_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/token_revocation_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/token_revocation_etcd_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/conf/micro-gw-default.conf
  distribution/resources/conf/micro-gw.conf
Labels: Type/New Feature

#950 Fixing broken link
  README.md
Labels: Docs/No Impact, Priority/Normal, Type/Docs

#952 Fix test configs
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  distribution/resources/conf/micro-gw-default.conf
  tests/src/test/resources/confs/base.conf
  tests/src/test/resources/confs/default-test-config.conf
  tests/src/test/resources/confs/http2-test.conf
  tests/src/test/resources/confs/mutualSSL-test.conf
  tests/src/test/resources/confs/startup.conf
  tests/src/test/resources/confs/throttle-test-config.conf
  tests/src/test/resources/confs/validation.conf
Labels: Docs/No Impact, Priority/Normal, Type/Task

#946 Fix #919 - Support backword compatibility for configs
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  distribution/resources/conf/micro-gw.conf
Labels: Docs/No Impact, Priority/Normal

#955 Fix #954 - Fix cache initialisation issue
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_secure_listener.bal
Labels: Type/Bug

#944 Restructure jballerina runtime and toolkit distribution
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-cli/src/main/resources/templates/secureSocket.mustache
  components/micro-gateway-core/assembly/bir.xml
  components/micro-gateway-core/assembly/jar.xml
  components/micro-gateway-core/assembly/jms_zip.xml
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/scripts/ballerina-build.bat
  components/micro-gateway-core/scripts/ballerina-build.sh
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/api_gateway_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/etcd_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/etcd_token_revocation_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_secure_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/observability_listener.bal
  components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/Main.java
  components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/UnzipUtility.java
  distribution/pom.xml
  distribution/resources/bin/gateway
  distribution/resources/conf/micro-gw.conf
  distribution/src/main/assembly/bin.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
  tests/src/test/resources/confs/base.conf
  tests/src/test/resources/confs/default-test-config.conf
  tests/src/test/resources/confs/http2-test.conf
  tests/src/test/resources/confs/mutualSSL-test.conf
  tests/src/test/resources/confs/startup.conf
  tests/src/test/resources/confs/throttle-test-config.conf
  tests/src/test/resources/confs/validation.conf
  tests/src/test/resources/testng.xml
Labels: Type/Improvement

#953 Default configs documentation
  distribution/resources/conf/micro-gw-default.conf
  distribution/resources/conf/micro-gw.conf
Labels: Type/Improvement

#932 API Key Feature
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/APIKey.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/annotation.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/api_security_constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/observability_constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/api_key_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/api_key_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/handler_wrappers/api_key_handler_wrapper.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_secure_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/api_key_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/subscription_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/conf/micro-gw-default.conf
  distribution/resources/conf/micro-gw.conf
  tests/src/test/java/org/wso2/micro/gateway/tests/apikey/APIKeyTestCase.java
  tests/src/test/resources/confs/api-key.conf
  tests/src/test/resources/openAPIs/common_api.yaml
  tests/src/test/resources/openAPIs/endpoints/endpoint_override.yaml
  tests/src/test/resources/openAPIs/endpoints/endpoint_security.yaml
  tests/src/test/resources/openAPIs/endpoints/endpoints_by_reference.yaml
  tests/src/test/resources/testng.xml
Labels: Docs/Has Impact, Priority/Normal

#934 Custom proto analytics
  components/micro-gateway-core/src/main/ballerina/src/gateway/Analytics.proto
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/file_rotating_timer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/upload_files_timer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/api_gateway_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/grpcAnalytics/gRPC_analytics_client.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/grpcAnalytics/gRPC_analytics_pb.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/grpcAnalytics/readme.md
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
  distribution/resources/conf/micro-gw-default.conf
  distribution/resources/conf/micro-gw.conf
  tests/src/test/resources/confs/api-key.conf
  tests/src/test/resources/confs/base.conf
  tests/src/test/resources/confs/http2-test.conf
  tests/src/test/resources/confs/mutualSSL-test.conf
  tests/src/test/resources/confs/startup.conf
  tests/src/test/resources/confs/throttle-test-config.conf
  tests/src/test/resources/confs/validation.conf
  tests/src/test/resources/testng.xml
Labels: Type/New Feature

#957 Fix build issues
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/scripts/ballerina-build.bat
Labels: Type/Task

#902 Add feature to pull interceptors from Ballerina Central
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
Labels: Priority/Normal
