Repository wso2/product-microgateway, pull requests merged in 2020-03, with the labels that each got.

#1072 Provide descriptive error message when an invalid URL is provided.
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/exception/CLICompileTimeException.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointListDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/EndpointListRouteDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOpenAPIObject.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaPath.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/protobuf/ProtobufParser.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
Labels: Affected/3.1.0-alpha, Type/Bug

#1034 Revamp json schema validator
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/ext/ExtendedAPI.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-cli/src/main/resources/templates/main.mustache
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/filter_wrappers/validation_filter_wrapper.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/validator.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/validation_util.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java
  pom.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/interceptor/InterceptorTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/validation/ValidationTestCase.java
  tests/src/test/resources/confs/validation.conf
  tests/src/test/resources/testng.xml
Labels: Type/Bug

#1082 Fix #929 - Enbale response caching open API extension
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIDetailedDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/resources/templates/caching.mustache
Labels: Affected/3.1.0-alpha, Type/Improvement

#1076 Fix issues in combined auth schemes
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/ApplicationSecurity.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/mutualSSL.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Affected/3.1.0-alpha, Type/Bug

#1084 Introduce x-wso2-mutual-ssl extension and change x-wso2-transports
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/MutualSSL.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/TransportSecurity.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  distribution/resources/conf/default-micro-gw.conf.template
Labels: Type/Improvement

#1085 Bug fixes: gRPC service with multiple security schemes and distributed throttling
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/protobuf/ProtoOpenAPI.java
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  distribution/resources/conf/default-micro-gw.conf.template
  tests/src/test/java/org/wso2/micro/gateway/tests/grpc/BasicGrpcTestCase.java
  tests/src/test/resources/confs/base.conf
  tests/src/test/resources/protobuf/mgwProto/basicProto.proto
Labels: Type/Bug

#1087 Fix issue during QSG
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
Labels: Priority/Highest, Type/Bug

#1088 Update the docker file for beta release
  docker/Dockerfile
Labels: Type/Task

#1090 Update the README to work with new docker image
  README.md
Labels: Type/Task

#1106 change api key config
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/api_key_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/conf/Ballerina.toml
  distribution/resources/conf/default-micro-gw.conf.template
  distribution/resources/conf/micro-gw.conf
  tests/src/test/resources/confs/api-key.conf
Labels: Type/Improvement

#1115 Fix #1113 - Template the API base path with version
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Docs/Has Impact, Type/Improvement

#1117 Fix #1116 - Reduce integration test running time
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointOverrideTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointWithSecurityTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointsByReferenceTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/MultipleEndpointsTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/extensions/OASAPIInvokeTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/http2/HTTP2RequestsWithHTTP1BackEndTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/http2/HTTP2RequestsWithHTTP2BackEndTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithBasicAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithOAuth2andBasicAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithOAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/AuthenticationFailureTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/DisableSecurityAndCustomAuthHeaderTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/MutualSSLTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/ScopesTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/OpenApiThrottlingTestCase.java
  tests/src/test/resources/openAPIs/endpoints/endpoint_override.yaml
  tests/src/test/resources/openAPIs/endpoints/endpoint_security.yaml
  tests/src/test/resources/openAPIs/endpoints/load_balance.yaml
  tests/src/test/resources/testng.xml
Labels: Type/Task

#1071 Adding ubuntu docker image
  docker/README.md
  docker/alpine/Dockerfile
  docker/ubuntu/Dockerfile
Labels: Priority/Normal, Type/Task

#1122 Fix DCR version
  README.md
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/RESTServiceConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/TokenBuilder.java
Labels: Docs/No Impact, Priority/Normal, Type/Bug

#1112 Remove in-place plugin from distribution
  distribution/pom.xml
  distribution/src/main/assembly/linux_bin.xml
  distribution/src/main/assembly/macos_bin.xml
  distribution/src/main/assembly/windows_bin.xml
Labels: Type/Task

#1114 Improve error logs on extensions
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
Labels: Type/Bug

#1120 Bug fixes: Observability and Interceptor related issues.
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/observability_constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/filter_wrappers/analytics_request_filter_wrapper.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/filter_wrappers/validation_filter_wrapper.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/observability_util.bal
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
Labels: Type/Bug

#1124 Fix #1123 - Allow to specify max header, payload, URI length
  components/micro-gateway-cli/src/main/resources/templates/http1Settings.mustache
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  distribution/resources/conf/default-micro-gw.conf.template
Labels: Priority/Normal, Type/Improvement

#1127 Save the OpenAPI mapping created for the gRPC service
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
Labels: Type/Improvement

#1129 Fixes for schema validation feature
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_filter.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java
  distribution/pom.xml
  pom.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/extensions/OASAPIInvokeTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/validation/ValidationTestCase.java
  tests/src/test/resources/confs/validation.conf
  tests/src/test/resources/openAPIs/validation/PizzaShackAPI_swagger.json
  tests/src/test/resources/openAPIs/validation/validation_api.yaml
Labels: Priority/High, Type/Bug

#1130 Fix #839 - Need a way find toolkit/runtime version
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/CliCommands.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/VersionCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
  distribution/pom.xml
  distribution/resources/bin/gateway
  distribution/resources/version.txt
  distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
  distribution/src/main/assembly/linux_bin.xml
  distribution/src/main/assembly/macos_bin.xml
  distribution/src/main/assembly/windows_bin.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
Labels: Type/Improvement

#1131 Update Readme.md file
  Architecture.png
  README.md
  architecture.png
Labels: Type/Task

#1134 Fix #1103 - API key fails when oauth2 scopes are defined
  README.md
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/api_key_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  tests/src/test/java/org/wso2/micro/gateway/tests/apikey/APIKeyTestCase.java
  tests/src/test/resources/openAPIs/common_api.yaml
Labels: Type/Bug

#1132 Bug fix: allow Basic Auth with custom auth header
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/observability_constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/basic_auth_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/handler_wrappers/basic_auth_handler_wrapper.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  tests/src/test/java/org/wso2/micro/gateway/tests/grpc/BasicGrpcTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/DisableSecurityAndCustomAuthHeaderTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/ScopesTestCase.java
  tests/src/test/resources/confs/default-test-config.conf
  tests/src/test/resources/openAPIs/common_api.yaml
  tests/src/test/resources/openAPIs/endpoints/endpoint_security.yaml
  tests/src/test/resources/openAPIs/endpoints/endpoints_by_reference.yaml
  tests/src/test/resources/openAPIs/interceptor/PerAPIInterceptor.yaml
  tests/src/test/resources/openAPIs/interceptor/interceptor.yaml
  tests/src/test/resources/openAPIs/security/disable_security.yaml
  tests/src/test/resources/openAPIs/validation/validation_api.yaml
  tests/src/test/resources/policies.yaml
  tests/src/test/resources/protobuf/mgwProto/basicProto.proto
Labels: Type/Bug

#1137 Fix #839 - Need a way find toolkit/runtime version - Update regex #1130
  distribution/pom.xml
Labels: Resolution/Not a bug

#1139 Fix #925 - Support case insensitive token header prefix
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/basic_auth_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/key_validation_handler.bal
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithBasicAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithOAuth2andBasicAuthTestCase.java
Labels: Type/Bug

#1145 Bug fixes related to analytics file uploading and import command
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/data_writer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/file_rotating_timer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Type/Bug

#1140 Fixes issues in windows scripts
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/protobuf/ProtocCommandBuilder.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
  distribution/resources/bin/gateway.bat
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
Labels: Docs/No Impact, Priority/Normal, Type/Bug

#1146 Fix #1056 - Toolkit fails when toolkit path contains spaces
  distribution/resources/bin/gateway
  distribution/resources/bin/micro-gw
Labels: Type/Bug

#1144 Template the project Ballerina.toml file
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/BallerinaLibrary.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/BallerinaToml.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/mutualSSL_handler.bal
  distribution/resources/conf/Ballerina.toml
Labels: Docs/No Impact, Priority/Normal, Type/Bug

#1151 Fix #1148 #1149 - API level throttling issues in distributed setup
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/bin/gateway
  tests/src/test/java/org/wso2/micro/gateway/tests/extensions/OASAPIInvokeTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithBasicAuthTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/OpenApiThrottlingTestCase.java
  tests/src/test/resources/confs/default-test-config.conf
  tests/src/test/resources/openAPIs/throttling/throttle.yaml
Labels: Type/Bug

#1153 Add callhome feature for micro-gw toolkit and runtime
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-cli/src/main/resources/templates/main.mustache
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/callHome.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/callhome/Callhome.java
  distribution/pom.xml
  distribution/resources/updates/product_linux.txt
  distribution/resources/updates/product_macos.txt
  distribution/resources/updates/product_windows.txt
  distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
  distribution/src/main/assembly/linux_bin.xml
  distribution/src/main/assembly/macos_bin.xml
  distribution/src/main/assembly/windows_bin.xml
  pom.xml
Labels: Type/Task

#1152 Fix #1039 - Analytics error when authentication fails
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/responsetime_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
Labels: Type/Bug

#1154 Update the docker files
  docker/alpine/Dockerfile
  docker/ubuntu/Dockerfile
Labels: Type/Task

#1155 Fix for windows runtime when path contains spaces
  distribution/resources/bin/gateway.bat
Labels: Docs/No Impact, Priority/High, Type/Bug

#1156 Handle error in call home function
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/callhome/Callhome.java
Labels: Type/Task

#1157 Remove org.json dependency
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-interceptor/pom.xml
  distribution/pom.xml
  pom.xml
Labels: Type/Task

#1158 Update release note and License.txt
  distribution/LICENSE-RUNTIME.txt
  distribution/LICENSE-TOOLKIT.txt
  release-notes.html
Labels: Priority/High, Type/Task

#1159 Fix gRPC test case failures
  tests/src/test/java/org/wso2/micro/gateway/tests/grpc/BasicGrpcTestCase.java
  tests/src/test/resources/protobuf/mgwProto/basicProto.proto
Labels: test-improvements

#1160 Make call home function run asynchronously with time out
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
Labels: test-improvements

#1163 Revert development version
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-interceptor/pom.xml
  components/micro-gateway-tools/pom.xml
  components/pom.xml
  distribution/pom.xml
  distribution/resources/version.txt
  pom.xml
  tests/pom.xml
Labels: Priority/Highest, Type/Task

#1165 Fix #1150 #1162 #1164 - Java interceptor json array, oauth2 context missmatch and caching issues
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Entity.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Request.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Response.java
  tests/src/main/java/org/wso2/micro/gateway/tests/interceptor/TestInterceptor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/interceptor/JavaInterceptorTestCase.java
Labels: Type/Bug

#1168 Add java cacerst as the truststore for callhome in the toolkit
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
  distribution/resources/version.txt
Labels: Priority/High, Type/Bug

#1172 Schema Validation: Split schema validation Filter
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-cli/src/main/resources/templates/healthCheck.mustache
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/filter_wrappers/validation_filter_wrapper.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/filter_wrappers/validation_request_filter_wrapper.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/filter_wrappers/validation_response_filter_wrapper.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_request_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_response_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/validation_util.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java
  distribution/pom.xml
  docker/alpine/Dockerfile
  docker/ubuntu/Dockerfile
Labels: Priority/High, Type/Bug

#1174 Fix docker motd for bash
  distribution/pom.xml
  docker/alpine/Dockerfile
Labels: Docs/No Impact, Priority/Highest, Type/Task

#1175 Update release note
  release-notes.html
Labels: Priority/Highest, Type/Task
