Repository wso2/product-microgateway, pull requests merged in 2020-05, with the labels that each got.

#1222 Fix response interceptor
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
Labels: Affected/3.1.0, Type/Bug

#1218 Bug Fix #1215 :Allow to tracing alone
  components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/GetConfig.java
Labels: Type/Bug

#1220 Bug Fix #1219 : Check style failure in windows machine
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/ThrottlePolicyGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/HashingConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/exception/CLIZipException.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/exception/HashingException.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/hashing/Hash.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/hashing/HashUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/ApplicationSecurity.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIDetailedDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIInfoDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIListDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/EndpointUrlTypeEnum.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/ApplicationThrottlePolicyListDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/BandwidthLimitDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/CustomAttributeDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/RequestCountLimitDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/SubscriptionThrottlePolicyDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/SubscriptionThrottlePolicyListDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/ThrottlePolicyDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/EndpointListRouteDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaPath.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/protobuf/ProtoOpenAPI.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RESTAPIUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Entity.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Request.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Response.java
  components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/GetConfig.java
  components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/model/B7a.java
  components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/model/Metrics.java
  components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/model/Observability.java
  components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/model/Prometheus.java
Labels: Type/Task, test-improvements

#1224 Bug Fix : Not able to create docker image with debug enable #1191
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/DockerConfig.java
  components/micro-gateway-cli/src/main/resources/templates/dockerConfig.mustache
Labels: Affected/3.1.0, Type/Bug

#1230 Custom throttle policy support with central TM
  components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/api_throttle_out_constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/gateway_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/throttle_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/throttle.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/blocking_condition_retriever_task.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/key_template_retriever_task.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/global/ThrottleUtils.java
  distribution/resources/conf/default-micro-gw.conf.template
Labels: Type/Improvement

#1228 Fix multiple jms subscription
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
Labels: Docs/No Impact, Priority/Normal, Type/Bug

#1226 Add envoy gateway initial implementation
  .gitignore
  .travis.yml
  ENVOY_GW_README.md
  LICENSE
  cmd/microgateway/bootsrap.go
  docker-compose.yaml
  envoy.yaml
  go.mod
  internal/pkg/accesslogs/accesslogs.go
  internal/pkg/api/APIServer.go
  internal/pkg/api/ApiService.go
  internal/pkg/api/ConfigService.go
  internal/pkg/auth/auth.go
  internal/pkg/confTypes/mgwtypes.go
  internal/pkg/mgw/mgw.go
  internal/pkg/oasparser/apis/test.yaml
  internal/pkg/oasparser/config/config.go
  internal/pkg/oasparser/configGenerator.go
  internal/pkg/oasparser/constants/openApiConstants.go
  internal/pkg/oasparser/envoyCodegen/httpFilters.go
  internal/pkg/oasparser/envoyCodegen/listener.go
  internal/pkg/oasparser/envoyCodegen/routesWithClusters.go
  internal/pkg/oasparser/models/apiDefinition/mgwSwagger.go
  internal/pkg/oasparser/models/apiDefinition/openApi.go
  internal/pkg/oasparser/models/apiDefinition/swagger.go
  internal/pkg/oasparser/models/envoy/envoyNode.go
  internal/pkg/oasparser/swaggerOperator/swaggerOperator.go
  internal/pkg/oasparser/utills/opeApiUtills.go
  main.go
  resources/apis/test.yaml
  resources/bin/mgw
  resources/conf/config.toml
Labels: Type/New Feature

#1185 resolving formatting issues
  components/micro-gateway-cli/src/main/resources/templates/jwtRevocation.mustache
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockETCDServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/jwtRevocation/JWTRevocationSupportTestCase.java
Labels: Type/Task

#1242 Fix #1239 #802 : Provide endpoint proxy, pool, retry, circuit breaker configs
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/AdvanceEndpointConfigDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/CircuitBreakerConfigDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/EndpointRetryDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointListDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/PoolConfigDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/RollingWindowConfigDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/EndpointListRouteDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
  components/micro-gateway-cli/src/main/resources/templates/advanceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/circuitBreaker.mustache
  components/micro-gateway-cli/src/main/resources/templates/clientsHttp2.mustache
  components/micro-gateway-cli/src/main/resources/templates/endpointPoolConfig.mustache
  components/micro-gateway-cli/src/main/resources/templates/endpointProxy.mustache
  components/micro-gateway-cli/src/main/resources/templates/endpointRetry.mustache
  components/micro-gateway-cli/src/main/resources/templates/failoverEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/failoverEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/failoverResourceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/httpEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/httpEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/httpResourceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbResourceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/secureSocket.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/api_gateway_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/etcd_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/etcd_token_revocation_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/blocking_condition_retriever_task.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/key_template_retriever_task.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/endpoint_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/conf/default-micro-gw.conf.template
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/AdvanceEndpointConfigTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointsByReferenceTestCase.java
  tests/src/test/resources/openAPIs/endpoints/advance_config.yaml
  tests/src/test/resources/openAPIs/endpoints/endpoint_override.yaml
  tests/src/test/resources/openAPIs/endpoints/endpoint_security.yaml
  tests/src/test/resources/openAPIs/endpoints/endpoints_by_reference.yaml
  tests/src/test/resources/testng.xml
Labels: Docs/Has Impact, Type/Improvement

#1240 X-wso2-basepath support for Api definition
  cmd/microgateway/bootsrap.go
  config/tomlConfigParser.go
  internal/pkg/confTypes/mgwtypes.go
  internal/pkg/mgw/mgw.go
  internal/pkg/oasparser/config/config.go
  internal/pkg/oasparser/configGenerator.go
  internal/pkg/oasparser/constants/openApiConstants.go
  internal/pkg/oasparser/envoyCodegen/httpFilters.go
  internal/pkg/oasparser/envoyCodegen/listener.go
  internal/pkg/oasparser/envoyCodegen/routesWithClusters.go
  internal/pkg/oasparser/models/apiDefinition/mgwSwagger.go
  internal/pkg/oasparser/models/apiDefinition/openApi.go
  internal/pkg/oasparser/models/apiDefinition/swagger.go
  internal/pkg/oasparser/models/envoy/envoyNode.go
  internal/pkg/oasparser/swaggerOperator/swaggerOperator.go
  resources/apis/test2.yaml
  resources/conf/config.toml
Labels: Type/Improvement
