Repository wso2/product-microgateway, pull requests merged in 2020-08, with the labels that each got.

#1362 Fix replacing '\' in truststore path in windows.
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/conf/AgentConfiguration.java
Labels: Docs/No Impact, Priority/Normal, Type/Bug

#1345 Refactor Backend JWT generation and Implement default claim retriever Implementation
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/backend_jwt_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/config_dtos/apim_credentials_config.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/config_dtos/jwt_generator_config.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/config_dtos/listener_config.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/gateway_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/gateway_conf.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/handler_wrappers/jwt_auth_handler_wrapper.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/token_introspection_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/jwt_generator/claim_retriever.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/jwt_generator/jwt_gen_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/jwtGenerator.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/jwt/generator/MGWJWTGeneratorInvoker.java
  components/micro-gateway-jwt-generator/pom.xml
  components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/AbstractMGWClaimRetriever.java
  components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/MGWClaimRetrieverImpl.java
  components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/MGWJWTGeneratorImpl.java
Labels: Type/Improvement

#1361 Read jmx_port from args and env
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-core/pom.xml
  components/micro-gateway-interceptor/pom.xml
  components/micro-gateway-jwt-generator/pom.xml
  components/micro-gateway-jwt-transformer/pom.xml
  components/micro-gateway-tools/pom.xml
  components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/GetConfig.java
  components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/Main.java
  components/pom.xml
  distribution/pom.xml
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  tests/pom.xml
Labels: Priority/Normal, Type/Bug

#1367 Fix JWT revocation not working with APIM 3.1.0
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/revocation/revoked_jwt_retriever_task.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/revocation/revoked_token_map.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/callhome/Callhome.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/jwt/generator/MGWJWTGeneratorInvoker.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/mutualssl/LoadKeyStore.java
Labels: Type/Bug

#1371 Enable kay validation service
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/token_introspection_handler.bal
  distribution/resources/conf/default-micro-gw.conf.template
Labels: Priority/Normal, Type/Bug

#1368 Introduce conditional throttling
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/api_throttle_out_constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/throttle_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/throttle.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/global/ThrottleUtils.java
  distribution/resources/conf/default-micro-gw.conf.template
Labels: Priority/Normal, Type/Improvement

#1373 Fix apim application data response object type mismatch error
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/application_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_dtos.bal
  tests/src/test/resources/application-get-response.json
Labels: Type/Bug

#1374 Improve condition based throttling
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
Labels: Priority/Normal, Type/Bug

#1376 Fix JWT generation related issues.
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/application_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/backend_jwt_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/gateway_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/token_introspection_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/jwt_generator/claim_retriever.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/jwt_generator/jwt_gen_util.bal
  components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/MGWJWTGeneratorImpl.java
Labels: Priority/High, Type/Bug

#1379 Rename the service_url config to serviceUrl
  distribution/resources/conf/default-micro-gw.conf.template
  distribution/resources/conf/micro-gw.conf
Labels: Type/Bug

#1383 Set the ballerina thread pool size to 100
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
Labels: Type/Task

#1380 Update and simplify the README
  README.md
  architecture-new.png
Labels: Docs/No Impact, Priority/High, Type/Task

#1382 Upgrade b7a version and prepare for release
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/jwt/generator/MGWJWTGeneratorInvoker.java
  distribution/LICENSE-RUNTIME.txt
  distribution/LICENSE-TOOLKIT.txt
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/resources/version.txt
  distribution/src/main/assembly/filter.properties
  docker/README.md
  docker/alpine/Dockerfile
  docker/ubuntu/Dockerfile
  pom.xml
  release-notes.html
Labels: Type/Task

#1385 Remove templating the mgwVersion in ballerinaToml.mustache.
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
Labels: Priority/Highest, Type/Bug
