Repository wso2/product-microgateway, pull requests merged in 2020-02, with the labels that each got.

#967 Fix #919 - Cache for introspect endpoints
  components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  pom.xml
Labels: Type/Improvement

#961 Improvements to maven build
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  distribution/pom.xml
  distribution/src/main/assembly/bin.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
  pom.xml
  tests/pom.xml
Labels: Type/Task

#968 Build command fails on windows
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
Labels: Type/Bug

#974 x-wso2-owner extension addition
  .gitignore
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIDetailedDTO.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/responsetime_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
  distribution/resources/ballerinaTruststore.p12
  tests/src/test/resources/ballerinaTruststore.p12
  tests/src/test/resources/keyStores/ballerinaTruststore.p12
Labels: Priority/High, Type/Improvement

#973 Rename micro-gw-default.conf template and Refactor code
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/file_rotating_timer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/usagedata_uploader.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/handler_wrappers/api_key_handler_wrapper.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/api_key_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/token_revocation_etcd_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/conf/default-micro-gw.conf.template
  distribution/resources/conf/micro-gw.conf
  tests/src/test/java/org/wso2/micro/gateway/tests/apikey/APIKeyTestCase.java
  tests/src/test/resources/testng.xml
Labels: Priority/Normal, Type/Improvement

#975 Fix #881 - Implement new fixed window throttling
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/ThrottlePolicyGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/policy/ThrottlePolicyInitializer.java
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-cli/src/main/resources/templates/main.mustache
  components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/throttle_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/filter_wrappers/throttle_filter_wrapper.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/mutualSSL_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/throttle.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/DataProcessAgent.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleConfigHolder.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleCounter.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleData.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleDataCleanUpTask.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleDataReceiver.java
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/resources/conf/default-micro-gw.conf.template
  distribution/src/main/assembly/bin.xml
  pom.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
  tests/src/test/resources/testng.xml
Labels: Type/Improvement

#962 Make windows executable work with jballerina
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  distribution/resources/bin/gateway.bat
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
Labels: Type/Improvement

#977 Fix #976 #774 - K8s issues and pull from private registries
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesDeployment.java
  components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
  components/micro-gateway-cli/src/main/resources/templates/kubernetesConfigMap.mustache
  components/micro-gateway-cli/src/main/resources/templates/kubernetesDeployment.mustache
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
Labels: Affected/3.0.2, Type/Bug

#981 Restructure distribution for jballerina
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/DockerConfig.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
  components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
  components/micro-gateway-cli/src/main/resources/templates/dockerConfig.mustache
  components/micro-gateway-core/assembly/bir.xml
  components/micro-gateway-core/assembly/jar.xml
  components/micro-gateway-core/assembly/jms_zip.xml
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/scripts/ballerina-build.bat
  components/micro-gateway-core/scripts/ballerina-build.sh
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/observability_listener.bal
  components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/Main.java
  components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/UnzipUtility.java
  distribution/pom.xml
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
  distribution/resources/conf/default-micro-gw.conf.template
  distribution/resources/conf/micro-gw.conf
  distribution/src/main/assembly/bin.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
  docker/Dockerfile
  docker/README.md
  tests/src/test/resources/confs/base.conf
  tests/src/test/resources/confs/http2-test.conf
Labels: Docs/Has Impact, Priority/High, Type/Task

#979 Fix #736 - Readiness and liveness probe support in deployment.toml
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesDeployment.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/ProbeConfig.java
  components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
  components/micro-gateway-cli/src/main/resources/templates/kubernetesDeployment.mustache
Labels: Type/Improvement

#983 Fix #982 - Improve performance in throttle and pre auth filter
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/throttle.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleConfigHolder.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleDataReceiver.java
  distribution/resources/conf/default-micro-gw.conf.template
Labels: Type/Improvement

#989 Mutual SSL authentication for API
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/TransportSecurity.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/ext/ExtendedAPI.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/api_key_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/mutualSSL_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Docs/Has Impact, Type/New Feature

#993 Fix #992 - Java interceptor support
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GeneratorConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-cli/src/main/resources/templates/main.mustache
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/interceptor.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/interceptors/InterceptorInvoker.java
  components/micro-gateway-interceptor/pom.xml
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Caller.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Constants.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Interceptor.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/InterceptorException.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Request.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Response.java
  components/pom.xml
  distribution/pom.xml
  distribution/resources/conf/Ballerina.toml
  pom.xml
Labels: Docs/Has Impact, Type/New Feature

#998 Fix dcr version
  README.md
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/RESTServiceConstants.java
  distribution/resources/cli-conf/toolkit-config.toml
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java
  tests/src/test/resources/confs/default-cli-test-config.toml
Labels: Type/Task

#999 Fixes the openAPIJsonConstants.json issue while starting the micro-gw
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
Labels: Docs/No Impact, Priority/Normal

#1001 Remove cookie handler
  components/micro-gateway-core/src/main/ballerina/src/gateway/cookie.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/cookie_handler.bal
Labels: Type/Bug

#1002 Update QSG on readme file
  README.md
Labels: Type/Task

#1008 Correct missing grpc logic
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
Labels: Type/Bug

#1006 Add policy hub feature
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaInterceptor.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/caching.mustache
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
Labels: Docs/Has Impact, Type/New Feature

#1004 Create separate toolkit distributions for different operating systems.
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/GetConfig.java
  distribution/pom.xml
  distribution/resources/bin/gateway
  distribution/resources/bin/micro-gw
  distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
  distribution/src/main/assembly/linux_bin.xml
  distribution/src/main/assembly/macos_bin.xml
  distribution/src/main/assembly/windows_bin.xml
  tests/pom.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/grpc/BasicGrpcTestCase.java
  tests/src/test/resources/testng.xml
Labels: Type/Improvement

#1010 Fix #690 - Add health check endpoint
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GeneratorConstants.java
  components/micro-gateway-cli/src/main/resources/templates/healthCheck.mustache
  components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
Labels: Type/Improvement

#1009 Change the dockerfile base image
  distribution/resources/bin/gateway
  distribution/resources/bin/micro-gw
  distribution/src/main/assembly/macos_bin.xml
  docker/Dockerfile
Labels: Type/Improvement

#1016 Make --docker build command optional for Docker
  README.md
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/resources/cli-help/cli-build.help
Labels: Type/Improvement

#1014 Fixes mutual ssl and api key test
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/api_security_constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authz_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/mutualSSL_handler.bal
  tests/src/test/java/org/wso2/micro/gateway/tests/apikey/APIKeyTestCase.java
  tests/src/test/resources/confs/api-key.conf
Labels: Type/Bug

#1017 upgrade ballerina 1.1.1 to 1.1.2
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  distribution/resources/conf/Ballerina.toml
  pom.xml
Labels: Type/Task

#1023 Multiple JWT issuers support
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/TransportSecurity.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/filter_wrappers/subscription_filter_wrapper.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_secure_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/api_key_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/conf/default-micro-gw.conf.template
  distribution/resources/conf/micro-gw.conf
  tests/src/test/java/org/wso2/micro/gateway/tests/util/TokenUtil.java
  tests/src/test/resources/confs/base.conf
  tests/src/test/resources/confs/default-test-config.conf
  tests/src/test/resources/confs/throttle-test-config.conf
Labels: Type/Improvement

#1032 Remove authorization header
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authz_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/key_validation_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/conf/default-micro-gw.conf.template
Labels: Affected/3.1.0-alpha, Type/Bug

#1028 Update API Manager cert and Fix mutual SSL error code
  components/micro-gateway-cli/src/main/resources/policies/throttle_policy_initializer.bal
  components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/api_security_constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/mutualSSL_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/token_revocation_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/api_key_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/ballerinaTruststore.p12
  distribution/resources/conf/default-micro-gw.conf.template
  distribution/resources/conf/micro-gw.conf
  tests/src/test/resources/ballerinaTruststore.p12
  tests/src/test/resources/confs/base.conf
  tests/src/test/resources/wso2carbon.jks
Labels: Type/Improvement

#1045 Fix the issue when the backend security is applied only for resources
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
Labels: Affected/3.1.0-alpha, Type/Bug

#1036 Fix default key type in jwt handler
  components/micro-gateway-cli/src/main/resources/policies/throttle_policy_initializer.bal
  components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
Labels: Affected/3.1.0-alpha, Type/Bug

#1042 Fix api level security
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Affected/3.1.0-alpha

#1049 Send backend jwt header if jwt has backendJwt claim
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/key_validation_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Affected/3.1.0-alpha, Type/Bug

#1047 Change ballerina base dist and docker image
  distribution/pom.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
  distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
  distribution/src/main/assembly/linux_bin.xml
  distribution/src/main/assembly/macos_bin.xml
  distribution/src/main/assembly/platform_zip.xml
  distribution/src/main/assembly/runtime_zip.xml
  distribution/src/main/assembly/windows_bin.xml
  docker/Dockerfile
Labels: Priority/Normal, Type/Task

#1061 Fix #1059 - Issues running in k8s
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesDeployment.java
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  distribution/resources/bin/gateway
Labels: Affected/3.1.0-alpha, Type/Bug

#1065 Fix #1051 - Issue in recovering from throttle out state and etcd issue
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/ThrottlePolicyGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GeneratorConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/policy/ThrottlePolicyInitializer.java
  components/micro-gateway-cli/src/main/resources/templates/endpointReinit.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/etcd_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleCounter.java
Labels: Affected/3.1.0-alpha

#1069 Java interceptor feature- provide payload modification
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/interceptors/InterceptorInvoker.java
  components/micro-gateway-interceptor/pom.xml
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Caller.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Constants.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Entity.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/InterceptorUtils.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/MGWBlockingCallBack.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Request.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Response.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Utils.java
  distribution/pom.xml
  distribution/resources/conf/Ballerina.toml
  pom.xml
  tests/pom.xml
  tests/src/main/java/org/wso2/micro/gateway/tests/interceptor/TestInterceptor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/context/Constants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/interceptor/InterceptorTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/interceptor/JavaInterceptorTestCase.java
  tests/src/test/resources/openAPIs/interceptor/interceptor.yaml
  tests/src/test/resources/testng.xml
Labels: Type/Improvement

#1073 Fix #1019 - Throttling consistant with APIM
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/annotation.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/api_throttle_out_constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/throttle_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/throttle.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/DataProcessAgent.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleCounter.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleData.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleDataReceiver.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/throttling/OpenApiThrottlingTestCase.java
Labels: Affected/3.1.0-alpha, Type/Bug

#1075 Fix #1048 - Scope issue with opaque tokens
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authz_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/cli-conf/toolkit-config.toml
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java
  tests/src/test/resources/confs/default-cli-test-config.toml
Labels: Affected/3.1.0-alpha, Type/Bug

#1077 Improve jwt revocation feature
  components/micro-gateway-cli/src/main/resources/templates/jwtRevocation.mustache
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/scripts/ballerina-build.sh
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/token_revocation_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/token_revocation_etcd_util.bal
Labels: Priority/High, Type/Improvement

#1078 Remove docker k8s libs from toolkit
  distribution/pom.xml
  distribution/src/main/assembly/linux_bin.xml
  distribution/src/main/assembly/macos_bin.xml
  distribution/src/main/assembly/windows_bin.xml
Labels: Priority/Normal, Type/Task
