Repository wso2/product-microgateway, pull requests merged in 2020-06, with the labels that each got.

#1211 Fix tokenContext "/"
  components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Affected/3.1.0, Type/Bug

#1214 Bug Fix : OpenAPI file generated for the proto file is not valid
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/ProtoToOpenAPIConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/protobuf/ProtoOpenAPI.java
Labels: Affected/3.1.0, Type/Bug

#1250 Avoid overriding backend auth responses
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authz_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointWithSecurityTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointsByReferenceTestCase.java
  tests/src/test/resources/openAPIs/endpoints/endpoint_security.yaml
Labels: Docs/No Impact, Priority/Normal, Type/Improvement

#1252 Update EP override params
  README.md
Labels: Docs/Has Impact, Priority/Normal, Type/Docs

#1256 Fix a test failure
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointsByReferenceTestCase.java
  tests/src/test/resources/openAPIs/endpoints/endpoint_security.yaml
Labels: Docs/No Impact, Priority/Normal, Type/Task

#1251 Backend JWT token generation support within microgateway (updated)
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/jwtGenerator.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/jwt/generator/AbstractMGWJWTGenerator.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/jwt/generator/MGWJWTGeneratorImpl.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/jwt/generator/MGWJWTGeneratorInvoker.java
  distribution/resources/conf/default-micro-gw.conf.template
  pom.xml
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/jwtGenerator/JWTGenerationTestCase.java
  tests/src/test/resources/confs/base.conf
  tests/src/test/resources/confs/jwt-generator-test-config.conf
  tests/src/test/resources/openAPIs/jwtGeneration/jwt_generation.yaml
  tests/src/test/resources/testng.xml
Labels: Affected/3.1.0, Type/New Feature

#1180 Improvement to support multiple token issuers with Claim Mappings #1179
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/jwt_mapping.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/mapping/MappingInvoker.java
  components/micro-gateway-jwt-transformer/pom.xml
  components/micro-gateway-jwt-transformer/src/main/java/org/wso2/micro/gateway/jwt/transformer/JWTValueTransformer.java
  components/pom.xml
  distribution/pom.xml
  distribution/resources/conf/default-micro-gw.conf.template
  pom.xml
  tests/pom.xml
  tests/src/main/java/org/wso2/micro/gateway/tests/jwtvaluetransformer/DefaultJwtTransformer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/context/Constants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/jwtTransformer/JwtTransformerTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/util/TokenUtil.java
  tests/src/test/resources/confs/jwt-transformer-test-config.conf
  tests/src/test/resources/openAPIs/jwtTransformer/jwt_transformer.yaml
  tests/src/test/resources/testng.xml
Labels: Affected/3.1.0, Type/New Feature

#1262 Fix #1261 - Support reading configurations from interceptor library
  components/micro-gateway-interceptor/pom.xml
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/ConfigUtils.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/InterceptorUtils.java
  pom.xml
  tests/src/main/java/org/wso2/micro/gateway/tests/interceptor/ConfigInterceptor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/interceptor/JavaInterceptorTestCase.java
  tests/src/test/resources/openAPIs/interceptor/interceptor.yaml
Labels: Type/Improvement

#1245 Add log4j logger for native implementation
  components/micro-gateway-cli/src/main/resources/templates/endpointReinit.mustache
  components/micro-gateway-cli/src/main/resources/templates/main.mustache
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/observability_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/logConfiguration.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/observability_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/interceptors/InterceptorInvoker.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/jwt/generator/AbstractMGWJWTGenerator.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/jwt/generator/MGWJWTGeneratorImpl.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/jwt/generator/MGWJWTGeneratorInvoker.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/logging/Log4j2Configuration.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/mapping/MappingInvoker.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleCounter.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleDataCleanUpTask.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleDataReceiver.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/global/ThrottleUtils.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  pom.xml
Labels: Type/Improvement

#1247 Support event publishing to multiple Traffic Managers
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-cli/src/main/resources/templates/main.mustache
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/throttle_config_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/globalThrottleEventPublisher.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/ThrottleAgent.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/AgentHolder.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/DataEndpointAgent.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/DataPublisher.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/client/AbstractClientPoolFactory.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/client/AbstractSecureClientPoolFactory.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/client/ClientPool.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/conf/AgentConfiguration.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/conf/DataEndpointConfiguration.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/endpoint/DataEndpoint.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/endpoint/DataEndpointConnectionWorker.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/endpoint/DataEndpointFailureCallback.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/endpoint/DataEndpointGroup.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/endpoint/EventPublisherThreadPoolExecutor.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/endpoint/WrappedEventFactory.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/endpoint/binary/BinaryClientPoolFactory.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/endpoint/binary/BinaryDataEndpoint.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/endpoint/binary/BinaryEventSender.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/endpoint/binary/BinarySecureClientPoolFactory.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/exception/DataEndpointAuthenticationException.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/exception/DataEndpointConfigurationException.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/exception/DataEndpointException.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/exception/EventQueueFullException.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/util/DataAgentConstants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/util/DataEndpointConstants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/util/DataPublisherUtil.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/util/SecurityConstants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/util/ThrottleEventConstants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/publisher/DataProcessAndPublishingAgent.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/publisher/DataPublisherConstants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/publisher/PublisherConfiguration.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/publisher/ThrottleDataPublisher.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/publisher/ThrottleDataPublisherPool.java
  distribution/pom.xml
  distribution/resources/conf/default-micro-gw.conf.template
  distribution/resources/conf/micro-gw.conf
  pom.xml
  tests/src/test/resources/confs/throttle-test-config.conf
Labels: Type/Improvement

#1253 Make api_definitions optional for build
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GeneratorConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
  components/micro-gateway-cli/src/main/resources/templates/generateSwagger.mustache
Labels: Type/Bug

#1249 Fix #988 - Support mutual SSL in API level
  components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/handler_wrappers/mutualSSL_handler_wrapper.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/mutualSSL_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/mutualSSL.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/mutualssl/CertificateUtils.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/mutualssl/LoadKeyStore.java
  distribution/resources/conf/default-micro-gw.conf.template
  tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/context/Constants.java
  tests/src/test/resources/confs/jwt-transformer-test-config.conf
Labels: Affected/3.1.0, Type/Improvement

#1266 Added a separate module for backend JWT generation
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/jwt/generator/MGWJWTGeneratorInvoker.java
  components/micro-gateway-jwt-generator/pom.xml
  components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/AbstractMGWJWTGenerator.java
  components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/MGWJWTGeneratorImpl.java
  components/pom.xml
  distribution/pom.xml
  distribution/resources/conf/default-micro-gw.conf.template
  pom.xml
  tests/pom.xml
  tests/src/main/java/org/wso2/micro/gateway/tests/jwtgenerator/TestJWTGenerator.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/context/Constants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/jwtGenerator/JWTGenerationTestCase.java
  tests/src/test/resources/confs/jwt-generator-test-config.conf
Labels: Type/Improvement

#1268 Fix #1267 - Upgrade to ballerina 1.2.4
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/data_writer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/callHome.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/compression.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/globalThrottleEventPublisher.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/interceptor.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/jwtGenerator.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/jwt_mapping.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/logConfiguration.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/mutualSSL.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/throttle.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/validator.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/token_revocation_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/emitOnStateChange.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/throttle_window.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/time_batch.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/lang_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/MGWBlockingCallBack.java
  distribution/pom.xml
  pom.xml
Labels: Type/Task

#1274 Fixed the Base64 encoding padding issue
  components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/AbstractMGWJWTGenerator.java
Labels: Type/Bug

#1271 Fix #1270 - Improve per API mutual ssl validation logic
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/mutualSSL_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/mutualssl/CertificateUtils.java
  distribution/resources/conf/default-micro-gw.conf.template
Labels: Type/Bug

#1278 Fix #1217 - Provide a method to read open API definition
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
  components/micro-gateway-cli/src/main/resources/templates/main.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/native/validator.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/utils/CommonUtils.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Utils.java
  components/pom.xml
  tests/pom.xml
  tests/src/main/java/org/wso2/micro/gateway/tests/interceptor/OpenAPIReadInterceptor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/interceptor/JavaInterceptorTestCase.java
  tests/src/test/resources/openAPIs/interceptor/interceptor.yaml
Labels: Type/Improvement

#1283 Fix #1279 #1280 - opaque token validation issue and API level throttling
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/gateway_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/blocking_condition_retriever_task.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/key_template_retriever_task.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  components/pom.xml
  distribution/resources/conf/default-micro-gw.conf.template
Labels: Type/Bug

#1284 Prepare for alpha release
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  distribution/src/main/assembly/filter.properties
  docker/alpine/Dockerfile
  docker/ubuntu/Dockerfile
  release-notes.html
Labels: Type/Task

#1285 Add datastores for new subscription validation
  components/micro-gateway-cli/src/main/resources/policies/subscription_Gold.bal
  components/micro-gateway-cli/src/main/resources/templates/jwtRevocation.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/api_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/application_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/key_mapping_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_data_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/subscription_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/gateway_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/gateway_pilot_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/token_revocation_etcd_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Priority/Normal, Type/Task

#1260 Add Unit test structure for Envoy mgw oasparser package
  go.mod
  go.sum
  internal/pkg/confTypes/mgwtypes.go
  internal/pkg/oasparser/configGenerator.go
  internal/pkg/oasparser/envoyCodegen/routesWithClusters.go
  internal/pkg/oasparser/envoyCodegen/routesWithClusters_test.go
  internal/pkg/oasparser/models/apiDefinition/mgwSwagger.go
  internal/pkg/oasparser/models/apiDefinition/mgwSwagger_internal_test.go
  internal/pkg/oasparser/models/apiDefinition/openApi.go
  internal/pkg/oasparser/models/apiDefinition/openApi_internal_test.go
  internal/pkg/oasparser/models/apiDefinition/swagger.go
  internal/pkg/oasparser/models/apiDefinition/swagger_internal_test.go
  internal/pkg/oasparser/swaggerOperator/swaggerOperator.go
  internal/pkg/oasparser/swaggerOperator/swaggerOperator_test.go
  internal/pkg/oasparser/utills/opeApiUtills.go
  internal/pkg/oasparser/utills/openApiUtills_test.go
  resources/apis/test2.yaml
Labels: Type/Task

#1293 Fix #1258 - Initial support for jms subcription data retrieval
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/api_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/application_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/key_mapping_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_data_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/subscription_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/gateway_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/gateway_pilot_endpoint.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/gateway_jms_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/conf/default-micro-gw.conf.template
  distribution/resources/conf/micro-gw.conf
Labels: Type/Improvement, Type/New Feature

#1299 Fix #1258 - Add tenantwise data stores in mgw side
  components/micro-gateway-cli/src/main/resources/templates/main.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/api_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/application_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/key_mapping_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_data_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/apim/subscription_data_store.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/gateway_jms_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
  distribution/resources/conf/default-micro-gw.conf.template
  distribution/resources/conf/micro-gw.conf
Labels: Type/Improvement

#1301 Fixes the api name replacement issue in microgateway.
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GeneratorConstants.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Labels: Type/Bug
