Repository wso2/product-microgateway, pull requests merged in 2020-11, with the labels that each got.

#1471 Improvements to jwt validation
  build.sh
  docker/with-external-build/docker-compose.yaml
  docker/with-external-build/filter-chain/Dockerfile
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/config/MGWConfiguration.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/constants/ConfigConstants.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/dto/TokenIssuerDto.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/grpc/server/AuthServer.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/models/ApplicationKeyMapping.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/models/ApplicationKeyMappingCacheKey.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/security/KeyValidator.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/security/jwt/JWTAuthenticator.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/security/jwt/validator/JWTValidator.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/subscription/SubscriptionDataLoaderImpl.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/subscription/SubscriptionDataStoreImpl.java
  filter-core/src/main/resources/filter.conf
  filter-core/src/main/resources/wso2carbon.pem
  resources/client-truststore.jks
Labels: Priority/High, Type/Improvement, envoy-gw

#1474 Add a developer guide
  developer-guide.md
Labels: Type/Task

#1473 Load API from checkrequest info
  developer-guide.md
  distribution/pom.xml
  distribution/src/main/assembly/assembly.xml
  docker/with-external-build/docker-compose.yaml
  filter-core/src/main/assembly/assembly.xml
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/api/API.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/api/APIFactory.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/api/RestAPI.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/config/MGWConfiguration.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/constants/APIConstants.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/constants/ConfigConstants.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/grpc/server/AuthServer.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/grpc/server/RequestHandler.java
  filter-core/src/main/java/org/wso2/micro/gateway/filter/core/subscription/SubscriptionDataLoaderImpl.java
  filter-core/src/main/resources/Dockerfile
  pilot/pkg/oasparser/envoyCodegen/envoyCodegen_internal_test.go
  pilot/pkg/oasparser/envoyCodegen/routesWithClusters.go
  resources/apis/test2.yaml
  resources/conf/config.toml
  resources/conf/log4j2.properties
  resources/docker-compose.yaml
  resources/filter-core/conf/filter.conf
Labels: Type/Improvement

#1476 Resolve Bugs related to routing
  pilot/build.sh
  pilot/configs/confTypes/mgwtypes.go
  pilot/go.mod
  pilot/pkg/oasparser/envoyCodegen/envoyCodegen_internal_test.go
  pilot/pkg/oasparser/envoyCodegen/httpFilters.go
  pilot/pkg/oasparser/envoyCodegen/listener.go
  pilot/pkg/oasparser/envoyCodegen/routesWithClusters.go
  pilot/pkg/oasparser/envoyCodegen/routesWithClusters_test.go
  pilot/pkg/oasparser/models/apiDefinition/mgwResource.go
  pilot/pkg/oasparser/models/apiDefinition/mgwSwagger.go
  pilot/pkg/oasparser/models/apiDefinition/openApi.go
  pilot/pkg/oasparser/models/apiDefinition/openApi_internal_test.go
  pilot/pkg/oasparser/models/apiDefinition/swagger.go
  pilot/pkg/oasparser/models/apiDefinition/swagger_internal_test.go
  pilot/pkg/xds/xds_server.go
  pilot/src/main/resources/Dockerfile
  pilot/test-resources/envoycodegen/openapi.yaml
  pilot/test-resources/envoycodegen/openapi_with_extensions_only.yaml
  pilot/test-resources/envoycodegen/openapi_with_extensions_servers.yaml
  pilot/test-resources/envoycodegen/swagger_with_extensions.yaml
  resources/conf/config.toml
  resources/conf/log_config.toml
Labels: Type/Bug, envoy-gw

#1478 Support https endpoints when the certificate is CA-signed
  pilot/pkg/oasparser/envoyCodegen/routesWithClusters.go
  pilot/pkg/oasparser/models/apiDefinition/openApi.go
  pilot/pkg/oasparser/models/apiDefinition/openApi_internal_test.go
  pilot/pkg/oasparser/swaggerOperator/swaggerOperator_test.go
Labels: Type/New Feature, envoy-gw

#1482 Update README.md with envoy gateway changes
  Architecture.png
  README.md
Labels: Type/Task, envoy-gw

#1481 Update default certs
  resources/certs/localhost.key
  resources/certs/localhost.pem
  resources/certs/req.conf
Labels: Type/Task, envoy-gw

#1484 doc issue
  README.md
Labels: Type/Bug

#1486 Validate with subscribedAPIs
  enforcer/pom.xml
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/JWTAuthenticator.java
Labels: Type/Improvement, envoy-gw

#1487 Rename proxy as router
  Architecture.png
  README.md
  pom.xml
  resources/docker-compose.yaml
  router/pom.xml
  router/src/main/assembly/assembly.xml
  router/src/main/resources/Dockerfile
Labels: Priority/High, envoy-gw

#1488 Prepare for 4.0.0-m1 release
  adapter/pom.xml
  developer-guide.md
  enforcer/pom.xml
  remove-containers.sh
  resources/docker-compose.yaml
  router/pom.xml
Labels: Priority/Highest, envoy-gw

#1489 Prepare for 4.0.0-m2 dev cycle
  adapter/pom.xml
  developer-guide.md
  distribution/pom.xml
  enforcer/pom.xml
  pom.xml
  remove-containers.sh
  resources/docker-compose.yaml
  router/pom.xml
Labels: Priority/Highest, Type/Task, envoy-gw

#1490 Add go lint and go vet checks to adapter implementation
  adapter/build.sh
  adapter/cmd/microgateway/bootsrap.go
  adapter/config/logtypes.go
  adapter/config/mgwtypes.go
  adapter/config/tomlConfigParser.go
  adapter/configs/confTypes/mgwtypes.go
  adapter/configs/tomlConfigParser.go
  adapter/go.mod
  adapter/go.sum
  adapter/loggers/logger.go
  adapter/main.go
  adapter/pkg/api/file_read_utils.go
  adapter/pkg/api/restserver/config_restapi.go
  adapter/pkg/auth/auth.go
  adapter/pkg/logging/logConstants.go
  adapter/pkg/logging/packageLogs.go
  adapter/pkg/logging/rootLogs.go
  adapter/pkg/mgw/mgw.go
  adapter/pkg/oasparser/configGenerator.go
  adapter/pkg/oasparser/envoyconf/constants.go
  adapter/pkg/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/pkg/oasparser/envoyconf/httpFilters.go
  adapter/pkg/oasparser/envoyconf/listener.go
  adapter/pkg/oasparser/envoyconf/routesWithClusters.go
  adapter/pkg/oasparser/envoyconf/routesWithClusters_test.go
  adapter/pkg/oasparser/model/constants.go
  adapter/pkg/oasparser/model/mgwResource.go
  adapter/pkg/oasparser/model/mgwSwagger.go
  adapter/pkg/oasparser/model/mgwSwagger_internal_test.go
  adapter/pkg/oasparser/model/openApi.go
  adapter/pkg/oasparser/model/openApi_internal_test.go
  adapter/pkg/oasparser/model/swagger.go
  adapter/pkg/oasparser/model/swagger_internal_test.go
  adapter/pkg/oasparser/models/apiDefinition/mgwSwagger.go
  adapter/pkg/oasparser/models/envoy/envoyNode.go
  adapter/pkg/oasparser/operator/operator.go
  adapter/pkg/oasparser/operator/operator_test.go
  adapter/pkg/oasparser/utills/opeApiUtills.go
  adapter/pkg/oasparser/utills/openApiUtills_test.go
  adapter/pkg/xds/xds_server.go
  enforcer/pom.xml
  go.mod
  go.sum
  remove-containers.sh
  resources/conf/config.toml
Labels: Type/Task, envoy-gw

#1493 Add getters for caches
  components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
Labels: Priority/Normal, Type/Improvement

#1505 Fixes analytics destination not oveeriding issue.
  components/micro-gateway-cli/src/main/resources/templates/analyticsDestination.mustache
  components/micro-gateway-cli/src/main/resources/templates/useAPIProdEp.mustache
  components/micro-gateway-cli/src/main/resources/templates/useApiSandEp.mustache
  components/micro-gateway-cli/src/main/resources/templates/useResourceProdEp.mustache
  components/micro-gateway-cli/src/main/resources/templates/useResourceSandEp.mustache
Labels: Affected/3.2.0, Priority/Normal, Type/Bug
