Repository wso2/product-microgateway, pull requests merged in 2020-10, with the labels that each got.

#1420 Remove docker artifacts
  docker/README.md
  docker/alpine/Dockerfile
  docker/ubuntu/Dockerfile
Labels: Docs/No Impact, Priority/High, Type/Task

#1431 Redirect doc issue creation to docs-mg
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation_template.md
  .github/pull_request_template.md
Labels: Priority/Normal, Type/Docs, Type/Task

#1417 Add mutual ssl backend support.
  components/micro-gateway-cli/src/main/resources/templates/secureSocket.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/observability_constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/observability_service.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  distribution/resources/conf/default-micro-gw.conf.template
Labels: Priority/Normal, Type/Improvement

#1436 Make server header configurable and issues in 3rd party jwts
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
  distribution/resources/conf/default-micro-gw.conf.template
Labels: Priority/Normal, Type/Bug, Type/Improvement, hacktoberfest-accepted

#1437 Fix inconsistency when updating APIM custom throttling policies
  components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/throttle_dtos.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/key_template_retriever_task.bal
Labels: Priority/Normal, Type/Bug, hacktoberfest-accepted

#1439 Upgrade some dependencies
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/protobuf/ProtobufParser.java
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  distribution/pom.xml
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
  distribution/resources/version.txt
  pom.xml
  tests/pom.xml
Labels: Priority/Normal, Type/Improvement, Type/Task, hacktoberfest-accepted

#1440 Prepare for 3.2.1 release
  README.md
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/jwt/generator/MGWJWTGeneratorInvoker.java
  distribution/LICENSE-RUNTIME.txt
  distribution/LICENSE-TOOLKIT.txt
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/resources/version.txt
  distribution/src/main/assembly/filter.properties
  release-notes.html
  samples/sample-jwt-generator/pom.xml
Labels: Priority/High, Type/Task
