Repository wso2/product-microgateway, pull requests merged in 2020-12, with the labels that each got.

#1492 Change enforcer imgae to alpine base image
  enforcer/src/main/resources/Dockerfile
Labels: Type/Task, envoy-gw

#1521 Add petstore v3 yaml for QSG
  samples/petstore_v3.yaml
Labels: Type/Task

#1511 [Envoy-Mgw] Add Integration tests
  docker-compose.yaml
  pom.xml
  remove-containers.sh
  resources/envoy.yaml
  test/mock-backend-server/pom.xml
  test/mock-backend-server/src/main/assembly/assembly.xml
  test/mock-backend-server/src/main/java/org.wso2am.micro.gw.mockbackend/Constants.java
  test/mock-backend-server/src/main/java/org.wso2am.micro.gw.mockbackend/MockBackEndServer.java
  test/mock-backend-server/src/main/java/org.wso2am.micro.gw.mockbackend/ResponseConstants.java
  test/mock-backend-server/src/main/resources/Dockerfile
  test/pom.xml
  test/test-integration/pom.xml
  test/test-integration/src/main/resources/project.properties
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/apiDeploy/APiDeployTestCase.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/common/BaseTestCase.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/common/model/API.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/common/model/ApplicationDTO.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/common/model/ApplicationPolicy.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/common/model/DefaultLimit.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/common/model/SubscribedApiDTO.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/common/model/SubscriptionPolicy.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/context/MgwServer.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/context/MgwServerInstance.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/context/MicroGWTestException.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/jwtValidator/JwtTestCase.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/listener/TestNGListener.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/mockbackend/MockBackendServer.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/ApiDeployment.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/ApiProjectGenerator.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/HttpClientRequest.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/HttpPostMultipart.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/HttpResponse.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/HttpsClientRequest.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/HttpsPostMultipart.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/TestConstant.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/TokenUtil.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/Utils.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/ZipDir.java
  test/test-integration/src/test/resources/apis/openApis/mockApi.yaml
  test/test-integration/src/test/resources/backend-service.yaml
  test/test-integration/src/test/resources/keystore/wso2carbon.jks
  test/test-integration/src/test/resources/testng.xml
Labels: envoy-gw

#1523 [Envoy-MGW] Change failsafe plugin to surefire to run test cases in integration tests
  pom.xml
  test/test-integration/pom.xml
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/apiDeploy/APiDeployTestCase.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/ApiDeployment.java
Labels: test-improvements

#1516 Reformat maven dependencies
  adapter/pom.xml
  enforcer/pom.xml
  pom.xml
  router/pom.xml
  test/test-integration/pom.xml
Labels: Priority/Normal, Type/Task, envoy-gw
