Repository wso2/product-microgateway, pull requests merged in 2020-04, with the labels that each got.

#1200 Fix duplicate variable name error
  components/micro-gateway-cli/src/main/resources/templates/basicAuth.mustache
  components/micro-gateway-cli/src/main/resources/templates/basicAuthHandler.mustache
Labels: Type/Bug

#1208 Upgrade to b7a 1.1.5
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  distribution/resources/version.txt
  pom.xml
Labels: Priority/Normal

#1209 Fix #1207 - Issue when endpoint url contain special characters
  components/micro-gateway-cli/src/main/resources/templates/failoverEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/failoverEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/failoverResourceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/httpEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/httpResourceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbResourceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/pathParameters.mustache
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Constants.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/InterceptorUtils.java
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Request.java
  tests/src/main/java/org/wso2/micro/gateway/tests/interceptor/TestInterceptor.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/ResourceLevelEndpointsTestCase.java
  tests/src/test/java/org/wso2/micro/gateway/tests/grpc/GrpcServer.java
  tests/src/test/java/org/wso2/micro/gateway/tests/interceptor/JavaInterceptorTestCase.java
  tests/src/test/resources/openAPIs/common_api.yaml
  tests/src/test/resources/openAPIs/interceptor/interceptor.yaml
  tests/src/test/resources/protobuf/mgwProto/basicProto.proto
Labels: Affected/3.1.0, Priority/Normal, Type/Bug
