Repository wso2/product-microgateway, pull requests merged in 2021-12, with the labels that each got.

#2472 bug-fix: subscription throttling does not work for self contained access token
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/throttle/SubscriptionThrottlingTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TokenUtil.java
  integration/test-integration/src/test/resources/configs/controlplane-enabled-config.toml
Labels: Type/Bug

#2492 [Bug-Fix] [Certs] Remove additional newline characters added to the PEM files (Enforcer) and process
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/TLSUtils.java
  enforcer-parent/enforcer/src/test/java/org/wso2/choreo/connect/enforcer/util/TLSUtilsTest.java
  enforcer-parent/enforcer/src/test/resources/certs/certWithAdditionalNewLine.pem
  enforcer-parent/enforcer/src/test/resources/certs/certWithTwoCerts.pem
  enforcer-parent/enforcer/src/test/resources/certs/truststoreSeparate/mg.pem
  enforcer-parent/enforcer/src/test/resources/certs/truststoreSeparate/wso2carbon.pem
  enforcer-parent/enforcer/src/test/resources/certs/truststoreSingle/certWithAdditionalNewLine.pem
Labels: Type/Bug

#2495 Fix apictl jwt disabling
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/resource.go
  adapter/internal/oasparser/model/swagger.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  integration/test-integration/src/test/resources/openAPIs/cors_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/deploy_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/global_cors_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/mtls_from_router_to_backend_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/security_openAPI.yaml
Labels: Type/Bug

#2499 Adding Istio Samples
  resources/k8s-artifacts/apim/apim-deployment.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-ingress-tls-secret.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
  samples/istio/README.md
  samples/istio/microservice/gw_vs_http.yaml
  samples/istio/microservice/gw_vs_https.yaml
  samples/istio/microservice/httpbin.yaml
  samples/istio/mtls-mode/README.md
  samples/istio/mtls-mode/create-certs.sh
  samples/istio/mtls-mode/gw_vs.yaml
  samples/istio/mtls-mode/mtls.jpg
  samples/istio/mtls-mode/openAPI.yaml
  samples/istio/sidecar-mode/README.md
  samples/istio/sidecar-mode/gw_vs.yaml
  samples/istio/sidecar-mode/openAPI.yaml
  samples/istio/sidecar-mode/sidecar.jpg
Labels: Type/Task

#2494 [Bug-fix] Prioritize Swagger definition's vendor extensions over API.yaml for all APIs.
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/swagger.go
  adapter/internal/oasparser/model/swagger_test.go
  adapter/internal/oasparser/model/types.go
  adapter/internal/oasparser/operator/operator.go
  adapter/internal/oasparser/operator/operator_test.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/PrototypedAPITestCase.java
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Type/Bug

#2504 Build adapter arm64 binary and update Dockerfiles
  adapter/scripts/build.sh
  adapter/src/main/assembly/assembly.xml
  adapter/src/main/resources/Dockerfile
  adapter/src/main/resources/Dockerfile.ubuntu
  build-ubuntu-multi-platform-images.sh
  enforcer-parent/enforcer/src/main/resources/Dockerfile
  enforcer-parent/enforcer/src/main/resources/Dockerfile.ubuntu
  router/src/main/resources/Dockerfile
  router/src/main/resources/Dockerfile.ubuntu
Labels: Type/Task, Docs/Has Impact

#2501 Fix apim security
  adapter/internal/discovery/xds/server.go
  adapter/internal/notifier/deployment_notifier.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/model/api_operation.go
  adapter/internal/oasparser/model/constants.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/mgw_swagger_internal_test.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/open_api_internal_test.go
  adapter/internal/oasparser/model/resource.go
  adapter/internal/oasparser/model/resource_test.go
  adapter/internal/oasparser/model/swagger.go
  adapter/internal/oasparser/model/swagger_internal_test.go
  adapter/internal/synchronizer/apis_fetcher.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/TLSUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/security/APIKeyTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/APIKeyHeaderTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/APIKeyQueryParamTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/APIKeyTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/InternalKeyHeaderTestCase.java
  integration/test-integration/src/test/resources/configs/cc-special-scenarios-with-apim.toml
  integration/test-integration/src/test/resources/openAPIs/api_key_swagger_security_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/app_level_security_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Type/Bug

#2507 Fixing envs for credentials
  adapter/internal/oasparser/model/api_env.go
Labels: Type/Bug

#2502 [bug-fix] Resource level disable security fix and test case for disabled security
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/swagger.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/extensions/DisableSecurityTestCase.java
  integration/test-integration/src/test/resources/openAPIs/disable_security_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
Labels: Type/Bug

#2513 Bug fix: APIList is not updated after the startup
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/eventhub/subscription.go
Labels: Type/Bug

#2506 Read securityconfig from extension
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/model/api_env.go
  adapter/internal/oasparser/model/constants.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/types.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendSandbox.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/circuitBreakers/CircuitBreakersTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/endpoints/BackendSecurityTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BackendSecurityTestCase.java
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  integration/test-integration/src/test/resources/openAPIs/backend_security_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
Labels: Type/Improvement

#2518 Add advance endpoint timeout config support to GRPC
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/protobuf/ExtensionHolder.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/protobuf/ProtobufParser.java
  distribution/resources/grpc/wso2_options.proto
Labels: ballerina-mgw

#2519 bug fix: Websocket APIs cannot be invoked due to null pointer exception
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
Labels: Type/Bug

#2517 Remove unwanted files from enforcer
  enforcer-parent/enforcer/src/main/assembly/assembly.xml
  enforcer-parent/enforcer/src/main/resources/Dockerfile
  enforcer-parent/enforcer/src/main/resources/Dockerfile.ubuntu
Labels: Type/Task, Priority/Normal

#2508 Bug fix: path parameters are not solved for the pattern /pet/{petID}/image/*
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/ParameterResolver.java
  enforcer-parent/commons/src/test/java/org/wso2/choreo/connect/enforcer/commons/model/RequestContextTest.java
Labels: Type/Bug

#2515 Add License files for CC 1.0.0 & Remove unwanted CPP source files
  adapter/LICENSE.txt
  adapter/src/main/assembly/assembly.xml
  distribution/src/main/assembly/assembly.xml
  enforcer-parent/enforcer/src/main/assembly/assembly.xml
  envoy-filters/mgw-api/extensions/filters/http/mgw/v3/BUILD
  envoy-filters/mgw-api/extensions/filters/http/mgw/v3/mgw.proto
  envoy-filters/mgw-source/filters/http/mgw/BUILD
  envoy-filters/mgw-source/filters/http/mgw/config.cc
  envoy-filters/mgw-source/filters/http/mgw/config.h
  envoy-filters/mgw-source/filters/http/mgw/mgw.cc
  envoy-filters/mgw-source/filters/http/mgw/mgw.h
  resources/license/LICENSE-ADAPTER.txt
  resources/license/LICENSE-ENFORCER.txt
  resources/license/LICENSE-ROUTER.txt
  router/src/main/assembly/assembly.xml
  router/src/main/resources/interceptor/lib/base64.lua
Labels: Type/Task

#2516 improvement: allow throttling data publishing via SSL connection
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/databridge/agent/DataPublisher.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/databridge/agent/endpoint/DataEndpointGroup.java
Labels: Type/Improvement

#2526 Send the same validateInfo used in authContext to jwt generator
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
Labels: Type/Task

#2524 Bug fix: Use API-ID instead of APIUUID for throttle data publishing
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/AuthenticationContext.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoAnalyticsProvider.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/MetadataConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/dto/APIKeyValidationInfoDTO.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/WebSocketHandler.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleDataHolder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/MetadataConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketMetaDataFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketThrottleFilter.java
Labels: Type/Task

#2523 Deploy to default env when env not specified
  adapter/internal/api/apis_impl.go
Labels: Type/Bug, Priority/High

#2530 Update enforcer license file
  .trivyignore
  resources/license/LICENSE-ENFORCER.txt
  router/src/main/resources/Dockerfile
  router/src/main/resources/Dockerfile.ubuntu
Labels: Type/Task

#2532 Updating Istio sample readme
  samples/istio/sidecar-mode/README.md
Labels: Type/Task

#2536 Set MVN_PROJECT_VERSION as second param for ubuntu image build
  build-ubuntu-multi-platform-images.sh
Labels: Type/Task

#2535 Fix api level scope validation
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/APIFactory.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/JwtTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/ScopeTest.java
  integration/test-integration/src/test/resources/openAPIs/scopes_openAPI.yaml
Labels: Type/Bug

#2538 Fix path param population error in Websocket APIs
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/RequestContext.java
Labels: Type/Bug, Priority/High

#2549 Ubuntu image build - Add QEMU user mode emulation binaries for ARM64 image build in AMD64
  build-ubuntu-multi-platform-images.sh
Labels: Type/Task

#2548 int-tests: Test apim mode undeploy, new resource, and delete resource
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/ApimResourceProcessor.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/PublisherUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BasicEventsTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
Labels: Type/Task

#2539 Add scope integration tests
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/ScopeTest.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/jwtValidator/JwtAndScopeTestCase.java
  integration/test-integration/src/test/resources/openAPIs/scopes_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Type/Task, test-improvements

#2550 [3.2.x] Upgrade ballerina version to 1.2.22
  pom.xml
Labels: ballerina-mgw

#2541 Backend JWT generation tests for API key
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/security/APIKeyTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/apikey/APIKeyTestCase.java
  integration/test-integration/src/test/resources/configs/cors-disabled-config.toml
  integration/test-integration/src/test/resources/openAPIs/api_key_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/api_key_swagger_security_openAPI.yaml
Labels: Type/Task

#2545 Fix consul
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api.go
Labels: Type/Bug

#2543 Fix sandbox only API
  adapter/internal/oasparser/model/mgw_swagger.go
  integration/test-integration/src/test/resources/openAPIs/sand_openAPI.yaml
Labels: Type/Bug

#2552 Setting resource specific basepath
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendSandbox.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/endpoints/ProductionSandboxTestCase.java
  integration/test-integration/src/test/resources/openAPIs/prod_and_sand_openAPI.yaml
Labels: Type/Improvement

#2554 Bug fix: API-Key subscription throttling does not work
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/AuthenticatorUtils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
Labels: Type/Bug

#2559 Swagger servers should set only as production endpoints
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/swagger.go
Labels: Type/Bug

#2556 [Bug-Fix] Unlimited API Level Tier is not applied after resource level tier applied for once
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/APIConfig.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketMetaDataFilter.java
Labels: Type/Bug

#2560 Add swagger test case
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/QSGAndSwaggerTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/QSGTestCase.java
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
Labels: Type/Task, test-improvements

#2564 Fix issue setting body from interceptor when body is empty from client or backend
  router/src/main/resources/interceptor/lib/interceptor.lua
  router/src/main/resources/interceptor/lib/utils.lua
Labels: Type/Bug

#2575 Avoid adding API when its basepath is already used for a different API
  adapter/internal/api/restserver/config_restapi.go
  adapter/internal/discovery/xds/server.go
Labels: Type/Bug

#2563 [Bug-Fix] Avoid Unwanted headers/query parameters being forwarded to the backend
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/RequestContext.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/ResponseObject.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
Labels: Type/Bug

#2577 [Bug-Fix] userId based deny policies not working
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
Labels: Type/Bug

#2562 Prepare for 1.0.0-rc2 release
  release-note.html
Labels: Type/Task

#2580 Update dependency versions of LICENSE-ENFORCER.txt
  release-note.html
  resources/license/LICENSE-ENFORCER.txt
Labels: Type/Task

#2557 Sample yaml files in main branch
  samples/openAPI-definitions/cors_sample.yaml
  samples/openAPI-definitions/endpoint_by_reference_sample.yaml
  samples/openAPI-definitions/interceptors_sample.yaml
  samples/openAPI-definitions/petstore_basic.yaml
  samples/openAPI-definitions/policies_sample.yaml
  samples/openAPI-definitions/security_sample.yaml
Labels: Type/Task

#2581 Fix Integration test failure in Qsgtestcase due to basepath conflict
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithMultipleEnv.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/QSGAndSwaggerTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/filter/CustomFilterTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtGenerator/CustomJwtTransformerTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtGenerator/JwtGeneratorTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtGenerator/JwtTransformerTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/InternalKeyTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/JwtTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/ScopeTest.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/mtls/MtlsFromRouterToBackendTestcase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/security/CorsTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TokenUtil.java
  integration/test-integration/src/test/resources/openAPIs/mtls_from_router_to_backend_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/openAPI.yaml
Labels: Type/Task, test-improvements

#2503 API Un-deploy event notify to control plane
  adapter/internal/discovery/xds/server.go
  adapter/internal/ga/api_event_listener.go
  adapter/internal/ga/client.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/notifier/deployment_notifier.go
  adapter/internal/notifier/types.go
Labels: Type/Bug, Choreo

#2586 Set next development iteration as 1.1.0-m1-SNAPSHOT
  adapter/pom.xml
  distribution/pom.xml
  enforcer-parent/commons/pom.xml
  enforcer-parent/enforcer/pom.xml
  enforcer-parent/pom.xml
  integration/mock-backend-server/pom.xml
  integration/pom.xml
  integration/test-integration/pom.xml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  pom.xml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  router/pom.xml
Labels: Type/Task

#2591 Refactor group ID for choreo-connect artifacts
  adapter/pom.xml
  distribution/pom.xml
  enforcer-parent/commons/pom.xml
  enforcer-parent/enforcer/pom.xml
  enforcer-parent/pom.xml
  integration/mock-backend-server/pom.xml
  integration/pom.xml
  integration/test-integration/pom.xml
  pom.xml
  router/pom.xml
  samples/filters/sample-filter/pom.xml
Labels: Type/Task

#2592 Upgrade log4j version
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  pom.xml
Labels: ballerina-mgw

#2544 Fixing a goroutine creation for handling API events from GA .
  adapter/internal/ga/client.go
Labels: Type/Bug, Choreo
