Repository wso2/product-microgateway, pull requests merged in 2021-03, with the labels that each got.

#1666 Add external key manager support
  adapter/internal/discovery/api/wso2/discovery/keymgt/key_manager_config.pb.go
  adapter/internal/discovery/protocol/cache/types/types.go
  adapter/internal/discovery/protocol/cache/v3/resource.go
  adapter/internal/discovery/protocol/cache/v3/snapshot.go
  adapter/internal/discovery/protocol/resource/v3/resource.go
  adapter/internal/discovery/protocol/server/sotw/v3/server.go
  adapter/internal/discovery/protocol/server/v3/server.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/eventhub/types/types.go
  adapter/internal/messaging/event_types.go
  adapter/internal/messaging/km_listener.go
  adapter/internal/mgw/mgw.go
  adapter/internal/synchronizer/keymanagers_fetcher.go
  api/wso2/discovery/keymgt/key_manager_config.proto
  enforcer/src/main/gen/org/wso2/gateway/discovery/keymgt/KeyManagerConfig.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/keymgt/KeyManagerConfigOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/keymgt/KeyManagerConfigProto.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/service/km/KMDiscoveryService.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/service/km/KMDiscoveryServiceGrpc.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/service/km/KmdsProto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/APIConstants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/Constants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/KeyManagerDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/keymgt/KeyManagerHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/validator/JWTValidator.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/server/AuthServer.java
Labels: Type/New Feature, envoy-gw

#1676 Enable code coverage for golang unit tests
  adapter/scripts/build.sh
Labels: Type/Task

#1679 Fix tests issues due to the absence of ryuk image
  pom.xml
  test/test-integration/pom.xml
Labels: Type/Task, envoy-gw

#1669 Fix #1668 - Resolve configs from environment variables
  adapter/config/parser.go
  enforcer/src/main/assembly/assembly.xml
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/Constants.java
  resources/conf/config.toml
  resources/docker-compose.yaml
Labels: Type/Improvement

#1687 Token Revocation Support for MG
  adapter/internal/discovery/api/wso2/discovery/keymgt/revoked_tokens.pb.go
  adapter/internal/discovery/api/wso2/discovery/service/keymgt/rtds.pb.go
  adapter/internal/discovery/api/wso2/discovery/service/keymgt/rtds_grpc.pb.go
  adapter/internal/discovery/protocol/cache/types/types.go
  adapter/internal/discovery/protocol/cache/v3/resource.go
  adapter/internal/discovery/protocol/cache/v3/snapshot.go
  adapter/internal/discovery/protocol/resource/v3/resource.go
  adapter/internal/discovery/protocol/server/sotw/v3/server.go
  adapter/internal/discovery/protocol/server/v3/server.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/messaging/revoked_token_listener.go
  adapter/internal/mgw/mgw.go
  adapter/internal/synchronizer/revoked_tokens_fetcher.go
  adapter/internal/synchronizer/types.go
  api/wso2/discovery/keymgt/revoked_tokens.proto
  api/wso2/discovery/service/keymgt/rtds.proto
  enforcer/src/main/gen/org/wso2/gateway/discovery/keymgt/RevokedToken.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/keymgt/RevokedTokenOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/keymgt/RevokedTokensProto.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/service/keymgt/RevokedTokenDiscoveryService.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/service/keymgt/RevokedTokenDiscoveryServiceGrpc.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/service/keymgt/RtdsProto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/Constants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApplicationDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/RevokedTokenDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/validator/RevokedJWTDataHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/server/AuthServer.java
Labels: Type/New Feature

#1693 Add docker resources to run APIM with MGW
  distribution/src/main/assembly/assembly.xml
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/keymgt/KeyManagerHolder.java
  resources/apim/conf/deployment.toml
  resources/apim/docker-compose.yaml
  resources/conf/config.toml
Labels: Type/Task, envoy-gw

#1694 Update K8s configs for MG 4.0.0-m7
  resources/k8s-artifacts/mg-adapter/config-toml-configmap.yaml
  resources/k8s-artifacts/mg-adapter/deployment.yaml
  resources/k8s-artifacts/mg-enforcer/deployment.yaml
  resources/k8s-artifacts/mg-router/deployment.yaml
Labels: Type/Task, envoy-gw

#1410 Resolve commented typos and formatting issues.
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
  components/micro-gateway-cli/src/main/resources/templates/http2.mustache
  components/micro-gateway-cli/src/main/resources/templates/http2settings.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/service.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/grpc_filter.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/basic_auth_handler.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
  components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/GetConfig.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/Constants.java
  tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
  tests/src/test/resources/protobuf/mgwProto/basicProto.proto
Labels: Priority/Normal, Type/Task

#1697 Implement a token endpoint for the REST API
  README.md
  adapter/config/types.go
  adapter/go.mod
  adapter/go.sum
  adapter/internal/api/apis_impl.go
  adapter/internal/api/models/api_meta_list_item.go
  adapter/internal/api/models/credentials.go
  adapter/internal/api/models/principal.go
  adapter/internal/api/restserver/config_restapi.go
  adapter/internal/api/restserver/embedded_spec.go
  adapter/internal/api/restserver/operations/api_collection/get_apis_parameters.go
  adapter/internal/api/restserver/operations/api_collection/get_apis_responses.go
  adapter/internal/api/restserver/operations/api_individual/delete_apis_parameters.go
  adapter/internal/api/restserver/operations/api_individual/delete_apis_responses.go
  adapter/internal/api/restserver/operations/api_individual/post_apis_responses.go
  adapter/internal/api/restserver/operations/authorization/post_oauth2_token.go
  adapter/internal/api/restserver/operations/authorization/post_oauth2_token_parameters.go
  adapter/internal/api/restserver/operations/authorization/post_oauth2_token_responses.go
  adapter/internal/api/restserver/operations/authorization/post_oauth2_token_urlbuilder.go
  adapter/internal/api/restserver/operations/restapi_api.go
  adapter/internal/auth/auth.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/mgw/mgw.go
  adapter/resources/adapterAPI.yaml
  adapter/restAPIGenGuide.md
  resources/conf/config.toml
Labels: Type/New Feature

#1700 M8 development iteration preparation.
  adapter/pom.xml
  distribution/pom.xml
  enforcer/pom.xml
  pom.xml
  remove-containers.sh
  resources/apim/docker-compose.yaml
  resources/docker-compose.yaml
  resources/k8s-artifacts/mg-adapter/deployment.yaml
  resources/k8s-artifacts/mg-enforcer/deployment.yaml
  resources/k8s-artifacts/mg-router/deployment.yaml
  router/pom.xml
  test/mock-backend-server/pom.xml
  test/pom.xml
  test/test-integration/pom.xml
Labels: Priority/Normal, Type/Task

#1707 Fixing subscription validation issue
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/keymgt/KeyManagerHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/validator/JWTValidator.java
Labels: Type/Bug

#1675 Add test JWT token generation support to MGW
  adapter/config/types.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/am_credentials.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/auth_service.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/binary_throttling.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/cache.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/cert.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/config.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/event_hub.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/issuer.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/jms_connection_params.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/jwt_generator.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/jwt_issuer.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/jwt_user.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/thread_pool.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/throttle_agent.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/throttle_publisher.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/throttling.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/tm_url_group.pb.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/mgw/mgw.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  api/wso2/discovery/config/enforcer/config.proto
  api/wso2/discovery/config/enforcer/jwt_issuer.proto
  api/wso2/discovery/config/enforcer/jwt_user.proto
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/Config.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/ConfigOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/ConfigProto.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/JWTIssuer.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/JWTIssuerOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/JWTIssuerProto.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/JWTUser.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/JWTUserOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/JWTUserProto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/EnforcerConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/dto/JWTIssuerConfigurationDto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/JWTAuthenticator.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/JWTUtil.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/issuer/AbstractJWTIssuer.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/issuer/HttpTokenServerHandler.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/issuer/HttpTokenServerInitializer.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/issuer/JWTIssuerImpl.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/issuer/TokenIssuer.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/issuer/URLSafeJWTIssuer.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/server/AuthServer.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/server/TokenServer.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/util/TLSUtils.java
  resources/conf/config.toml
  resources/docker-compose.yaml
  router/src/main/resources/Dockerfile
Labels: Type/New Feature

#1718 Fix TokenServer initializing issue
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/server/AuthServer.java
Labels: Type/Bug

#1726 M8 release preperation.
  adapter/pom.xml
  distribution/pom.xml
  enforcer/pom.xml
  pom.xml
  router/pom.xml
  test/mock-backend-server/pom.xml
  test/pom.xml
  test/test-integration/pom.xml
Labels: Priority/High, Type/Task, envoy-gw

#1737 Development prep for next release.
  remove-containers.sh
  resources/apim/docker-compose.yaml
  resources/docker-compose.yaml
  resources/k8s-artifacts/mg-adapter/deployment.yaml
  resources/k8s-artifacts/mg-enforcer/deployment.yaml
  resources/k8s-artifacts/mg-router/deployment.yaml
Labels: Priority/High, Type/Task, envoy-gw

#1721 Improve config xds retry
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/EnvVarConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/Constants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/Backoff.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ConfigDiscoveryClient.java
  enforcer/src/main/resources/Dockerfile
  resources/apim/docker-compose.yaml
  resources/docker-compose.yaml
  resources/k8s-artifacts/mg-enforcer/deployment.yaml
Labels: Priority/High, envoy-gw, test-improvements

#1608 fix line space and document methods
  components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/callhome/Callhome.java
Labels: Type/Task

#1739 Adding k8s artifacts
  resources/k8s-artifacts/apim/apim-config.yaml
  resources/k8s-artifacts/apim/apim-deployment.yaml
  resources/k8s-artifacts/apim/apim-service.yaml
  resources/k8s-artifacts/mg-adapter/config-toml-configmap.yaml
  resources/k8s-artifacts/mg-enforcer/deployment.yaml
Labels: Type/Task

#1744 Upgrading carbon.apimgt version to 9.0.70
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/JWTAuthenticator.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/util/FilterUtils.java
  pom.xml
Labels: Type/Improvement

#1747 Microgateway APIM Internal-Key Support
  adapter/config/types.go
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/api/wso2/discovery/api/api.pb.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/model/mgw_swagger.go
  api/wso2/discovery/api/api.proto
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/Api.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/ApiOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/ApiProto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/RestAPI.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/config/APIConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/common/CacheProvider.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/APIConstants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/dto/JWTTokenPayloadInfo.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/AuthFilter.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/AuthenticationResponse.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/Authenticator.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/JWTAuthenticator.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/oauth/OAuthAuthenticator.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/util/FilterUtils.java
  resources/conf/config.toml
Labels: Type/New Feature, envoy-gw

#1730 Add Conditional Throttling
  adapter/go.sum
  adapter/internal/discovery/api/wso2/discovery/api/Endpoint.pb.go
  adapter/internal/discovery/api/wso2/discovery/api/Resource.pb.go
  adapter/internal/discovery/api/wso2/discovery/api/api.pb.go
  adapter/internal/discovery/api/wso2/discovery/service/api/apids.pb.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/model/api_operation.go
  adapter/internal/oasparser/model/constants.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/open_api_internal_test.go
  adapter/internal/oasparser/model/swagger.go
  adapter/internal/oasparser/model/swagger_internal_test.go
  api/wso2/discovery/api/Resource.proto
  api/wso2/discovery/api/api.proto
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/Api.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/ApiOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/ApiProto.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/Operation.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/OperationOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/Resource.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/ResourceOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/ResourceProto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/RequestContext.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/RestAPI.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/config/APIConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/EnvVarConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ConfigDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/JWTUtil.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleConstants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleDataHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleEventListener.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleFilter.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleUtils.java
  integration/test-integration/src/test/resources/jwtGenerator/config.toml
  resources/conf/config.toml
Labels: Priority/Normal, Type/New Feature, envoy-gw

#1754 Add Retry-After header to throttle response
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/RequestContext.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/RestAPI.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/grpc/ExtAuthService.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleConstants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleDataHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleFilter.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleUtils.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/dto/Decision.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/util/FilterUtils.java
  integration/test-integration/src/test/resources/jwtGenerator/config.toml
Labels: Priority/High, Type/Improvement, envoy-gw

#1760 Fix jwt encoding issue
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/issuer/AbstractJWTIssuer.java
Labels: Type/Improvement

#1731 Adding unit tests for adapter
  adapter/go.mod
  adapter/go.sum
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/listener_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/internal/oasparser/model/mgw_swagger_internal_test.go
  adapter/internal/oasparser/model/open_api_internal_test.go
  adapter/internal/oasparser/model/swagger_test.go
  adapter/internal/oasparser/operator/operator_test.go
  adapter/test-resources/envoycodegen/openapi_with_xwso2label.yaml
Labels: Type/Task

#1757 Add Integration tests for Subscription Validation
  integration/test-integration/pom.xml
  integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/apim/APIMLifecycleBaseTest.java
  integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/apim/APIMWithMgwBaseTest.java
  integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/context/APIManagerWithMgwServerInstance.java
  integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/context/MgwServerImpl.java
  integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/context/MgwServerInstance.java
  integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/mockbackend/MockBackendServer.java
  integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/testCaseBefore/APIManagerInitializeTestCase.java
  integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/testCases/subscription/SubscriptionValidationTestCase.java
  integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/TestConstant.java
  integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/Utils.java
  integration/test-integration/src/test/resources/apim/config.toml
  integration/test-integration/src/test/resources/automation.xml
  integration/test-integration/src/test/resources/testng.xml
  resources/apim/docker-compose.yaml
  resources/docker-compose.yaml
Labels: Type/Task

#1768 Resolve throttle publisher pwd from env vars
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/dto/ThrottleAgentConfigDto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/dto/ThrottlePublisherConfigDto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/databridge/publisher/ThrottleDataPublisher.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/databridge/publisher/ThrottleDataPublisherPool.java
Labels: Priority/Normal, Type/Bug, envoy-gw

#1761 Fix subscription validation when multiple issuers are provided
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
Labels: Priority/Normal, Type/Bug

#1778 Advance jms connection support for Enforcer
  adapter/config/types.go
  enforcer/pom.xml
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/dto/ThrottleConfigDto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/Constants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/server/AuthServer.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleEventListener.java
  pom.xml
  resources/apim/docker-compose.yaml
  resources/conf/config.toml
  resources/docker-compose.yaml
Labels: Priority/Normal, Type/Improvement, envoy-gw

#1745 Add support for Consul service mesh
  adapter/config/types.go
  adapter/internal/discovery/xds/consul.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/svcdiscovery/client.go
  adapter/internal/svcdiscovery/watcher.go
  resources/conf/config.toml
Labels: Type/New Feature, envoy-gw

#1748 Add support for denying/blocking throttle conditions
  adapter/internal/discovery/api/wso2/discovery/throttle/blocking_conditions.pb.go
  adapter/internal/discovery/api/wso2/discovery/throttle/throttle_data.pb.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/mgw/mgw.go
  adapter/internal/synchronizer/throttle_data_fetcher.go
  adapter/internal/synchronizer/types.go
  api/wso2/discovery/throttle/blocking_conditions.proto
  api/wso2/discovery/throttle/throttle_data.proto
  enforcer/src/main/gen/org/wso2/gateway/discovery/throttle/BlockingConditions.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/throttle/BlockingConditionsOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/throttle/BlockingConditionsProto.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/throttle/IPCondition.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/throttle/IPConditionOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/throttle/ThrottleData.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/throttle/ThrottleDataOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/throttle/ThrottleDataProto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ThrottleDataDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleConstants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleDataHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleEventListener.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleFilter.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/dto/IPRange.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/dto/ThrottleCondition.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/utils/ThrottleUtils.java
Labels: Priority/Normal, Type/New Feature, envoy-gw

#1753 Add health check endpoint to Router
  adapter/config/types.go
  adapter/go.mod
  adapter/go.sum
  adapter/internal/discovery/xds/server.go
  adapter/internal/mgw/mgw.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/listener_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  enforcer/pom.xml
  integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/testCaseBefore/MgwWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/TestConstant.java
  integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/Utils.java
  integration/test-integration/src/test/resources/apim/config.toml
  integration/test-integration/src/test/resources/jwtGenerator/config.toml
  resources/apim/docker-compose.yaml
  resources/conf/config.toml
  resources/docker-compose.yaml
Labels: Type/Improvement, envoy-gw

#1784 Non Secured APIs Feature
  adapter/internal/discovery/api/wso2/discovery/api/Endpoint.pb.go
  adapter/internal/discovery/api/wso2/discovery/api/Resource.pb.go
  adapter/internal/discovery/api/wso2/discovery/api/api.pb.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/model/api_operation.go
  adapter/internal/oasparser/model/constants.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/open_api_internal_test.go
  adapter/internal/oasparser/model/swagger.go
  adapter/internal/oasparser/model/swagger_internal_test.go
  api/wso2/discovery/api/Resource.proto
  api/wso2/discovery/api/api.proto
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/Api.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/ApiOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/ApiProto.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/Operation.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/OperationOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/ResourceProto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/RestAPI.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/config/APIConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/config/ResourceConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/APIConstants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/AuthFilter.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/UnsecuredAPIAuthenticator.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/util/FilterUtils.java
Labels: Type/New Feature

#1785 Adding basic auth endpoint security and remove auth header feature based on config
  adapter/config/parser.go
  adapter/config/types.go
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/api/wso2/discovery/api/api.pb.go
  adapter/internal/discovery/api/wso2/discovery/api/endpoint_security.pb.go
  adapter/internal/discovery/api/wso2/discovery/api/security_info.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/config.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/security.pb.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/envoyconf/internal_dtos.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/model/constants.go
  adapter/internal/oasparser/model/mgw_swagger.go
  api/wso2/discovery/api/api.proto
  api/wso2/discovery/api/endpoint_security.proto
  api/wso2/discovery/api/security_info.proto
  api/wso2/discovery/config/enforcer/config.proto
  api/wso2/discovery/config/enforcer/security.proto
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/Api.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/ApiOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/ApiProto.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/EndpointSecurity.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/EndpointSecurityOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/EndpointSecurityProto.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/SecurityInfo.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/SecurityInfoOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/api/SecurityInfoProto.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/Config.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/ConfigOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/ConfigProto.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/Security.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/SecurityOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/SecurityProto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/RestAPI.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/config/APIConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/EnforcerConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/exception/APISecurityException.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/JWTAuthenticator.java
  integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/testCases/jwtValidator/JwtTestCase.java
  integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/testCases/subscription/SubscriptionValidationTestCase.java
  integration/test-integration/src/test/resources/apim/config.toml
  integration/test-integration/src/test/resources/jwtGenerator/config.toml
  resources/conf/config.toml
Labels: Type/New Feature, envoy-gw

#1791 Fix #1790 - Enforcer env varaible resolving issue
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
  resources/apim/docker-compose.yaml
  resources/conf/config.toml
Labels: Type/Bug, envoy-gw
