Repository wso2/product-microgateway, pull requests merged in 2021-01, with the labels that each got.

#1501 Adding kubernetes artifacts related to Envoy microgateway
  k8s-artifacts/K8S-README.md
  k8s-artifacts/mg-adapter/adapter-key-secret.yaml
  k8s-artifacts/mg-adapter/adapter-pem-secret.yaml
  k8s-artifacts/mg-adapter/config-toml-configmap.yaml
  k8s-artifacts/mg-adapter/deployment.yaml
  k8s-artifacts/mg-adapter/log4j2-configmap.yaml
  k8s-artifacts/mg-adapter/logconfig-toml-configmap.yaml
  k8s-artifacts/mg-adapter/service.yaml
  k8s-artifacts/mg-enforcer/client-truststore-secret.yaml
  k8s-artifacts/mg-enforcer/deployment.yaml
  k8s-artifacts/mg-enforcer/service.yaml
  k8s-artifacts/mg-router/deployment.yaml
  k8s-artifacts/mg-router/envoy-configmap.yaml
  k8s-artifacts/mg-router/service.yaml
Labels: envoy-gw

#1530 Upgrade ballerina to 1.2.12, add config for reponse header limits cha…
  components/micro-gateway-cli/src/main/resources/templates/failoverEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/failoverEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/failoverResourceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/http1Settings.mustache
  components/micro-gateway-cli/src/main/resources/templates/httpEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/httpEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/httpResourceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbEndpointReInit.mustache
  components/micro-gateway-cli/src/main/resources/templates/lbResourceEndpoint.mustache
  components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
  components/micro-gateway-cli/src/main/resources/templates/requestLimits.mustache
  components/micro-gateway-cli/src/main/resources/templates/responseLimits.mustache
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
  distribution/resources/conf/default-micro-gw.conf.template
  pom.xml
Labels: Type/Bug

#1536 Fix jenkins golint command not found
  adapter/build.sh
  adapter/go.mod
  adapter/go.sum
Labels: Type/Task, envoy-gw

#1537 Fix #1446 - Configure the grpc server for the external authz
  enforcer/pom.xml
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/common/ReferenceHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/EnforcerConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/dto/AuthServiceConfigurationDto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/dto/CredentialDto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/dto/EventHubConfigurationDto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/dto/JWKSConfigurationDTO.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/dto/TokenIssuerDto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/ConfigConstants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/dto/EventHubConfigurationDto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/grpc/ExtAuthService.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/grpc/server/AuthServer.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/listener/GatewayJMSMessageListener.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/DefaultJWTTransformer.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/JWTAuthenticator.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/JWTTransformer.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/validator/JWTValidator.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/server/AuthServer.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/server/Constants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/server/EnforcerThreadPoolExecutor.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/server/EnforcerWorkerPool.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/server/NativeThreadFactory.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/server/RequestHandler.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/subscription/SubscriptionDataLoaderImpl.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/subscription/SubscriptionDataStoreImpl.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/util/FilterUtils.java
  enforcer/src/main/resources/Dockerfile
  resources/conf/config.toml
  test/mock-backend-server/src/main/java/org.wso2am.micro.gw.mockbackend/Constants.java
  test/mock-backend-server/src/main/resources/Dockerfile
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/TestConstant.java
  test/test-integration/src/test/resources/apis/openApis/mockApi.yaml
  test/test-integration/src/test/resources/backend-service-tls.yaml
  test/test-integration/src/test/resources/backend-service.yaml
  test/test-integration/src/test/resources/backendtls/openapi.yaml
  test/test-integration/src/test/resources/prod-sand/prodOpenAPI.yaml
  test/test-integration/src/test/resources/prod-sand/prodSandOpenAPI.yaml
Labels: Type/New Feature

#1546 Fix #1545 - Evenhub config reading error
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/dto/EventHubConfigurationDto.java
Labels: Type/Bug, envoy-gw

#1543 Update K8s configs for MGW 4.0.0-m3
  distribution/src/main/assembly/assembly.xml
  k8s-artifacts/mg-adapter/adapter-pem-secret.yaml
  resources/k8s-artifacts/K8S-README.md
  resources/k8s-artifacts/mg-adapter/adapter-tls-secret.yaml
  resources/k8s-artifacts/mg-adapter/config-toml-configmap.yaml
  resources/k8s-artifacts/mg-adapter/deployment.yaml
  resources/k8s-artifacts/mg-adapter/log4j2-configmap.yaml
  resources/k8s-artifacts/mg-adapter/logconfig-toml-configmap.yaml
  resources/k8s-artifacts/mg-adapter/service.yaml
  resources/k8s-artifacts/mg-enforcer/client-truststore-secret.yaml
  resources/k8s-artifacts/mg-enforcer/deployment.yaml
  resources/k8s-artifacts/mg-enforcer/service.yaml
  resources/k8s-artifacts/mg-router/deployment.yaml
  resources/k8s-artifacts/mg-router/envoy-configmap.yaml
  resources/k8s-artifacts/mg-router/router-tls-secret.yaml
  resources/k8s-artifacts/mg-router/service.yaml
Labels: Type/Improvement, envoy-gw

#1541 Feature/web socket
  adapter/go.mod
  adapter/go.sum
  adapter/pkg/api/file_read_utils.go
  adapter/pkg/oasparser/configGenerator.go
  adapter/pkg/oasparser/envoyconf/constants.go
  adapter/pkg/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/pkg/oasparser/envoyconf/httpFilters.go
  adapter/pkg/oasparser/envoyconf/listener.go
  adapter/pkg/oasparser/envoyconf/routesWithClusters.go
  adapter/pkg/oasparser/envoyconf/routesWithClusters_test.go
  adapter/pkg/oasparser/model/constants.go
  adapter/pkg/oasparser/model/mgwSwagger.go
  adapter/pkg/oasparser/model/openApi.go
  adapter/pkg/oasparser/model/openApi_internal_test.go
  adapter/pkg/oasparser/model/swagger.go
  adapter/pkg/oasparser/model/swagger_internal_test.go
  adapter/pkg/oasparser/operator/operator.go
  adapter/pkg/oasparser/operator/operator_test.go
  adapter/pkg/xds/xds_server.go
  adapter/test-resources/envoycodegen/api.yaml
  adapter/test-resources/envoycodegen/api_prod.yaml
  adapter/test-resources/envoycodegen/api_sand.yaml
Labels: Type/New Feature, envoy-gw

#1549 [k8s artifacts] Update changes for Adapter config.toml
  resources/k8s-artifacts/mg-adapter/config-toml-configmap.yaml
Labels: envoy-gw

#1551 Fix K8s Resources
  resources/k8s-artifacts/mg-adapter/deployment.yaml
  resources/k8s-artifacts/mg-enforcer/deployment.yaml
  resources/k8s-artifacts/mg-router/deployment.yaml
Labels: Type/Bug, envoy-gw

#1552 Prepare for 4.0.0-m3 release
  adapter/pom.xml
  developer-guide.md
  distribution/pom.xml
  enforcer/pom.xml
  pom.xml
  remove-containers.sh
  resources/docker-compose.yaml
  router/pom.xml
  test/mock-backend-server/pom.xml
  test/pom.xml
  test/test-integration/pom.xml
Labels: Priority/Highest, envoy-gw

#1553 Prepare for 4.0.0-m4 dev cycle
  adapter/pom.xml
  developer-guide.md
  distribution/pom.xml
  enforcer/pom.xml
  pom.xml
  remove-containers.sh
  resources/docker-compose.yaml
  router/pom.xml
  test/mock-backend-server/pom.xml
  test/pom.xml
  test/test-integration/pom.xml
Labels: Type/Task, envoy-gw

#1458 Modify implementtion to apply custom throttling policies for unauthenticated api calls
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
Labels: Type/Bug

#1559 Retrieving JMS Events to Control Plane
  adapter/config/mgwtypes.go
  adapter/go.mod
  adapter/loggers/logger.go
  adapter/pkg/messaging/eventtypes.go
  adapter/pkg/messaging/keymanagerListener.go
  adapter/pkg/messaging/mainListener.go
  adapter/pkg/messaging/notificationListener.go
  adapter/pkg/messaging/tokenRevocationListener.go
  adapter/pkg/mgw/mgw.go
  adapter/pkg/resourcetypes/dto.go
  resources/conf/config.toml
Labels: Type/New Feature, Type/Task, envoy-gw

#1563 consul service discovery for envoy gateway
  adapter/config/mgwtypes.go
  adapter/loggers/logger.go
  adapter/pkg/oasparser/envoyconf/routesWithClusters.go
  adapter/pkg/oasparser/model/mgwSwagger.go
  adapter/pkg/svcdiscovery/client.go
  adapter/pkg/svcdiscovery/utils.go
  adapter/pkg/svcdiscovery/utils_test.go
  adapter/pkg/svcdiscovery/watcher.go
  adapter/pkg/xds/xds_server.go
  resources/adapter/security/consul/consul-agent-ca.pem
  resources/adapter/security/consul/local-dc-client-consul-0-key.pem
  resources/adapter/security/consul/local-dc-client-consul-0.pem
  resources/conf/config.toml
Labels: Type/New Feature, envoy-gw

#1560 Support Cross-Origin-Resource-Sharing (CORS)
  adapter/go.mod
  adapter/pkg/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/pkg/oasparser/envoyconf/httpFilters.go
  adapter/pkg/oasparser/envoyconf/internalDTOs.go
  adapter/pkg/oasparser/envoyconf/routesWithClusters.go
  adapter/pkg/oasparser/model/constants.go
  adapter/pkg/oasparser/model/mgwSwagger.go
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/ResponseObject.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/RestAPI.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/config/ResourceConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/HttpConstants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/cors/CorsFilter.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/grpc/ExtAuthService.java
  test/test-integration/pom.xml
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/security/CorsTestCase.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/HttpsClientRequest.java
  test/test-integration/src/test/resources/apis/openApis/mockApi.yaml
  test/test-integration/src/test/resources/cors/mockApi.yaml
  test/test-integration/src/test/resources/testng.xml
Labels: Type/New Feature, envoy-gw

#1573 fix the issue where containers are not shutting down after CORS testcase
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/security/CorsTestCase.java
Labels: Type/Task, envoy-gw

#1574 Update K8s configs for MG 4.0.0-m4
  resources/k8s-artifacts/mg-adapter/adapter-tls-secret.yaml
  resources/k8s-artifacts/mg-adapter/config-toml-configmap.yaml
  resources/k8s-artifacts/mg-adapter/consul-cert-secret.yaml
  resources/k8s-artifacts/mg-adapter/controlplane-secret.yaml
  resources/k8s-artifacts/mg-adapter/deployment.yaml
  resources/k8s-artifacts/mg-adapter/service.yaml
  resources/k8s-artifacts/mg-enforcer/deployment.yaml
  resources/k8s-artifacts/mg-enforcer/service.yaml
  resources/k8s-artifacts/mg-router/deployment.yaml
  resources/k8s-artifacts/mg-router/envoy-configmap.yaml
  resources/k8s-artifacts/mg-router/service.yaml
Labels: Type/Improvement, envoy-gw

#1575 Prepare for 4.0.0-m4 release
  README.md
  developer-guide.md
  remove-containers.sh
  resources/docker-compose.yaml
Labels: Type/Task, envoy-gw

#1576 [Do not merge]Prepare for 4.0.0-m4 release
  adapter/pom.xml
  distribution/pom.xml
  enforcer/pom.xml
  pom.xml
  router/pom.xml
  test/mock-backend-server/pom.xml
  test/pom.xml
  test/test-integration/pom.xml
Labels: Type/Task, envoy-gw

#1578 Prepare for 4.0.0-m5 dev cycle
  adapter/pom.xml
  developer-guide.md
  distribution/pom.xml
  enforcer/pom.xml
  pom.xml
  remove-containers.sh
  resources/docker-compose.yaml
  resources/k8s-artifacts/mg-adapter/deployment.yaml
  resources/k8s-artifacts/mg-enforcer/deployment.yaml
  resources/k8s-artifacts/mg-router/deployment.yaml
  router/pom.xml
  test/mock-backend-server/pom.xml
  test/pom.xml
  test/test-integration/pom.xml
Labels: Type/Task, envoy-gw
