Repository wso2/product-microgateway, pull requests merged in 2021-06, with the labels that each got.

#2042 Introduce tenant domain/ organizationId based entity maps
  adapter/internal/api/apis_impl.go
  adapter/internal/api/restserver/config_restapi.go
  adapter/internal/discovery/xds/consul.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/messaging/notification_listener.go
Labels: Choreo, Type/Improvement

#2047 Add info log for api project zip file read
  adapter/internal/synchronizer/apis_fetcher.go
Labels: Type/Improvement, Type/Task

#2052 Add organization ID to the cluster name
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
Labels: Type/Bug

#2055 Bug Fix: JMS retrying does not work
  adapter/go.mod
  adapter/go.sum
  adapter/internal/messaging/km_listener.go
  adapter/internal/messaging/listener.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/messaging/revoked_token_listener.go
  adapter/internal/messaging/throttle_data_listener.go
  adapter/pkg/messaging/connection.go
  adapter/pkg/messaging/listener.go
Labels: Type/Bug, envoy-gw

#2059 Update the snakeyaml version
  enforcer/pom.xml
  pom.xml
Labels: Type/Bug, envoy-gw

#2060 Merge the feature branch with main
  adapter/go.mod
  adapter/go.sum
  adapter/internal/messaging/km_listener.go
  adapter/internal/messaging/listener.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/messaging/revoked_token_listener.go
  adapter/internal/messaging/throttle_data_listener.go
  adapter/pkg/messaging/connection.go
  adapter/pkg/messaging/listener.go
  enforcer/pom.xml
  pom.xml
Labels: Type/Task

#2036 Simplify the default configuration file
  adapter/config/default_config.go
  adapter/config/parser.go
  adapter/config/types.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/pkg/discovery/api/wso2/discovery/config/enforcer/am_credentials.pb.go
  adapter/pkg/discovery/api/wso2/discovery/config/enforcer/binary_publisher.pb.go
  adapter/pkg/discovery/api/wso2/discovery/config/enforcer/config.pb.go
  adapter/pkg/discovery/api/wso2/discovery/config/enforcer/thread_pool.pb.go
  api/proto/wso2/discovery/config/enforcer/am_credentials.proto
  api/proto/wso2/discovery/config/enforcer/binary_publisher.proto
  api/proto/wso2/discovery/config/enforcer/config.proto
  api/proto/wso2/discovery/config/enforcer/thread_pool.proto
  api/protogen.sh
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/AmCredentials.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/AmCredentialsOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/AmCredentialsProto.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/BinaryPublisher.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/BinaryPublisherOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/BinaryPublisherProto.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/Config.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/ConfigOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/ConfigProto.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/ThreadPool.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/ThreadPoolOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/ThreadPoolProto.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/EnforcerConfig.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  integration/test-integration/src/test/resources/apim/config.toml
  integration/test-integration/src/test/resources/cors/cors-disabled-config.toml
  integration/test-integration/src/test/resources/jwtGenerator/config.toml
  resources/conf/config-for-eventhub.toml
  resources/conf/config.toml
  resources/conf/config.toml.template
Labels: Priority/Normal, Type/Task

#2062 Fix #2061 - Use same UUID to track request in router and enforcer
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/HttpConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/interceptors/AccessLogInterceptor.java
Labels: Type/Bug

#2072 Fix route related issues
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  router/src/main/resources/Dockerfile
Labels: Type/Bug, envoy-gw

#2071 Add timeout configurations
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackEndServer.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/timeouts/TimeOutTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
  integration/test-integration/src/test/resources/openAPIs/timeout_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
  resources/conf/config.toml.template
Labels: Type/Improvement, envoy-gw

#2082 Handle malformed endpoints
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/open_api_internal_test.go
  adapter/internal/oasparser/model/swagger.go
  adapter/internal/oasparser/model/swagger_internal_test.go
  adapter/internal/oasparser/model/swagger_test.go
  adapter/internal/oasparser/operator/operator.go
  adapter/internal/oasparser/operator/operator_test.go
Labels: Choreo, Type/Bug

#2080 int-tests: combine startup pull and via eventhub tests
  integration/test-integration/readme.md
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/withapim/ApimPreparer.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BasicEventsTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/ExistingApiTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Type/Task

#2087 Add connection retry for failover endpoints
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
  adapter/internal/discovery/xds/routercallbacks/router_callbacks.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/eventhub/subscription.go
  adapter/pkg/messaging/connection.go
Labels: Type/Bug, envoy-gw

#2093 Fix #2092 - Improve enforcer logs
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiListDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationKeyMappingDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationPolicyDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/KeyManagerDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/RevokedTokenDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionPolicyDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ThrottleDataDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
Labels: Type/Task

#2099 Syncing branches
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
  adapter/internal/discovery/xds/routercallbacks/router_callbacks.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/eventhub/subscription.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/open_api_internal_test.go
  adapter/internal/oasparser/model/swagger.go
  adapter/internal/oasparser/model/swagger_internal_test.go
  adapter/internal/oasparser/model/swagger_test.go
  adapter/internal/oasparser/operator/operator.go
  adapter/internal/oasparser/operator/operator_test.go
  adapter/pkg/messaging/connection.go
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiListDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationKeyMappingDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationPolicyDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/KeyManagerDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/RevokedTokenDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionPolicyDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ThrottleDataDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackEndServer.java
  integration/test-integration/readme.md
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/withapim/ApimPreparer.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/timeouts/TimeOutTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BasicEventsTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/ExistingApiTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
  integration/test-integration/src/test/resources/openAPIs/timeout_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
  resources/conf/config.toml.template
  router/src/main/resources/Dockerfile
Labels: Type/Task

#2101 Add readiness probe for router
  adapter/internal/adapter/adapter.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/pkg/messaging/connection.go
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Improvement, envoy-gw

#2113 Merging main to feature branch
  adapter/internal/adapter/adapter.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/pkg/messaging/connection.go
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#2112 Bug Fix: APIUUID is not published to Analytics when Internal-Key is used.
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
Labels: Choreo, Type/Bug, mgw-analytics

#2115 Prepare for release 3.1.1
  README.md
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-core/pom.xml
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java
  components/micro-gateway-interceptor/pom.xml
  components/micro-gateway-jwt-generator/pom.xml
  components/micro-gateway-tools/pom.xml
  components/pom.xml
  distribution/LICENSE-RUNTIME.txt
  distribution/pom.xml
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/resources/version.txt
  distribution/src/main/assembly/filter.properties
  pom.xml
  release-notes.html
  tests/pom.xml
Labels: Type/Task

#2120 Fix #2119 Change enforcer base image to jdk based image
  enforcer/src/main/resources/Dockerfile
Labels: Type/Task
