Repository wso2/product-microgateway, pull requests merged in 2021-09, with the labels that each got.

#2218 Add logic to inject data to correct pipeline once consumed from azure service bus
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/adapter/adapter.go
  adapter/internal/messaging/azure_listener.go
  adapter/internal/messaging/listener.go
  adapter/internal/messaging/messaging_test.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/messaging/revoked_token_listener.go
  adapter/pkg/messaging/azure_connection.go
  adapter/pkg/messaging/azure_listener.go
Labels: Type/Task

#2214 Readme file changes for supported versions
  README.md
  developer-guide.md
Labels: Type/Task

#2225 Fix not giving priority to x-wso2 extensions when server url is malformed
  adapter/internal/oasparser/model/open_api.go
Labels: Type/Bug

#2184 Add implementation for the retry mechanism
  adapter/internal/adapter/adapter.go
  adapter/internal/eventhub/subscription.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/pkg/health/controlplane.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/ApimInstance.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/withapim/ApimRestartExecutor.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
  integration/test-integration/src/test/resources/configs/controlplane-enabled-config.toml
  integration/test-integration/src/test/resources/database/WSO2AM_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2CARBON_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2MB_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2METRICS_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2SHARED_DB.mv.db
  integration/test-integration/src/test/resources/dockerCompose/apim-in-common-network-docker-compose.yaml
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Type/Improvement

#2242 Update jars
  pom.xml
Labels: Type/Task

#2241 Update jars
  pom.xml
Labels: Type/Task

#2221 Init lua interceptors
  adapter/config/types.go
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/interceptor/interceptor.go
  adapter/internal/loggers/logger.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/http_filters.go
  adapter/internal/oasparser/envoyconf/internal_dtos.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/internal/oasparser/model/constants.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/resource.go
Labels: Type/New Feature

#2240 Add Jaeger metric exporting
  adapter/config/default_config.go
  enforcer/pom.xml
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigDefaults.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/AzureTraceExporter.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/RateLimitingSampler.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/TracerFactory.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/TracingConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/AzureExporter.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/JaegerExporter.java
  enforcer/src/test/java/org/wso2/choreo/connect/enforcer/tracing/exporters/JaegerExporterTest.java
  pom.xml
  resources/conf/config.toml.template
Labels: Type/New Feature
