Repository wso2/product-microgateway, pull requests merged in 2021-07, with the labels that each got.

#2118 Fix version in ballerinaToml
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
Labels: Type/Task

#2100 Remove redundant log config read operation
  adapter/config/log_types.go
  adapter/config/parser.go
  adapter/internal/adapter/adapter.go
  adapter/internal/discovery/xds/server_utils_test.go
  adapter/internal/oasparser/envoyconf/access_loggers.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/pkg/config/log_types.go
  adapter/pkg/config/parser.go
  adapter/pkg/logging/package_logs.go
  adapter/pkg/logging/root_logs.go
Labels: Type/Task

#2117 Fix #2116 - Improve enforcer side logs to print app, sub counts
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiListDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationKeyMappingDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationPolicyDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/KeyManagerDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionPolicyDiscoveryClient.java
Labels: Type/Improvement

#2108 Global Adapter related Implementation
  adapter/config/default_config.go
  adapter/config/parser.go
  adapter/config/types.go
  adapter/go.mod
  adapter/go.sum
  adapter/internal/adapter/adapter.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/ga/client.go
  adapter/internal/loggers/logger.go
  adapter/pkg/discovery/api/wso2/discovery/ga/api.pb.go
  adapter/pkg/discovery/api/wso2/discovery/service/ga/apids.pb.go
  adapter/pkg/discovery/protocol/cache/types/types.go
  adapter/pkg/discovery/protocol/cache/v3/resource.go
  adapter/pkg/discovery/protocol/cache/v3/snapshot.go
  adapter/pkg/discovery/protocol/resource/v3/resource.go
  adapter/pkg/discovery/protocol/server/sotw/v3/server.go
  adapter/pkg/discovery/protocol/server/v3/server.go
  adapter/scripts/build.sh
  api/proto/wso2/discovery/ga/api.proto
  api/proto/wso2/discovery/service/ga/apids.proto
  api/protogen.sh
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiListDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationKeyMappingDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationPolicyDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/KeyManagerDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionPolicyDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
  enforcer/src/main/resources/Dockerfile
  resources/conf/config.toml.template
Labels: Type/Task

#2124 Bug Fix: if duplicate remove events are received, xds cache gets cleared
  adapter/internal/messaging/messaging_test.go
  adapter/internal/messaging/notification_listener.go
Labels: Type/Bug

#2123 Introduce private AsyncAPIs to MicroGateway.
  adapter/internal/api/apis_impl.go
  adapter/internal/oasparser/model/constants.go
Labels: Type/New Feature

#2128 Bug fix: Event duplication
  adapter/pkg/messaging/connection.go
Labels: Type/Bug

#2131 Add missing checks for AsyncAPI.
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
Labels: Type/New Feature, envoy-gw

#2122 Add unit test case
  adapter/internal/discovery/xds/server_test.go
Labels: Type/Task

#2133 Add missing checks for AsyncAPI.
  adapter/internal/api/apis_impl.go
Labels: Type/Bug

#2121 Support API UUID for Internal Maps
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/discovery/xds/server_test.go
  adapter/internal/discovery/xds/server_utils.go
  adapter/internal/discovery/xds/server_utils_test.go
Labels: Type/New Feature, envoy-gw

#2142 Fix #2081 - Internal key cache issue
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/dto/JWTTokenPayloadInfo.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/InternalKeyTestCase.java
Labels: Type/Bug

#2141 Set correct api uuid and publisher for analytics event
  adapter/internal/synchronizer/apis_fetcher.go
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsUtils.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
Labels: Type/Bug

#2139 Merge Feature branch with Main
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/discovery/xds/server_test.go
  adapter/internal/discovery/xds/server_utils.go
  adapter/internal/discovery/xds/server_utils_test.go
  adapter/internal/messaging/messaging_test.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/model/constants.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/pkg/messaging/connection.go
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsUtils.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/dto/JWTTokenPayloadInfo.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/InternalKeyTestCase.java
Labels: Type/Task, feature/global-adapter

#2138 Implement Fetch APIs Functionality for Global adapter configuration for startup
  adapter/internal/ga/client.go
Labels: Type/Task, feature/global-adapter

#2147 Fix #2146 - Remove x-envoy-upstream-service-time header from response
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/SubscriptionValidationTestCase.java
Labels: Type/Bug

#2144 Change MG_USER_ID and MG_USER_GROUP_ID in Dockerfile.
  adapter/src/main/resources/Dockerfile
  enforcer/src/main/resources/Dockerfile
  router/src/main/resources/Dockerfile
Labels: Type/Task

#2152 Rename Websub to webhook
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/model/constants.go
Labels: Type/Task

#2148 Include organization UUID within the protobuf payload from global adapter
  adapter/internal/ga/client.go
  adapter/pkg/discovery/api/wso2/discovery/ga/api.pb.go
  adapter/pkg/synchronizer/types.go
  api/proto/wso2/discovery/ga/api.proto
Labels: Type/Task, feature/global-adapter

#2155 Merging the feature branch with main
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/model/constants.go
  adapter/src/main/resources/Dockerfile
  enforcer/src/main/resources/Dockerfile
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/SubscriptionValidationTestCase.java
  router/src/main/resources/Dockerfile
Labels: Type/Task, feature/global-adapter

#2156 fixed #2145
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
Labels: Type/Bug

#2157 Prepare for release 3.2.3
  README.md
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/jwt/generator/MGWJWTGeneratorInvoker.java
  distribution/LICENSE-RUNTIME.txt
  distribution/LICENSE-TOOLKIT.txt
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/resources/version.txt
  distribution/src/main/assembly/filter.properties
  release-notes.html
  samples/sample-jwt-generator/pom.xml
Labels: Type/Task

#2158 prepare for 3.2.3 release
  README.md
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/jwt/generator/MGWJWTGeneratorInvoker.java
  distribution/LICENSE-RUNTIME.txt
  distribution/LICENSE-TOOLKIT.txt
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/resources/version.txt
  distribution/src/main/assembly/filter.properties
  release-notes.html
  samples/sample-jwt-generator/pom.xml
Labels: Type/Task

#2159 fixed by adding .jar extension
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
Labels: Type/Task

#2137 implement retrying for global adapter connection
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/go.mod
  adapter/go.sum
  adapter/internal/adapter/adapter.go
  adapter/internal/ga/client.go
  resources/conf/config.toml.template
Labels: Type/Task, feature/global-adapter

#2127 Local Adapter Related Implementation
  adapter/go.sum
  adapter/internal/adapter/adapter.go
  adapter/internal/eventhub/subscription.go
  adapter/internal/ga/api_event_listener.go
  adapter/internal/ga/client.go
  adapter/internal/ga/client_test.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/pkg/adapter/adapter.go
  adapter/pkg/health/controlplane.go
  adapter/pkg/synchronizer/apis_fetcher.go
Labels: Type/Task, feature/global-adapter

#2150 Mutual TLS communication with Global Adapter
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/ga/client.go
  resources/adapter/security/truststore/global-adapter.pem
  resources/conf/config.toml.template
Labels: Type/Task, feature/global-adapter

#2171 Enable readiness probe when the eventhub is disabled
  adapter/internal/adapter/adapter.go
Labels: Type/Bug

#2104 Send deployment status
  adapter/config/types.go
  adapter/go.mod
  adapter/go.sum
  adapter/internal/adapter/adapter.go
  adapter/internal/api/apis_impl.go
  adapter/internal/api/restserver/config_restapi.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/eventhub/subscription.go
  adapter/internal/loggers/logger.go
  adapter/internal/notifier/deployment_notifier.go
  adapter/internal/notifier/types.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/internal/synchronizer/keymanagers_fetcher.go
  adapter/internal/synchronizer/revoked_tokens_fetcher.go
  adapter/internal/synchronizer/throttle_data_fetcher.go
  adapter/pkg/tlsutils/tls_utils.go
Labels: Type/New Feature, envoy-gw

#2167 Add a check for trailing slashes in endpoint URL.
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/EndpointsWithTrailingSlashTestCase.java
  integration/test-integration/src/test/resources/apimApisAppsSubs/apis.json
  integration/test-integration/src/test/resources/apimApisAppsSubs/applications.json
  integration/test-integration/src/test/resources/apimApisAppsSubs/subscriptions.json
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Type/Bug, envoy-gw

#2103 Handle adapter crash issue when malformed endpoints are provided
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/mgw_swagger_internal_test.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/open_api_internal_test.go
  adapter/internal/oasparser/model/swagger.go
  adapter/internal/oasparser/model/swagger_test.go
  adapter/internal/oasparser/operator/operator.go
  adapter/internal/oasparser/operator/operator_test.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/pkg/messaging/listener.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/endpoints/MalformedEndpointTestCase.java
  integration/test-integration/src/test/resources/openAPIs/malformed_endpoint_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
Labels: Choreo, Priority/Highest, Severity/Major, Type/Bug, envoy-gw

#2166 Updating APIDeployment type to match GA
  adapter/pkg/synchronizer/types.go
Labels: Type/Task, feature/global-adapter

#2176 Add template config file to the distribution pack
  distribution/src/main/assembly/assembly.xml
Labels: Type/Improvement

#2035 Cert header validation fix
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/mutualSSL_handler.bal
Labels: Affected/3.2.0

#2161 Validate malformed endpoint
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/open_api_internal_test.go
Labels: Type/Bug

#2130 int-tests: add startup and eventhub groups
  integration/test-integration/readme.md
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Type/Task

#2180 Fix deployment status retries
  adapter/internal/notifier/deployment_notifier.go
Labels: Type/Bug, envoy-gw
