Repository wso2/product-microgateway, pull requests merged in 2021-08, with the labels that each got.

#2177 Initial skeleton to test azure event subscription flow
  adapter/internal/adapter/adapter.go
  adapter/internal/messaging/azure_listener.go
  adapter/pkg/messaging/azure_connection.go
Labels: Type/Task

#2188 Upgrade analytics publisher version to v1.0.2
  pom.xml
Labels: Type/Task

#2190 Add correct environment variable name to be read for connection param
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/messaging/azure_listener.go
  adapter/pkg/messaging/azure_connection.go
  resources/conf/config.toml.template
Labels: Type/Task

#2006 Fix maven build warnings
  adapter/src/main/assembly/assembly.xml
  pom.xml
  resources/conf/log_config.toml
  router/src/main/assembly/assembly.xml
Labels: Type/Improvement, Type/Task, envoy-gw

#2194 Add subscriber implementation for token revocation and notification events from azure service bus
  adapter/go.mod
  adapter/go.sum
  adapter/internal/adapter/adapter.go
  adapter/internal/messaging/azure_listener.go
  adapter/internal/messaging/listener.go
  adapter/internal/messaging/messaging_test.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/messaging/revoked_token_listener.go
  adapter/pkg/health/controlplane.go
  adapter/pkg/messaging/azure_connection.go
  adapter/pkg/messaging/azure_listener.go
Labels: Type/Task

#2198 Upgrade analytics publisher version to v1.0.4
  pom.xml
Labels: Type/Task

#2126 Use a map instead of list, to keep track of enforcer resources within adapter
  adapter/go.sum
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/eventhub/subscription.go
  adapter/internal/messaging/messaging_test.go
  adapter/internal/messaging/notification_listener.go
Labels: Type/Bug, Type/Improvement

#2196 Add connection retry logic for service bus subscription
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/messaging/azure_listener.go
  adapter/pkg/messaging/azure_connection.go
  adapter/pkg/messaging/azure_listener.go
  resources/conf/config.toml.template
Labels: Type/Task

#2208 Merge Main branch
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/messaging/azure_listener.go
  adapter/pkg/messaging/azure_connection.go
  adapter/pkg/messaging/azure_listener.go
  resources/conf/config.toml.template
Labels: Type/Task, feature/global-adapter
