Repository wso2/product-microgateway, pull requests merged in 2021-02, with the labels that each got.

#1579 Fix Open APIv2 struct issue
  adapter/pkg/xds/xds_server.go
Labels: Type/Improvement, envoy-gw

#1585 Add log rotation
  resources/docker-compose.yaml
Labels: Type/Task, envoy-gw

#1584 fixed-too much info logging
  adapter/pkg/oasparser/envoyconf/routesWithClusters.go
  adapter/pkg/xds/xds_server.go
Labels: Type/Improvement, envoy-gw

#1598 Remove [enforcer.eventHub] configs from config.toml
  adapter/pkg/subscription/subscription.go
  adapter/pkg/xds/xds_server.go
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApiListDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApplicationDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApplicationKeyMappingDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApplicationPolicyDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/SubscriptionDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/SubscriptionPolicyDiscoveryClient.java
  resources/conf/config.toml
Labels: Type/Improvement, envoy-gw

#1593 Add a config to start Consul service discovery
  adapter/config/mgwtypes.go
  adapter/pkg/oasparser/model/mgwSwagger.go
  adapter/pkg/svcdiscovery/watcher.go
  adapter/pkg/xds/xds_server.go
  resources/conf/config.toml
Labels: Type/Improvement, envoy-gw

#1605 Support trailing arguments for the router CMD via environmental variables.
  router/src/main/resources/Dockerfile
Labels: Type/Improvement, envoy-gw

#1604 Refactor tlsEnabled config and avoid retrying for 4xx errors.
  adapter/config/mgwtypes.go
  adapter/pkg/mgw/mgw.go
  adapter/pkg/subscription/subscription.go
  adapter/pkg/synchronizer/apis_fetcher.go
  adapter/pkg/synchronizer/synchronizer_dtos.go
  resources/conf/config.toml
Labels: Type/Improvement, envoy-gw

#1599 Fix checkstyle and javadoc issues
  enforcer/pom.xml
  enforcer/suppressions.xml
  test/pom.xml
Labels: Type/Task, envoy-gw

#1597 Update K8s configs for MG 4.0.0-m5
  resources/k8s-artifacts/mg-adapter/adapter-keystore-secret.yaml
  resources/k8s-artifacts/mg-adapter/adapter-tls-secret.yaml
  resources/k8s-artifacts/mg-adapter/adapter-truststore-secret.yaml
  resources/k8s-artifacts/mg-adapter/config-toml-configmap.yaml
  resources/k8s-artifacts/mg-adapter/deployment.yaml
  resources/k8s-artifacts/mg-adapter/logconfig-toml-configmap.yaml
  resources/k8s-artifacts/mg-enforcer/client-truststore-secret.yaml
  resources/k8s-artifacts/mg-enforcer/deployment.yaml
  resources/k8s-artifacts/mg-enforcer/enforcer-keystore-secret.yaml
  resources/k8s-artifacts/mg-enforcer/enforcer-truststore-secret.yaml
  resources/k8s-artifacts/mg-router/deployment.yaml
  resources/k8s-artifacts/mg-router/router-keystore-secret.yaml
  resources/k8s-artifacts/mg-router/router-tls-secret.yaml
  resources/k8s-artifacts/mg-router/router-truststore-secret.yaml
Labels: Type/Improvement, envoy-gw

#1609 Fix issues in release build
  pom.xml
Labels: Type/Task, envoy-gw

#1610 Fix javadoc issue
  pom.xml
Labels: Type/Task, envoy-gw

#1611 fix javadoc issue
  pom.xml
Labels: Type/Task, envoy-gw

#1612 Prepare for 4.0.0-m5 release
  README.md
  developer-guide.md
  remove-containers.sh
  resources/docker-compose.yaml
Labels: Type/Task, envoy-gw

#1614 Set build version in docker-compose and refactor code
  developer-guide.md
  docker/with-external-build/control-plane/Dockerfile
  docker/with-external-build/docker-compose.yaml
  docker/with-external-build/envoy/Dockerfile
  docker/with-external-build/filter-chain/Dockerfile
  docker/without-dependencies/control-plane/Dockerfile
  docker/without-dependencies/docker-compose.yaml
  docker/without-dependencies/filter-chain/Dockerfile
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/RequestContext.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/RestAPI.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/dto/AuthServiceConfigurationDto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/APIConstants.java
  pom.xml
  remove-containers.sh
  resources/docker-compose.yaml
Labels: Type/Task, envoy-gw

#1616 Add scm
  pom.xml
Labels: Type/Task, envoy-gw

#1617 Fix version replacement using maven-antrun-plugin
  pom.xml
Labels: Type/Task, envoy-gw

#1619 Configure Travis
  .travis.yml
Labels: Type/Task, envoy-gw

#1618 [envoy-gw] Refactor update API
  adapter/pkg/oasparser/configGenerator.go
  adapter/pkg/oasparser/model/mgwResource.go
  adapter/pkg/oasparser/model/mgwSwagger.go
  adapter/pkg/oasparser/model/mgwSwagger_internal_test.go
  adapter/pkg/oasparser/model/openApi.go
  adapter/pkg/oasparser/model/swagger.go
  adapter/pkg/xds/xds_server.go
Labels: Type/Improvement, envoy-gw

#1628 push to docker and skip zip upload to nexus
  README.md
  distribution/pom.xml
  pom.xml
  test/mock-backend-server/pom.xml
Labels: Type/Task, envoy-gw

#1633 Configure max inbound msg size for xds
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/EnvVarConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/Constants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApiDiscoveryClient.java
  resources/docker-compose.yaml
Labels: Type/Improvement

#1636 Bug fix : APIList Discovery Client cannot retrieve events
  adapter/go.mod
  adapter/go.sum
  adapter/pkg/messaging/eventtypes.go
  adapter/pkg/messaging/notificationListener.go
  adapter/pkg/mgw/mgw.go
  adapter/pkg/resourcetypes/dto.go
  adapter/pkg/subscription/subscription.go
  adapter/pkg/xds/xds_server.go
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/common/ReferenceHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/Constants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/keymgt/KeyManagerDataService.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/keymgt/KeyManagerDataServiceImpl.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/listener/GatewayJMSMessageListener.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/server/AuthServer.java
Labels: Type/Bug

#1640 Encoding mgw labels to compatible with control plane.
  adapter/pkg/messaging/eventtypes.go
  adapter/pkg/messaging/notificationListener.go
  adapter/pkg/resourcetypes/dto.go
  adapter/pkg/synchronizer/apis_fetcher.go
Labels: Priority/Normal, Type/Improvement

#1641 Move xds proto to mgw repo
  adapter/api/wso2/discovery/keymgt/key_manager_config.pb.go
  adapter/api/wso2/discovery/service/keymgt/kmds.pb.go
  adapter/api/wso2/discovery/service/keymgt/kmds_grpc.pb.go
  api/wso2/discovery/api/Endpoint.proto
  api/wso2/discovery/api/Resource.proto
  api/wso2/discovery/api/api.proto
  api/wso2/discovery/config/enforcer/am_credentials.proto
  api/wso2/discovery/config/enforcer/auth_service.proto
  api/wso2/discovery/config/enforcer/binary_throttling.proto
  api/wso2/discovery/config/enforcer/cert.proto
  api/wso2/discovery/config/enforcer/config.proto
  api/wso2/discovery/config/enforcer/event_hub.proto
  api/wso2/discovery/config/enforcer/issuer.proto
  api/wso2/discovery/config/enforcer/jwt_generator.proto
  api/wso2/discovery/config/enforcer/thread_pool.proto
  api/wso2/discovery/config/enforcer/throttle_agent.proto
  api/wso2/discovery/config/enforcer/throttle_publisher.proto
  api/wso2/discovery/config/enforcer/throttling.proto
  api/wso2/discovery/config/enforcer/tm_url_group.proto
  api/wso2/discovery/keymgt/key_manager_config.proto
  api/wso2/discovery/service/api/apids.proto
  api/wso2/discovery/service/config/cds.proto
  api/wso2/discovery/service/keymgt/kmds.proto
  api/wso2/discovery/service/subscription/apids.proto
  api/wso2/discovery/service/subscription/app_key_mapping_ds.proto
  api/wso2/discovery/service/subscription/app_policy_ds.proto
  api/wso2/discovery/service/subscription/appds.proto
  api/wso2/discovery/service/subscription/sds.proto
  api/wso2/discovery/service/subscription/sub_policy_ds.proto
  api/wso2/discovery/subscription/api.proto
  api/wso2/discovery/subscription/api_list.proto
  api/wso2/discovery/subscription/application.proto
  api/wso2/discovery/subscription/application_key_mapping.proto
  api/wso2/discovery/subscription/application_key_mapping_list.proto
  api/wso2/discovery/subscription/application_list.proto
  api/wso2/discovery/subscription/application_policy.proto
  api/wso2/discovery/subscription/application_policy_list.proto
  api/wso2/discovery/subscription/subscription.proto
  api/wso2/discovery/subscription/subscription_list.proto
  api/wso2/discovery/subscription/subscription_policy.proto
  api/wso2/discovery/subscription/subscription_policy_list.proto
  api/wso2/discovery/subscription/url_mapping.proto
  enforcer/pom.xml
  enforcer/src/main/gen/org/wso2/gateway/discovery/km/KeyManagerConfig.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/km/KeyManagerConfigOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/km/KeyManagerConfigProto.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/service/keymgt/KMDiscoveryService.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/service/keymgt/KMDiscoveryServiceGrpc.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/service/keymgt/KmdsProto.java
Labels: Priority/Normal, Type/Task, envoy-gw

#1639 Fix Labelling For Enforcer
  adapter/pkg/api/file_read_utils.go
  adapter/pkg/oasparser/operator/operator.go
  adapter/pkg/xds/xds_server.go
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/AdapterConstants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApiListDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApplicationDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApplicationKeyMappingDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApplicationPolicyDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ConfigDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/SubscriptionDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/SubscriptionPolicyDiscoveryClient.java
  enforcer/src/main/resources/Dockerfile
  remove-containers.sh
  resources/docker-compose.yaml
  router/src/main/resources/Dockerfile
Labels: Priority/High, Type/Bug, envoy-gw

#1649 Fix #1648 - Enable Access logs for the enforcer
  enforcer/pom.xml
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/config/APIConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/APIConstants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/grpc/ExtAuthService.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/grpc/interceptors/AccessLogInterceptor.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/AuthFilter.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/server/AuthServer.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/util/FilterUtils.java
  enforcer/src/main/resources/Dockerfile
  resources/conf/log4j2.properties
Labels: Type/Improvement

#1503 fix java_args not being set during the startup of gateway batch script
  distribution/resources/bin/gateway.bat
Labels: Affected/3.2.0, Priority/Normal, Type/Bug

#1626 Add backend jwt generation feature
  adapter/config/mgwtypes.go
  adapter/pkg/xds/xds_server.go
  distribution/src/main/assembly/assembly.xml
  enforcer/pom.xml
  enforcer/src/main/gen/org/wso2/gateway/discovery/service/km/KMDiscoveryService.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/service/km/KMDiscoveryServiceGrpc.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/service/km/KmdsProto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/common/CacheProvider.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/EnforcerConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/EnvVarConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/Constants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/JwtConstants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/JWTAuthenticator.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/JWTUtil.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/JWTValidationInfo.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/validator/JWTConstants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/validator/JWTValidator.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/util/FilterUtils.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/util/TLSUtils.java
  resources/conf/config.toml
  resources/docker-compose.yaml
  test/mock-backend-server/pom.xml
  test/mock-backend-server/src/main/assembly/assembly.xml
  test/mock-backend-server/src/main/java/org.wso2am.micro.gw.mockbackend/MockBackEndServer.java
  test/mock-backend-server/src/main/java/org.wso2am.micro.gw.mockbackend/ResponseConstants.java
  test/test-integration/pom.xml
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/jwtGenerator/jwtGeneratorTestCase.java
  test/test-integration/src/test/resources/apis/openApis/mockApi.yaml
  test/test-integration/src/test/resources/testng.xml
Labels: Priority/High, Type/New Feature, envoy-gw

#1651 Complete the Subscription Validation Flow
  adapter/pkg/discovery/resource/v3/resource.go
  adapter/pkg/messaging/eventtypes.go
  adapter/pkg/messaging/notificationListener.go
  adapter/pkg/mgw/mgw.go
  adapter/pkg/oasparser/envoyconf/routesWithClusters.go
  adapter/pkg/oasparser/model/mgwSwagger.go
  adapter/pkg/resourcetypes/dto.go
  adapter/pkg/subscription/subscription.go
  adapter/pkg/xds/xds_server.go
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/config/ResourceConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApiListDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/KeyValidator.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/JWTAuthenticator.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/subscription/SubscriptionDataLoader.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/subscription/SubscriptionDataLoaderImpl.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/subscription/SubscriptionDataStoreImpl.java
Labels: Priority/Normal, Type/New Feature

#1647 Update K8s configs for MG 4.0.0-m6
  resources/k8s-artifacts/mg-adapter/config-toml-configmap.yaml
  resources/k8s-artifacts/mg-adapter/deployment.yaml
  resources/k8s-artifacts/mg-enforcer/deployment.yaml
  resources/k8s-artifacts/mg-router/deployment.yaml
Labels: Type/Task, envoy-gw

#1654 Disable BE jwt generation by default
  resources/conf/config.toml
  resources/k8s-artifacts/mg-adapter/config-toml-configmap.yaml
Labels: Priority/High, Type/Improvement

#1646 Prepare for 4.0.0-m6
  README.md
  developer-guide.md
  remove-containers.sh
  resources/docker-compose.yaml
Labels: Priority/High, Type/Task

#1506 Fixing API level sandbox and production endpoint confusion.
  components/micro-gateway-cli/src/main/resources/templates/useAPIProdEp.mustache
  components/micro-gateway-cli/src/main/resources/templates/useApiSandEp.mustache
Labels: Affected/3.2.0, Priority/Normal, Type/Bug

#1655 Fix a test failure in JWTGenerator
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/jwtGenerator/JwtGeneratorTestCase.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/TestConstant.java
  test/test-integration/src/test/resources/jwtGenerator/config.toml
  test/test-integration/src/test/resources/testng.xml
Labels: Priority/High, Type/Bug

#1656 Complete 4.0.0-m6 release
  adapter/pom.xml
  distribution/pom.xml
  enforcer/pom.xml
  pom.xml
  remove-containers.sh
  resources/docker-compose.yaml
  router/pom.xml
  test/mock-backend-server/pom.xml
  test/pom.xml
  test/test-integration/pom.xml
Labels: Priority/Highest, Type/Task

#1658 Fix #1657 - Make gateway jwt cache configurable
  adapter/api/wso2/discovery/config/enforcer/am_credentials.pb.go
  adapter/api/wso2/discovery/config/enforcer/auth_service.pb.go
  adapter/api/wso2/discovery/config/enforcer/binary_throttling.pb.go
  adapter/api/wso2/discovery/config/enforcer/cache.pb.go
  adapter/api/wso2/discovery/config/enforcer/cert.pb.go
  adapter/api/wso2/discovery/config/enforcer/config.pb.go
  adapter/api/wso2/discovery/config/enforcer/event_hub.pb.go
  adapter/api/wso2/discovery/config/enforcer/issuer.pb.go
  adapter/api/wso2/discovery/config/enforcer/jwt_generator.pb.go
  adapter/api/wso2/discovery/config/enforcer/thread_pool.pb.go
  adapter/api/wso2/discovery/config/enforcer/throttle_agent.pb.go
  adapter/api/wso2/discovery/config/enforcer/throttle_publisher.pb.go
  adapter/api/wso2/discovery/config/enforcer/throttling.pb.go
  adapter/api/wso2/discovery/config/enforcer/tm_url_group.pb.go
  adapter/config/mgwtypes.go
  adapter/pkg/xds/xds_server.go
  api/wso2/discovery/config/enforcer/cache.proto
  api/wso2/discovery/config/enforcer/config.proto
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/Cache.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/CacheOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/CacheProto.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/Config.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/ConfigOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/ConfigProto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/common/CacheProvider.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigDefaults.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/EnforcerConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/dto/CacheDto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/grpc/ExtAuthService.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/JWTAuthenticator.java
  resources/conf/config.toml
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/context/MgwServerInstance.java
  test/test-integration/src/test/resources/backend-service-tls.yaml
Labels: Type/Improvement, envoy-gw

#1607 fix line spacing
  adapter/pkg/oasparser/utills/openApiUtills_test.go
  test/mock-backend-server/src/main/java/org.wso2am.micro.gw.mockbackend/MockBackEndServer.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/common/BaseTestCase.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/common/model/ApplicationDTO.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/context/MgwServerInstance.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/mockbackend/MockBackendServer.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/HttpClientRequest.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/HttpPostMultipart.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/HttpsPostMultipart.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/Utils.java
  test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/ZipDir.java
Labels: Priority/Normal, Type/Task

#1664 Add AMQP failover endpoint support
  adapter/config/types.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/am_credentials.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/auth_service.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/binary_throttling.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/cache.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/cert.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/config.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/event_hub.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/issuer.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/jms_connection_params.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/jwt_generator.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/thread_pool.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/throttle_agent.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/throttle_publisher.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/throttling.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/tm_url_group.pb.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/messaging/connection.go
  adapter/internal/messaging/listener.go
  api/wso2/discovery/config/enforcer/event_hub.proto
  api/wso2/discovery/config/enforcer/jms_connection_params.proto
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/EventHub.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/EventHubOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/EventHubProto.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/JMSConnectionParamsProto.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/JmsConnectionParameters.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/config/enforcer/JmsConnectionParametersOrBuilder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
  resources/conf/config.toml
  test/test-integration/src/test/resources/jwtGenerator/config.toml
Labels: Type/Improvement, envoy-gw
