Repository wso2/product-microgateway, pull requests merged in 2021-11, with the labels that each got.

#2347 Custom Filter Properties via configurations
  adapter/config/types.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/pkg/discovery/api/wso2/discovery/api/Endpoint.pb.go
  adapter/pkg/discovery/api/wso2/discovery/api/Resource.pb.go
  adapter/pkg/discovery/api/wso2/discovery/api/api.pb.go
  adapter/pkg/discovery/api/wso2/discovery/api/endpoint_cluster.pb.go
  adapter/pkg/discovery/api/wso2/discovery/config/enforcer/filter.pb.go
  api/proto/wso2/discovery/config/enforcer/filter.proto
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/Filter.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/Filter.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/FilterOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/FilterProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/dto/FilterDTO.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/cors/CorsFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketMetaDataFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketThrottleFilter.java
  integration/test-integration/src/main/java/org/wso2/choreo/connect/tests/CustomFilter.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/circuitBreakers/CircuitBreakersTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/filter/CustomFilterTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/interceptor/InterceptorBaseTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/interceptor/InterceptorRequestFlowTestcase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/interceptor/InterceptorResponseFlowTestcase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/interceptor/InterceptorServiceNotAvailableTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/interceptor/InterceptorServiceRequestBodyTestCase.java
  integration/test-integration/src/test/resources/configs/jwt-generator-config.toml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
  resources/conf/config.toml.template
Labels: Type/Improvement

#2354 Refactor configurations with support for old properties
  adapter/config/default_config.go
  adapter/config/parser.go
  adapter/config/types.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/svcdiscovery/watcher.go
  adapter/pkg/config/parser_test.go
  adapter/scripts/build.sh
  resources/conf/config-for-eventhub.toml
  resources/conf/config.toml
  resources/conf/config.toml.template
  resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
Labels: Type/Task, Priority/High, Docs/Has Impact

#2359 Open API Definition for Interceptor and sample interceptor service in Ballerina
  resources/interceptor-service-open-api.yaml
  samples/interceptors/.gitignore
  samples/interceptors/README.md
  samples/interceptors/bookstore-api.yaml
  samples/interceptors/cc-sample-legacy-xml-backend/.gitignore
  samples/interceptors/cc-sample-legacy-xml-backend/Ballerina.toml
  samples/interceptors/cc-sample-legacy-xml-backend/Cloud.toml
  samples/interceptors/cc-sample-legacy-xml-backend/backend-service.bal
  samples/interceptors/cc-sample-xml-interceptor/.gitignore
  samples/interceptors/cc-sample-xml-interceptor/Ballerina.toml
  samples/interceptors/cc-sample-xml-interceptor/Cloud.toml
  samples/interceptors/cc-sample-xml-interceptor/interceptor-service-open-api_service.bal
  samples/interceptors/cc-sample-xml-interceptor/types.bal
  samples/interceptors/create-interceptor-certs.sh
  samples/interceptors/docker-compose.yaml
Labels: Type/Task

#2366 Fix sandbox endpoint invocation failure with apim
  adapter/internal/eventhub/subscription.go
  adapter/internal/messaging/notification_listener.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/TracerFactory.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/StoreUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/ExistingApiTestCase.java
  integration/test-integration/src/test/resources/apimApisAppsSubs/apis.json
  integration/test-integration/src/test/resources/apimApisAppsSubs/applications.json
  integration/test-integration/src/test/resources/apimApisAppsSubs/subscriptions.json
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Type/Bug, Priority/High

#2365 Prepare for 1.0.0-alpha release
  ENVOY_GW_README.md
  integration/mock-backend-server/pom.xml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  release-note.html
  remove-containers.sh
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#2379 Test dynamic endpoints with custom filters
  integration/test-integration/src/main/java/org/wso2/choreo/connect/tests/CustomFilter.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/filter/CustomFilterTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/interceptor/InterceptorRequestFlowTestcase.java
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  integration/test-integration/src/test/resources/openAPIs/intercept_request_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/openAPI.yaml
  remove-containers.sh
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task, test-improvements

#2386 Upgrade balleirna to 1.2.21
  pom.xml
Labels: ballerina-mgw

#2377 Updating minimum cpu and memory in cc
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Improvement

#2375 Support env specific properties
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/types.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/pkg/synchronizer/apis_fetcher.go
  adapter/pkg/synchronizer/types.go
Labels: Type/New Feature

#2399 int-test: Enable mtls in mockbackend and interceptor service
  integration/mock-backend-server/pom.xml
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendProd.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendSandbox.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockInterceptorServer.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockServices.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Utils.java
  integration/mock-backend-server/src/main/resources/Dockerfile
  integration/mock-backend-server/src/main/resources/backendKeystore.pem
  integration/mock-backend-server/src/main/resources/backendKeystore.pkcs12
  integration/mock-backend-server/src/main/resources/client-truststore.jks
  integration/mock-backend-server/src/main/resources/interceptorKeystore.pem
  integration/mock-backend-server/src/main/resources/interceptorKeystore.pkcs12
  integration/mock-backend-server/src/main/resources/mg.pem
  integration/mock-backend-server/src/main/resources/wso2carbon.jks
  integration/test-integration/pom.xml
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/ChoreoConnectImpl.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithBackendTlsAndCorsDisabled.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithJwtConfig.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/StandaloneBeforeTestSuite.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/APiDeployViaApictlTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/QSGTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/mtls/MtlsFromRouterToBackendTestcase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/ApictlUtils.java
  integration/test-integration/src/test/resources/certs/backend_tls.crt
  integration/test-integration/src/test/resources/certs/interceptor.crt
  integration/test-integration/src/test/resources/configs/cors-disabled-config.toml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
  integration/test-integration/src/test/resources/openAPIs/intercept_request_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/intercept_response_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/mtls_from_router_to_backend_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
Labels: Type/Task, test-improvements

#2413 bug fix: GA connection fails as overwritehostname property is not replaced.
  adapter/internal/ga/client.go
Labels: Type/Bug

#2408 Fixing consul service mesh issues
  adapter/internal/discovery/xds/consul.go
  adapter/internal/svcdiscovery/client.go
  adapter/internal/svcdiscovery/watcher.go
  resources/conf/config.toml.template
Labels: Type/Bug

#2415 bug fix: Override hostname is not properly replaced. Hence GA connection fails
  adapter/internal/ga/client.go
Labels: Type/Bug

#2419 update alias name
  adapter/pkg/synchronizer/types.go
Labels: Type/Bug

#2416 Improve interceptor extension
  adapter/internal/oasparser/model/constants.go
  adapter/internal/oasparser/model/mgw_swagger.go
  integration/test-integration/src/test/resources/openAPIs/intercept_request_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/intercept_response_openAPI.yaml
  samples/interceptors/bookstore-api.yaml
Labels: Type/Improvement

#2392 Add samples for custom filters
  samples/filters/sample-filter/README.md
  samples/filters/sample-filter/pom.xml
  samples/filters/sample-filter/src/main/java/sample/filter/CustomFilter.java
  samples/filters/sample-filter/src/main/resources/META-INF/services/org.wso2.choreo.connect.enforcer.commons.Filter
Labels: Type/Task

#2402 Add per endpoint cert
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/mgw_swagger_internal_test.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/open_api_internal_test.go
  adapter/internal/oasparser/model/types.go
  adapter/internal/oasparser/operator/operator_test.go
Labels: Type/Improvement

#2423 Updating docker compose version from v2 to v3
  integration/test-integration/src/test/resources/dockerCompose/apim-in-common-network-docker-compose.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  resources/docker-compose/apim/docker-compose.yaml
Labels: Type/Task

#2396 Go-Control-Plane Version upgrade and remove deprecated fields
  adapter/go.mod
  adapter/go.sum
  adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
  adapter/internal/discovery/xds/routercallbacks/router_callbacks.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/access_loggers.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/pkg/discovery/protocol/cache/v3/resource.go
  adapter/pkg/discovery/protocol/cache/v3/simple.go
  adapter/pkg/discovery/protocol/cache/v3/snapshot.go
  adapter/pkg/discovery/protocol/cache/v3/status.go
  adapter/pkg/discovery/protocol/resource/v3/resource.go
  adapter/pkg/discovery/protocol/server/sotw/v3/server.go
  adapter/pkg/discovery/protocol/server/v3/server.go
  router/src/main/resources/Dockerfile
Labels: Type/Improvement

#2434 Fix custom params api.yaml
  adapter/internal/oasparser/model/types.go
  adapter/pkg/discovery/api/wso2/discovery/api/security_info.pb.go
  api/proto/wso2/discovery/api/security_info.proto
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/SecurityInfo.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/SecurityInfo.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/SecurityInfoOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/SecurityInfoProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/APIProcessUtils.java
Labels: Type/Bug

#2391 Improve memory utilization for Applications
  adapter/go.sum
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/eventhub/subscription.go
  adapter/internal/ga/api_event_listener.go
  adapter/internal/messaging/notification_listener.go
Labels: Type/Improvement

#2427 Add support for common tracing config
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/go.sum
  adapter/internal/adapter/adapter.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/envoyconf/access_loggers.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/TracingConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/AzureExporter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/JaegerExporter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/ZipkinExporter.java
  enforcer-parent/enforcer/src/test/java/org/wso2/choreo/connect/enforcer/tracing/exporters/JaegerExporterTest.java
  enforcer-parent/enforcer/src/test/java/org/wso2/choreo/connect/enforcer/tracing/exporters/ZipkinExporterTest.java
  resources/conf/config.toml.template
Labels: Type/Improvement, Priority/Normal

#2435 Bug-Fix: [Websocket] Fix Null pointer issues popped during websocket APIs Invocation
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/Utils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketMetaDataFilter.java
Labels: Type/Bug

#2438 Bug fix: [Enforcer] Fix the issue where path parameters does not resolve depending on the trailing slash
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/ParameterResolver.java
  enforcer-parent/commons/src/test/java/org/wso2/choreo/connect/enforcer/commons/model/RequestContextTest.java
Labels: Type/Bug

#2432 Refactor logic related to tokens and fix few bugs
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/model/constants.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/open_api_internal_test.go
  adapter/internal/oasparser/model/swagger.go
  adapter/internal/oasparser/model/swagger_internal_test.go
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/ResourceConfig.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/common/ReferenceHolder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyHandler.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/BackendJwtUtils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/EndpointSecurityUtils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/JWTUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/PublisherUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/APIKeyAppLevelTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/APIKeyHeaderTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/APIKeyQueryParamTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/APIKeyTestCase.java
  integration/test-integration/src/test/resources/openAPIs/app_level_security_openAPI.yaml
Labels: Type/Bug, Type/Task

#2450 Fix enabling enforcer tracing
  adapter/go.sum
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/AuthServer.java
Labels: Type/Bug, Priority/Highest

#2453 bug-fix [TokenRevocation] Revoked Tokens are not properly updated when enforcer restarts.
  adapter/pkg/discovery/protocol/cache/v3/resource.go
Labels: Type/Bug

#2441 Fix backend basic auth security
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/EndpointSecurityUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/dto/Api.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BackendSecurityTestCase.java
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Type/Task, test-improvements

#2452 Updating config.toml template for tracing
  resources/conf/config.toml
  resources/conf/config.toml.template
Labels: Type/Task

#2444 Bug fix: [ Websocket] APIs with no endpointBasepath results in XDS update failure
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
Labels: Type/Bug

#2455 Fix no security basic auth backend
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/EndpointSecurityUtils.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendProd.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BackendSecurityTestCase.java
Labels: Type/Bug

#2461 Update enforcer JDK 11 docker image
  enforcer-parent/enforcer/src/main/resources/Dockerfile
Labels: Type/Task

#2431 Prepare for 1.0.0-beta release
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  release-note.html
  remove-containers.sh
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#2469 Bug-Fix :Mount a envoy.yaml so that default envoy configuration won't apply
  router/src/main/resources/Dockerfile
Labels: Type/Bug

#2467 Router concurrency level change
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  router/src/main/resources/Dockerfile
Labels: Type/Task

#2464 Bug-fix [Vhost] Resolve issue where APIs are not properly undeployed from specific host under specific environment.
  adapter/internal/discovery/xds/server.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithMultipleEnv.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/ApictlUtils.java
  integration/test-integration/src/test/resources/configs/multiple-env-config.toml
  integration/test-integration/src/test/resources/deploymentEnvironments/apictl_test_deploy_multiple_env.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
Labels: Type/Bug

#2470 Add basepath validation
  adapter/go.sum
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/mgw_swagger_internal_test.go
Labels: Type/Bug

#2465 At API level apply only the specified security scheme
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/operator/operator.go
  adapter/pkg/discovery/api/wso2/discovery/api/Resource.pb.go
  adapter/pkg/discovery/api/wso2/discovery/api/api.pb.go
  adapter/pkg/discovery/api/wso2/discovery/api/security_scheme.pb.go
  api/proto/wso2/discovery/api/Resource.proto
  api/proto/wso2/discovery/api/api.proto
  api/proto/wso2/discovery/api/security_scheme.proto
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/APIConfig.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/Api.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiProto.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ResourceProto.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/Scopes.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ScopesOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/SecurityList.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/SecurityListOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/SecuritySchemeProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/InternalKeyTestCase.java
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  remove-containers.sh
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Bug

#2473 Override endpoints using environment variables
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/internal/oasparser/model/api_env.go
  adapter/internal/oasparser/model/api_yaml.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/types.go
Labels: Type/Bug

#2462 Performance test details relevant to the CC V1 release
  performance/benchmarks/cpus-1/images/diagram.png
  performance/benchmarks/cpus-1/images/percentile.png
  performance/benchmarks/cpus-1/images/response_time_0ms.png
  performance/benchmarks/cpus-1/images/throughput.png
  performance/benchmarks/cpus-1/summary.csv
  performance/benchmarks/cpus-1/summary.md
  performance/benchmarks/cpus-2/images/diagram.png
  performance/benchmarks/cpus-2/images/percentile.png
  performance/benchmarks/cpus-2/images/response_time_0ms.png
  performance/benchmarks/cpus-2/images/throughput.png
  performance/benchmarks/cpus-2/summary.csv
  performance/benchmarks/cpus-2/summary.md
  performance/benchmarks/inteceptor/images/inteceptorDiagram.png
  performance/benchmarks/inteceptor/summary.md
Labels: Type/Task

#2479 Updating Architecture diagram
  Architecture.png
Labels: Type/Task

#2482 Fix minor formatting issues
  adapter/internal/api/apis_impl.go
Labels: Type/Task

#2481 Use provided method to directly access resource config and remove loop
  adapter/internal/oasparser/operator/operator.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/PublisherUtils.java
Labels: Type/Improvement

#2491 Run tests if the workflow is manually triggered
  .github/workflows/nightly-integration-test.yml
Labels: Type/Task

#2476 [Improvement] [Analytics] Showing application usage when subscription is disabled.
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
Labels: Type/Improvement

#2490 Updating root readme
  README.md
Labels: Type/Task

#2488 Updating azure tracing for beta 5
  .trivyignore
  adapter/internal/oasparser/envoyconf/listener.go
  enforcer-parent/enforcer/pom.xml
  pom.xml
  resources/conf/config.toml.template
Labels: Type/Task

#2489 [bug-fix] Fixes un-deploying an API deployed to multiple labels form APICTL
  adapter/internal/discovery/xds/server.go
Labels: Type/Bug

#2496 Only depend on tier in APIConfig which represents apiTier
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/AuthenticationContext.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/dto/APIKeyValidationInfoDTO.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/WebSocketHandler.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketMetaDataFilter.java
Labels: Type/Improvement
