Repository wso2/product-microgateway, pull requests merged in 2021-04, with the labels that each got.

#1795 Adding k8s artifacts for router+enforcer in sidecar mode.
  resources/k8s-artifacts/mg-adapter/config-toml-configmap.yaml
  resources/k8s-artifacts/mg-adapter/deployment.yaml
  resources/k8s-artifacts/mg-adapter/log4j2-configmap.yaml
  resources/k8s-artifacts/mg-deployment/deployment.yaml
  resources/k8s-artifacts/mg-deployment/enforcer-keystore-secret.yaml
  resources/k8s-artifacts/mg-deployment/enforcer-truststore-secret.yaml
  resources/k8s-artifacts/mg-deployment/router-keystore-secret.yaml
  resources/k8s-artifacts/mg-deployment/router-truststore-secret.yaml
  resources/k8s-artifacts/mg-deployment/service.yaml
  resources/k8s-artifacts/mg-enforcer/service.yaml
  resources/k8s-artifacts/mg-router/deployment.yaml
Labels: Type/Improvement

#1801 Fix #1800 - Enforcer reconnect after adapter restart
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/EnvVarConfig.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/Constants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApiDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApiListDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApplicationDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApplicationKeyMappingDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/KeyManagerDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/RevokedTokenDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/SubscriptionDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ThrottleDataDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/scheduler/XdsSchedulerManager.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/util/GRPCUtils.java
Labels: Type/Bug, envoy-gw

#1812 Retrieve throttling data from adapter via tdds
  adapter/internal/discovery/api/wso2/discovery/throttle/blocking_conditions.pb.go
  adapter/internal/discovery/api/wso2/discovery/throttle/throttle_data.pb.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/messaging/event_types.go
  adapter/internal/messaging/listener.go
  adapter/internal/messaging/throttle_data_listener.go
  adapter/internal/synchronizer/throttle_data_fetcher.go
  adapter/internal/synchronizer/types.go
  api/wso2/discovery/throttle/blocking_conditions.proto
  api/wso2/discovery/throttle/throttle_data.proto
  enforcer/src/main/gen/org/wso2/gateway/discovery/throttle/BlockingConditions.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/throttle/BlockingConditionsOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/throttle/BlockingConditionsProto.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/throttle/ThrottleData.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/throttle/ThrottleDataOrBuilder.java
  enforcer/src/main/gen/org/wso2/gateway/discovery/throttle/ThrottleDataProto.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/APIConstants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ThrottleDataDiscoveryClient.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleConstants.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleDataHolder.java
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleEventListener.java
  resources/conf/config.toml
Labels: Priority/High, Type/Improvement, envoy-gw

#1809 provide enable/disable option for router accesslog configurations
  adapter/config/log_types.go
  adapter/internal/oasparser/envoyconf/listener.go
  resources/conf/log_config.toml
  resources/k8s-artifacts/mg-adapter/logconfig-toml-configmap.yaml
Labels: Type/Improvement, envoy-gw

#1815 Update APIM base docker image
  enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleEventListener.java
  integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/apim/APIMLifecycleBaseTest.java
  pom.xml
  resources/apim/conf/deployment.toml
  resources/apim/docker-compose.yaml
  resources/conf/log4j2.properties
  resources/k8s-artifacts/apim/apim-config.yaml
  resources/k8s-artifacts/apim/apim-deployment.yaml
Labels: envoy-gw

#1808 Release prep for m10.
  README.md
  remove-containers.sh
  resources/apim/docker-compose.yaml
  resources/docker-compose.yaml
Labels: Type/Task

#1816 Update k8s artifacts for m10
  resources/k8s-artifacts/mg-adapter/deployment.yaml
  resources/k8s-artifacts/mg-deployment/deployment.yaml
Labels: Type/Task, envoy-gw

#1818 Fix #1817 - Debug log printing issue
  enforcer/pom.xml
  integration/test-integration/pom.xml
  pom.xml
  resources/conf/log4j2.properties
Labels: Type/Bug, envoy-gw

#1821 Fixing invokeRemoveAuthHeaderSuccessTest issue
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  integration/mock-backend-server/src/main/java/org.wso2am.micro.gw.mockbackend/MockBackEndServer.java
Labels: Type/Bug, envoy-gw

#1822 Adding log4j2 configs to k8s artifacts.
  resources/k8s-artifacts/mg-adapter/log4j2-configmap.yaml
Labels: Type/Improvement

#1824 Adding APIM beta images and bump carbon-apimgt version.
  pom.xml
  remove-containers.sh
  resources/apim/conf/deployment.toml
  resources/apim/docker-compose.yaml
  resources/docker-compose.yaml
  resources/k8s-artifacts/apim/apim-config.yaml
  resources/k8s-artifacts/apim/apim-deployment.yaml
  resources/k8s-artifacts/mg-adapter/deployment.yaml
  resources/k8s-artifacts/mg-deployment/deployment.yaml
Labels: Type/Task

#1825 Bump ballerina version
  pom.xml
Labels: Type/Task

#1827 Changes due to moving 'envoy-gw' to 'main'.
  CONTRIBUTING.md
  README.md
  integration/test-integration/pom.xml
Labels: Type/Task

#1796 Upgrade docker base images
  adapter/scripts/build.sh
  adapter/src/main/resources/Dockerfile
  enforcer/src/main/resources/Dockerfile
  resources/k8s-artifacts/choreo-connect-deployment/deployment.yaml
  router/src/main/resources/Dockerfile
Labels: Type/Improvement, Type/Task, envoy-gw

#1834 Use XdsScheduleManager for CDS
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/Backoff.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ConfigDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/scheduler/XdsSchedulerManager.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/AuthServer.java
Labels: Priority/Normal, Type/Improvement, envoy-gw

#1836 Fix IndexOutofBound Exception in the first api call with JWT generation
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
Labels: Type/Bug, envoy-gw

#1843 Fix #1842 - issue scopes with test key
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/issuer/HttpTokenServerHandler.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/issuer/HttpTokenServerInitializer.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/issuer/JWTIssuerImpl.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/apiDeploy/QSGTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/ApictlUtils.java
  integration/test-integration/src/test/resources/testng.xml
  pom.xml
Labels: Type/Bug, Type/Improvement, envoy-gw

#1845 Fix minor issues in global throttling
  adapter/internal/discovery/xds/server.go
  adapter/internal/messaging/notification_listener.go
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/RequestHandler.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
Labels: Priority/High, Type/Bug, envoy-gw

#1841 Changing distribution structure for better user experience.
  README.md
  distribution/src/main/assembly/assembly.xml
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/APIManagerWithMgwServerInstance.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/MgwServerImpl.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/MgwServerInstance.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/ApictlUtils.java
  pom.xml
  resources/docker-compose/apim/conf/config.toml
  resources/docker-compose/apim/conf/deployment.toml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/K8S-README.md
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/adapter-keystore-secret.yaml
  resources/k8s-artifacts/choreo-connect/adapter-service.yaml
  resources/k8s-artifacts/choreo-connect/adapter-truststore-secret.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
  resources/k8s-artifacts/choreo-connect/consul-cert-secret.yaml
  resources/k8s-artifacts/choreo-connect/enforcer-keystore-secret.yaml
  resources/k8s-artifacts/choreo-connect/enforcer-truststore-secret.yaml
  resources/k8s-artifacts/choreo-connect/log4j2-configmap.yaml
  resources/k8s-artifacts/choreo-connect/logconfig-toml-configmap.yaml
  resources/k8s-artifacts/choreo-connect/mg-deployment.yaml
  resources/k8s-artifacts/choreo-connect/mg-service.yaml
  resources/k8s-artifacts/choreo-connect/router-keystore-secret.yaml
  resources/k8s-artifacts/choreo-connect/router-truststore-secret.yaml
Labels: Type/Docs, Type/Task

#1846 Fix token validation when Authorization header is malformed
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APISecurityConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/oauth/OAuthAuthenticator.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/jwtValidator/JwtTestCase.java
Labels: Type/Bug

#1850 Handle deletion of blocking conditions
  adapter/internal/messaging/throttle_data_listener.go
Labels: Priority/Normal, Type/Bug, envoy-gw

#1852 Fixing issue in api invocation with invalid JWT
  adapter/internal/synchronizer/keymanagers_fetcher.go
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/SignedJWTInfo.java
Labels: Type/Bug, envoy-gw

#1857 Bug fixes and improvements
  adapter/internal/messaging/throttle_data_listener.go
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
Labels: Priority/Normal, Type/Bug, envoy-gw

#1858 Improve logging
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/exception/DataLoadingException.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/exception/DiscoveryException.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/exception/EnforcerException.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTUtil.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
Labels: Type/Improvement

#1853 Adding License, changing distribution structure.
  LICENSE
  adapter/go.mod
  adapter/go.sum
  distribution/src/main/assembly/assembly.xml
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/APIManagerWithMgwServerInstance.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/MgwServerImpl.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/MgwServerInstance.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/ApictlUtils.java
  resources/conf/config-for-eventhub.toml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
Labels: Type/Improvement

#1854 Bug Fixes: Revision Undeployment is not working.
  adapter/internal/discovery/xds/server.go
  adapter/internal/messaging/event_types.go
  adapter/internal/messaging/notification_listener.go
Labels: Type/Bug, envoy-gw

#1860 Remove org.json from shade jar and pack json.wso2 to docker image
  enforcer/pom.xml
Labels: Type/Task, envoy-gw

#1859 Fixing Router image runs as non root user
  router/src/main/resources/Dockerfile
Labels: Type/Bug, envoy-gw

#1862 Update README.md
  README.md
Labels: envoy-gw

#1861 Adding a release note for Alpha.
  release-note.html
Labels: Type/Task

#1864 Improving info logs for connection retry
  adapter/internal/messaging/connection.go
Labels: Type/Improvement, envoy-gw

#1863 Release prep for alpha.
  adapter/LICENSE.txt
  adapter/resources/license.txt
  adapter/src/main/assembly/assembly.xml
  adapter/src/main/resources/Dockerfile
  distribution/src/main/assembly/assembly.xml
  enforcer/LICENSE.txt
  enforcer/src/main/assembly/assembly.xml
  enforcer/src/main/resources/Dockerfile
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/mg-deployment.yaml
Labels: Type/Task

#1866 Adding README.md to the distribution.
  distribution/src/main/assembly/assembly.xml
Labels: Type/Task

#1868 Dev iteration for beta.
  remove-containers.sh
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/mg-deployment.yaml
Labels: Type/Task

#1867 Adding retry interval logs for every attempt when adapter connection retry happens with control plane
  adapter/internal/messaging/connection.go
Labels: Type/Improvement

#1871 Add docker base image upgrade command to router Dockerfile
  enforcer/src/main/resources/Dockerfile
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-service.yaml
  router/src/main/resources/Dockerfile
Labels: Type/Task

#1873 Enabling default CORS + tweak configs to work with APIM.
  distribution/src/main/assembly/assembly.xml
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCaseBefore/MgwWithBackendTls.java
  integration/test-integration/src/test/resources/cors/cors-disabled-config.toml
  resources/conf/config-for-eventhub.toml
  resources/conf/config.toml
  resources/docker-compose/apim/conf/deployment.toml
  resources/k8s-artifacts/apim/apim-config.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
Labels: Type/Improvement

#1874 Release prep for alpha2.
  distribution/src/main/assembly/assembly.xml
  enforcer/LICENSE.txt
  release-note.html
  remove-containers.sh
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#1878 Prep for next development iteration.
  remove-containers.sh
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#1869 Adding www-authenticate header to auth failures
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/Authenticator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/UnsecuredAPIAuthenticator.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/jwtValidator/JwtTestCase.java
Labels: Type/Improvement, envoy-gw

#1884 Bring in java SPI to resolve customJWTTransformer
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTUtil.java
  enforcer/src/main/resources/Dockerfile
  integration/test-integration/src/main/resources/META-INF/services/org.wso2.carbon.apimgt.common.gateway.jwttransformer.JWTTransformer
Labels: Type/Improvement, envoy-gw

#1886 Bug Fixes: Routes are not matched when wildcard / path with suffix prefix are used.
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
Labels: Type/Bug, envoy-gw

#1892 Fixes issues when used with tenants
  adapter/internal/messaging/notification_listener.go
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationPolicyDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionPolicyDiscoveryClient.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/scheduler/XdsSchedulerManager.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/models/Application.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/models/Policy.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/models/SubscriptionPolicy.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/subscription/SubscriptionDataStore.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/subscription/SubscriptionDataStoreImpl.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/subscription/SubscriptionDataStoreUtil.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
Labels: Type/Bug, envoy-gw

#1826 Vhost support for deployments
  .github/workflows/main.yml
  adapter/config/parser.go
  adapter/config/types.go
  adapter/internal/adapter/adapter.go
  adapter/internal/api/apis_impl.go
  adapter/internal/api/models/api_meta_list_item.go
  adapter/internal/api/models/error.go
  adapter/internal/api/models/error_list_item.go
  adapter/internal/api/project_parser.go
  adapter/internal/api/restserver/config_restapi.go
  adapter/internal/api/restserver/embedded_spec.go
  adapter/internal/api/restserver/operations/api_individual/delete_apis_parameters.go
  adapter/internal/api/restserver/operations/api_individual/delete_apis_urlbuilder.go
  adapter/internal/api/types.go
  adapter/internal/discovery/api/wso2/discovery/api/api.pb.go
  adapter/internal/discovery/protocol/cache/v3/resource.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/discovery/xds/server_test.go
  adapter/internal/discovery/xds/server_utils.go
  adapter/internal/discovery/xds/server_utils_test.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/internal_dtos.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/listener_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/internal/synchronizer/types.go
  adapter/resources/adapterAPI.yaml
  api/wso2/discovery/api/api.proto
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/Api.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiProto.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/APIFactory.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/config/APIConfig.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/APIMLifecycleBaseTest.java
  resources/conf/config.toml
Labels: Type/New Feature, envoy-gw

#1881 [Adapter] Fix ordering of resources
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/resource.go
  adapter/internal/oasparser/model/resource_test.go
  adapter/internal/oasparser/model/swagger.go
Labels: Priority/Normal, Type/Improvement

#1896 Fix #1895 - Rename eventhub config
  adapter/config/types.go
  adapter/internal/adapter/adapter.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/am_credentials.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/analytics.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/binary_publisher.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/cache.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/cert.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/claim_mapping.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/config.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/event_hub.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/issuer.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/jms_connection_params.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/jwt_generator.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/jwt_issuer.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/jwt_user.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/security.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/service.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/thread_pool.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/throttle_agent.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/throttle_publisher_pool.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/throttling.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/tm_url_group.pb.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/eventhub/subscription.go
  adapter/internal/messaging/connection.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/internal/synchronizer/keymanagers_fetcher.go
  adapter/internal/synchronizer/revoked_tokens_fetcher.go
  adapter/internal/synchronizer/throttle_data_fetcher.go
  api/wso2/discovery/config/enforcer/config.proto
  api/wso2/discovery/config/enforcer/event_hub.proto
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/Config.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/ConfigOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/ConfigProto.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/EnforcerConfig.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/dto/EventHubConfigurationDto.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/keymgt/KeyManagerHolder.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/RevokedJWTDataHolder.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/subscription/SubscriptionDataStoreImpl.java
  integration/test-integration/src/test/resources/apim/config.toml
  integration/test-integration/src/test/resources/cors/cors-disabled-config.toml
  integration/test-integration/src/test/resources/jwtGenerator/config.toml
  resources/conf/config-for-eventhub.toml
  resources/conf/config.toml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
Labels: Type/Task, envoy-gw

#1883 Make analytics publishing extensible
  adapter/config/parser.go
  adapter/config/types.go
  adapter/go.mod
  adapter/go.sum
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/api/wso2/discovery/api/api.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/analytics.pb.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/model/mgw_swagger.go
  api/wso2/discovery/api/api.proto
  api/wso2/discovery/config/enforcer/analytics.proto
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/Api.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiProto.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/Analytics.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/AnalyticsOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/AnalyticsProto.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsEventPublisher.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoAnalyticsProvider.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/DefaultAnalyticsEventPublisher.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/config/APIConfig.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/dto/AnalyticsDTO.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/AnalyticsConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/MetadataConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTUtil.java
  enforcer/src/main/resources/Dockerfile
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Constants.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockAnalyticsServer.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackEndServer.java
  integration/test-integration/pom.xml
  integration/test-integration/src/main/java/org/wso2/choreo/connect/tests/CustomAnalyticMetricBuilder.java
  integration/test-integration/src/main/java/org/wso2/choreo/connect/tests/CustomAnalyticsMetric.java
  integration/test-integration/src/main/java/org/wso2/choreo/connect/tests/CustomMetricReporter.java
  integration/test-integration/src/main/java/org/wso2/choreo/connect/tests/utils/HttpClient.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/APIMWithMgwBaseTest.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/APIManagerWithMgwServerInstance.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCaseBefore/APIManagerInitializeTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/subscription/SubscriptionValidationTestCase.java
  integration/test-integration/src/test/resources/apim/config.toml
  integration/test-integration/src/test/resources/backend-service-tls.yaml
  integration/test-integration/src/test/resources/backend-service.yaml
  resources/conf/config-for-eventhub.toml
  resources/conf/config.toml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
Labels: Type/Improvement, envoy-gw

#1899 Health check for Adapter and Enforcer
  .github/workflows/main.yml
  adapter/config/types.go
  adapter/internal/adapter/adapter.go
  adapter/internal/api/restserver/config_restapi.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/health/api/wso2/health/service/health.pb.go
  adapter/internal/health/api/wso2/health/service/health_grpc.pb.go
  adapter/internal/health/controlplane.go
  adapter/internal/health/health.go
  adapter/internal/messaging/listener.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/loggers/logger.go
  adapter/pom.xml
  adapter/src/main/assembly/assembly.xml
  adapter/src/main/resources/Dockerfile
  adapter/src/main/resources/check_health.sh
  api/wso2/health/service/health.proto
  enforcer/pom.xml
  enforcer/src/main/assembly/assembly.xml
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/health/Health.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/health/HealthCheckRequest.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/health/HealthCheckRequestOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/health/HealthCheckResponse.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/health/HealthCheckResponseOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/health/HealthGrpc.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/health/HealthProto.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/HealthService.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/AuthServer.java
  enforcer/src/main/resources/Dockerfile
  enforcer/src/main/resources/check_health.sh
  integration/test-integration/src/test/resources/apim/config.toml
  integration/test-integration/src/test/resources/cors/cors-disabled-config.toml
  integration/test-integration/src/test/resources/jwtGenerator/config.toml
  pom.xml
  resources/conf/config-for-eventhub.toml
  resources/conf/config.toml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
Labels: Type/Improvement, envoy-gw

#1912 Fix #1870 #1897 - Blocked API issue
  adapter/internal/discovery/api/wso2/discovery/subscription/api.pb.go
  adapter/internal/discovery/api/wso2/discovery/subscription/api_list.pb.go
  adapter/internal/discovery/api/wso2/discovery/subscription/application.pb.go
  adapter/internal/discovery/api/wso2/discovery/subscription/application_key_mapping.pb.go
  adapter/internal/discovery/api/wso2/discovery/subscription/application_key_mapping_list.pb.go
  adapter/internal/discovery/api/wso2/discovery/subscription/application_list.pb.go
  adapter/internal/discovery/api/wso2/discovery/subscription/application_policy.pb.go
  adapter/internal/discovery/api/wso2/discovery/subscription/application_policy_list.pb.go
  adapter/internal/discovery/api/wso2/discovery/subscription/subscription.pb.go
  adapter/internal/discovery/api/wso2/discovery/subscription/subscription_list.pb.go
  adapter/internal/discovery/api/wso2/discovery/subscription/subscription_policy.pb.go
  adapter/internal/discovery/api/wso2/discovery/subscription/subscription_policy_list.pb.go
  adapter/internal/discovery/api/wso2/discovery/subscription/url_mapping.pb.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/eventhub/types/types.go
  adapter/internal/messaging/notification_listener.go
  api/wso2/discovery/subscription/api.proto
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/subscription/APIs.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/subscription/APIsOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/subscription/APIsProto.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/GeneralErrorCodeConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/models/API.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/subscription/SubscriptionDataStoreImpl.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/APIMLifecycleBaseTest.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/apim/BlockedAPITestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/apim/SubscriptionValidationTestCase.java
  integration/test-integration/src/test/resources/testng.xml
Labels: Type/Bug, envoy-gw

#1904 Bug fixes
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/swagger_test.go
Labels: Type/Bug, envoy-gw

#1910 Introducing ingress to the k8s artifacts.
  distribution/src/main/assembly/assembly.xml
  resources/k8s-artifacts/apim/apim-config.yaml
  resources/k8s-artifacts/apim/apim-deployment.yaml
  resources/k8s-artifacts/choreo-connect/adapter-service.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-ingress-tls-secret.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-ingress.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-service.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-with-apim-ingress.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
Labels: Type/Improvement

#1905 Adding new token issuer for APIM publisher
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/dto/ExtendedTokenIssuerDto.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
  integration/test-integration/src/test/resources/apim/config.toml
  integration/test-integration/src/test/resources/jwtGenerator/config.toml
  resources/conf/config.toml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
Labels: Type/Bug

#1900 Throttling test cases and bug fixes
  adapter/internal/adapter/adapter.go
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleDataHolder.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/APIMLifecycleBaseTest.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/APIMWithMgwBaseTest.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/APIManagerWithMgwServerInstance.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/MgwServerImpl.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/MgwServerInstance.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/listener/TestNGListener.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/apim/BlockedAPITestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/apim/SubscriptionValidationTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/apim/throttle/AdvanceThrottlingTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/apim/throttle/ApplicationThrottlingTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/apim/throttle/DenyConditionTestCasejava
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/apim/throttle/SubscriptionThrottlingTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/apim/throttle/ThrottlingBaseTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
  integration/test-integration/src/test/resources/apim/config.toml
  integration/test-integration/src/test/resources/testng.xml
Labels: Type/Bug, Type/Task

#1918 Add support for x-wso2-throttling-tier
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/model/api_operation.go
  adapter/internal/oasparser/model/constants.go
  adapter/internal/oasparser/model/mgw_swagger.go
Labels: Priority/Normal, Type/Improvement, envoy-gw

#1911 Default gateway label refactoring
  adapter/config/parser.go
  adapter/internal/adapter/adapter.go
  adapter/internal/eventhub/subscription.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/oasparser/operator/operator.go
  adapter/test-resources/envoycodegen/api.yaml
  adapter/test-resources/envoycodegen/api_prod.yaml
  adapter/test-resources/envoycodegen/api_sand.yaml
  enforcer/src/main/resources/Dockerfile
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/APIMLifecycleBaseTest.java
  integration/test-integration/src/test/resources/apim/config.toml
  integration/test-integration/src/test/resources/cors/cors-disabled-config.toml
  integration/test-integration/src/test/resources/jwtGenerator/config.toml
  pom.xml
  resources/conf/config-for-eventhub.toml
  resources/conf/config.toml
  resources/docker-compose/apim/conf/deployment.toml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/apim/apim-config.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
  router/src/main/resources/Dockerfile
Labels: Type/Task

#1908 Add Enforcer error handling and fallback implementation
  adapter/internal/adapter/adapter.go
  adapter/internal/discovery/xds/consul.go
  adapter/internal/discovery/xds/enforcer_callbacks.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/discovery/xds/state_cache.go
Labels: Type/Improvement, envoy-gw

#1914 No proper error response when the provided JWT cannot be parsed.
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/exception/APISecurityException.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer/src/main/resources/Dockerfile
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/jwtValidator/JwtTestCase.java
Labels: Type/Bug, envoy-gw

#1925 Remove copying unnecessary config files to adaptor and enforcer
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#1926 Remove copying unnecessary config files in dockerfiles
  adapter/src/main/resources/Dockerfile
  enforcer/src/main/resources/Dockerfile
Labels: Type/Task

#1927 add missing configs
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
  resources/conf/config-for-eventhub.toml
Labels: Type/Bug, Type/Improvement, envoy-gw

#1930 updating k8s artifacts.
  resources/k8s-artifacts/apim/apim-service.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
Labels: Type/Task

#1931 Updating license and prepping for release.
  enforcer/LICENSE.txt
  remove-containers.sh
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#1932 Add dependencies to root pom
  integration/test-integration/pom.xml
  pom.xml
  release-note.html
Labels: Type/Task, envoy-gw

#1939 Prep for next dev iteration.
  remove-containers.sh
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#1937 Update envoy version to 1.18.2
  adapter/config/types.go
  adapter/internal/oasparser/envoyconf/http_filters.go
  resources/conf/config-for-eventhub.toml
  resources/conf/config.toml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
  router/src/main/resources/Dockerfile
Labels: Type/Improvement, envoy-gw

#1942 Updating control plane artifacts to be compatible with APIM RC.
  pom.xml
  resources/docker-compose/apim/conf/deployment.toml
  resources/docker-compose/apim/docker-compose.yaml
  resources/k8s-artifacts/apim/apim-config.yaml
  resources/k8s-artifacts/apim/apim-deployment.yaml
Labels: Type/Task

#1943 Support web socket throttling
  adapter/go.mod
  adapter/go.sum
  adapter/internal/api/apis_impl.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/http_filters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  api/wso2/discovery/service/websocket/frame_service.proto
  enforcer/pom.xml
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/websocket/Metadata.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/websocket/MetadataOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/websocket/MgwWebSocketProto.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/websocket/WebSocketFrameRequest.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/websocket/WebSocketFrameRequestOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/websocket/WebSocketFrameResponse.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/websocket/WebSocketFrameResponseOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/websocket/WebSocketFrameServiceGrpc.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/APIFactory.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RequestContext.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/WebSocketFrameService.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/interceptors/AccessLogInterceptor.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/AuthServer.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/HttpRequestHandler.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/RequestHandler.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/WebSocketHandler.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/utils/ThrottleUtils.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/MetadataConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketFrameContext.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketMetaDataFilter.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketResponseObserver.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketThrottleFilter.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketThrottleResponse.java
  envoy-filters/mgw-api/extensions/filters/http/mgw-wasm-websocket/v3/BUILD
  envoy-filters/mgw-api/extensions/filters/http/mgw-wasm-websocket/v3/WORKSPACE
  envoy-filters/mgw-api/extensions/filters/http/mgw-wasm-websocket/v3/config.proto
  envoy-filters/mgw-api/extensions/filters/http/mgw-wasm-websocket/v3/service.proto
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/BUILD
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/WORKSPACE
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/build.sh
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/filter.cc
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/filter.h
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/handler.h
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/handler_impl.cc
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/handler_impl.h
  integration/mock-backend-server/pom.xml
  router/pom.xml
  router/src/main/assembly/assembly.xml
  router/src/main/resources/Dockerfile
Labels: Type/New Feature

#1935 Change 403 error message when enforcer is unavailable
  adapter/internal/err/errors.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/response_mapper.go
Labels: Priority/Normal, Type/Bug, envoy-gw

#1948 Bug fixes: Improve subscription validation flow [Don't Merge]
  adapter/internal/discovery/api/wso2/discovery/subscription/application_key_mapping.pb.go
  adapter/internal/discovery/api/wso2/discovery/subscription/subscription.pb.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/eventhub/subscription.go
  adapter/internal/eventhub/types/types.go
  adapter/internal/messaging/event_types.go
  adapter/internal/messaging/notification_listener.go
  api/wso2/discovery/subscription/application_key_mapping.proto
  api/wso2/discovery/subscription/subscription.proto
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/subscription/ApplicationKeyMapping.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/subscription/ApplicationKeyMappingOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/subscription/ApplicationKeyMappingProto.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/subscription/Subscription.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/subscription/SubscriptionOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/subscription/SubscriptionProto.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/models/Application.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/models/ApplicationKeyMapping.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/models/Subscription.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/subscription/SubscriptionDataStore.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/subscription/SubscriptionDataStoreImpl.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/subscription/SubscriptionDataStoreUtil.java
Labels: Type/Improvement, envoy-gw

#1949 Vhost integration tests - APICTL
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  integration/test-integration/pom.xml
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCaseBefore/BeforeTestSuite.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCaseBefore/MgwWithBackendTls.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCaseBefore/MgwWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCaseBefore/MgwWithJwtConfig.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/apiDeploy/APiDeployViaApictlTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/apiDeploy/QSGTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/vhost/VhostAPICtlTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/ApictlUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
  integration/test-integration/src/test/resources/deploymentEnvironments/apictl_test_deploy_env.yaml
  integration/test-integration/src/test/resources/deploymentEnvironments/vhost1_deploy_env.yaml
  integration/test-integration/src/test/resources/deploymentEnvironments/vhost2_deploy_env.yaml
  integration/test-integration/src/test/resources/openAPIs/vhost1_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/vhost2_openAPI.yaml
  integration/test-integration/src/test/resources/testng.xml
Labels: Type/Improvement, envoy-gw

#1950 Add router build to maven profile
  .github/workflows/main.yml
  .gitignore
  .travis.yml
  pom.xml
Labels: Type/Task, envoy-gw

#1933 Support basic auth secured backend
  adapter/config/parser.go
  adapter/config/types.go
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/am_credentials.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/analytics.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/auth_header.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/binary_publisher.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/cache.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/cert.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/claim_mapping.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/config.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/issuer.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/jms_connection_params.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/jwt_generator.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/jwt_issuer.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/jwt_user.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/security.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/service.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/thread_pool.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/throttle_agent.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/throttle_publisher_pool.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/throttling.pb.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/tm_url_group.pb.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  api/wso2/discovery/config/enforcer/auth_header.proto
  api/wso2/discovery/config/enforcer/config.proto
  api/wso2/discovery/config/enforcer/security.proto
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/ConfigProto.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/Security.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/SecurityOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/SecurityProto.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RequestContext.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/ResponseObject.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/EnforcerConfig.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/dto/AuthHeaderDto.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
  integration/test-integration/src/test/resources/apim/config.toml
  integration/test-integration/src/test/resources/cors/cors-disabled-config.toml
  integration/test-integration/src/test/resources/jwtGenerator/config.toml
  resources/conf/config-for-eventhub.toml
  resources/conf/config.toml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
Labels: Type/Bug, envoy-gw

#1951 Bug fixes: Filter events based on tenant
  adapter/config/parser.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/discovery/xds/server_utils.go
  adapter/internal/messaging/notification_listener.go
Labels: Type/Improvement, envoy-gw

#1947 removed unnecessary logs
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketMetaDataFilter.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketResponseObserver.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketThrottleFilter.java
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/filter.cc
Labels: 0.9.0-GA, Type/Task, envoy-gw

#1957 Add backend endpoint port validation
  adapter/internal/oasparser/model/mgw_swagger.go
Labels: Type/Bug, envoy-gw

#1961 Add vhost integration test for APIM
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/APIMLifecycleBaseTest.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/APIMWithMgwBaseTest.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/APIManagerWithMgwServerInstance.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCaseBefore/APIManagerInitializeTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/apim/VhostAPIMTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
  integration/test-integration/src/test/resources/apim/vhost-deployment.toml
  integration/test-integration/src/test/resources/testng.xml
Labels: test-improvements

#1967 Fix sandbox endpoint security auth header
  adapter/internal/api/apis_impl.go
Labels: Type/Bug, envoy-gw

#1970 Bug fixes
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/http_filters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/model/open_api.go
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackEndServer.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCaseBefore/MgwWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/apiDeploy/OpenAPIV3TestCase.java
  integration/test-integration/src/test/resources/openAPIs/openAPI_v3_standard_valid.yaml
  integration/test-integration/src/test/resources/testng.xml
  resources/conf/log_config.toml
Labels: 0.9.0-GA, Type/Bug, envoy-gw

#1969 Fix #1963 - API LC state block does not work for unsecured APIs
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/UnsecuredAPIAuthenticator.java
Labels: 0.9.0-GA

#1968 Keep existing environments when undeploy an API from APIM which is deployed with same vhosts
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/discovery/xds/server_test.go
Labels: Type/Bug

#1973 Updating license and release note
  enforcer/LICENSE.txt
  pom.xml
  release-note.html
Labels: Type/Task

#1974 Update APIM version
  pom.xml
Labels: Type/Task, envoy-gw

#1975 Updating apictl + APIM docker images.
  pom.xml
  resources/docker-compose/apim/docker-compose.yaml
  resources/k8s-artifacts/apim/apim-deployment.yaml
Labels: Type/Task

#1976 analytics fix: errors for tenant are not shown properly
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
Labels: Type/Bug, envoy-gw

#1978 bug fix: denied policies and analytics does not work together
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
Labels: Type/Bug, envoy-gw

#1979 Prepping RC release.
  release-note.html
  remove-containers.sh
  resources/docker-compose/apim/conf/deployment.toml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/apim/apim-config.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
Labels: Type/Task
