Repository wso2/product-microgateway, pull requests merged in 2021-05, with the labels that each got.

#1982 Update docker image and apim deployment.toml
  adapter/internal/discovery/xds/enforcer_callbacks.go
  adapter/src/main/resources/Dockerfile
  resources/docker-compose/apim/conf/deployment.toml
Labels: Type/Task, envoy-gw

#1987 Add callbacks to debug router connection
  adapter/internal/adapter/adapter.go
  adapter/internal/discovery/xds/routercallbacks/router_callbacks.go
  adapter/loggers/logger.go
Labels: envoy-gw

#1992 Improve debug logs
  adapter/internal/adapter/adapter.go
  adapter/internal/synchronizer/apis_fetcher.go
Labels: Type/Bug, envoy-gw

#1993 Add logging improvements
  adapter/internal/adapter/adapter.go
  adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
  adapter/internal/messaging/connection.go
  adapter/internal/messaging/km_listener.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/messaging/revoked_token_listener.go
  adapter/internal/synchronizer/keymanagers_fetcher.go
  adapter/loggers/logger.go
  adapter/src/main/resources/Dockerfile
  pom.xml
Labels: Type/Improvement, envoy-gw

#1995 Bump version for 0.9.0.1 patch release
  adapter/pom.xml
  distribution/pom.xml
  enforcer/pom.xml
  enforcer/src/main/resources/Dockerfile
  integration/mock-backend-server/pom.xml
  integration/pom.xml
  integration/test-integration/pom.xml
  pom.xml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  router/pom.xml
Labels: Type/Task, envoy-gw

#1996 [0.9.x] Fix integration test failure
  adapter/internal/messaging/event_types.go
  adapter/internal/messaging/km_listener.go
  adapter/internal/messaging/notification_listener.go
  adapter/pom.xml
  distribution/pom.xml
  enforcer/pom.xml
  integration/mock-backend-server/pom.xml
  integration/pom.xml
  integration/test-integration/pom.xml
  pom.xml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  router/pom.xml
Labels: Type/Bug, envoy-gw

#1990 Improve debug logs
  adapter/internal/adapter/adapter.go
  adapter/internal/synchronizer/apis_fetcher.go
Labels: Type/Bug, envoy-gw

#1998 Remove unnecessary info log in test
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/APIMWithMgwBaseTest.java
Labels: Type/Task, envoy-gw

#1997 Update jars
  enforcer/pom.xml
  pom.xml
Labels: Type/Task, envoy-gw

#2002 Update dependency
  enforcer/pom.xml
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/APIMWithMgwBaseTest.java
  pom.xml
Labels: Type/Task, envoy-gw

#2001 [main] Add Logging improvements
  adapter/internal/adapter/adapter.go
  adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
  adapter/internal/messaging/connection.go
  adapter/internal/messaging/event_types.go
  adapter/internal/messaging/km_listener.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/messaging/revoked_token_listener.go
  adapter/internal/synchronizer/keymanagers_fetcher.go
  adapter/loggers/logger.go
  enforcer/src/main/resources/Dockerfile
  pom.xml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Improvement, Type/Task, envoy-gw

#2004 Bump version for the patch tag (0.9.0.2)
  adapter/pom.xml
  distribution/pom.xml
  enforcer/pom.xml
  integration/mock-backend-server/pom.xml
  integration/pom.xml
  integration/test-integration/pom.xml
  pom.xml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  router/pom.xml
Labels: Type/Task, envoy-gw

#2005 Prepare for the next development iteration
  adapter/pom.xml
  distribution/pom.xml
  enforcer/pom.xml
  integration/mock-backend-server/pom.xml
  integration/pom.xml
  integration/test-integration/pom.xml
  pom.xml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  router/pom.xml
Labels: Type/Task, envoy-gw

#2010 Mask connection url and improve jms retry
  adapter/internal/messaging/connection.go
  adapter/internal/messaging/listener.go
Labels: Type/Bug, Type/New Feature, envoy-gw

#2013 Make internal-key configurable
  adapter/config/types.go
  adapter/internal/discovery/api/wso2/discovery/config/enforcer/auth_header.pb.go
  adapter/internal/discovery/xds/marshaller.go
  api/wso2/discovery/config/enforcer/auth_header.proto
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/AuthHeader.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/AuthHeaderOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/AuthHeaderProto.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/Security.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/SecurityOrBuilder.java
  enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/SecurityProto.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/dto/AuthHeaderDto.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  resources/conf/config-for-eventhub.toml
  resources/conf/config.toml
Labels: Type/Improvement, envoy-gw

#2015 Prepare for release 0.9.0.3
  adapter/pom.xml
  distribution/pom.xml
  enforcer/pom.xml
  integration/mock-backend-server/pom.xml
  integration/pom.xml
  integration/test-integration/pom.xml
  pom.xml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  router/pom.xml
Labels: 0.9.0.3, Type/Task

#2017 Update k8s config maps with the new enforcer configuration
  resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
Labels: 0.9.0.3, Type/Improvement, envoy-gw

#2018 Add maven settings file to allow http repositories
  .github/workflows/main.yml
  .maven/settings.xml
  enforcer/pom.xml
  integration/test-integration/pom.xml
  pom.xml
Labels: Type/Task

#2023 Update nimbus.jose.jwt version
  pom.xml
Labels: Type/Task, envoy-gw

#2026 Revert XDS Cache fallback on enforcer NACK message.
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
  adapter/internal/discovery/xds/server.go
Labels: Choreo, Type/Bug, envoy-gw

#2021 Fix the slf4j binding issue
  enforcer/pom.xml
  pom.xml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Choreo, Type/Bug, envoy-gw

#2028 Update json-smart version
  pom.xml
Labels: Type/Task, envoy-gw
