Repository wso2/product-microgateway, pull requests merged in 2022-11, with the labels that each got.

#3131 Parse JWT payload with JSON parser during JWT based throttle validations
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleDataHolder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/utils/ThrottleUtils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketThrottleFilter.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/JwtTestCase.java
Labels: Type/Bug

#3133 Custom Analytics Data Provider Support
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/oasparser/envoyconf/access_loggers.go
  codecov.yml
  dev-scripts/code-coverage/prepare-files-before-int-tests.sh
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsUtils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoAnalyticsProvider.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/DefaultAnalyticsEventPublisher.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/AnalyticsConstants.java
  pom.xml
  resources/conf/config.toml.template
  samples/analytics-custom-data-provider/README.md
  samples/analytics-custom-data-provider/pom.xml
  samples/analytics-custom-data-provider/src/main/java/org/wso2/carbon/apimgt/gateway/sample/publisher/CustomDataProvider.java
Labels: Type/Task, Priority/Normal

#3122 Enforcer truststore should trust ca root certs
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/EnvVarConfig.java
Labels: Type/Improvement, Choreo

#3136 Added woodstox-core as a direct dependency
  pom.xml
Labels: Choreo

#3137 Forward the authorization header to backend if the authentication is disabled at the gateway level
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/extensions/DisableSecurityTestCase.java
  integration/test-integration/src/test/resources/openAPIs/disable_security_openAPI.yaml
Labels: Type/Task, Choreo

#3135 Fix for error in getHeaders method
  components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Entity.java
Labels: Type/Bug

#3141 JWKS endpoint for validating backend JWTs
  adapter/config/default_config.go
  adapter/config/parser.go
  adapter/config/types.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/pkg/discovery/api/wso2/discovery/config/enforcer/jwt_generator.pb.go
  adapter/pkg/discovery/api/wso2/discovery/config/enforcer/keypair.pb.go
  api/proto/wso2/discovery/config/enforcer/jwt_generator.proto
  api/proto/wso2/discovery/config/enforcer/keypair.proto
  developer-guide.md
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/JWTGenerator.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/JWTGeneratorOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/JWTGeneratorProto.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/KeyPairProto.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/Keypair.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/KeypairOrBuilder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/admin/AdminServerInitializer.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/EnforcerConfig.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/JwtConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/jwks/BackendJWKSDto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/jwks/JWKSRequestHandler.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/issuer/HttpTokenServerHandler.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/issuer/HttpTokenServerInitializer.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/RestServer.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/RestServerInitializer.java
  enforcer-parent/enforcer/src/test/java/org/wso2/choreo/connect/enforcer/backend/jwt/BackendJwksTest.java
  enforcer-parent/enforcer/src/test/java/org/wso2/choreo/connect/enforcer/backend/jwt/BackendJwtTest.java
  enforcer-parent/enforcer/src/test/resources/keystore/mg.key
  enforcer-parent/enforcer/src/test/resources/keystore/mg.pem
  enforcer-parent/enforcer/src/test/resources/keystore/multipleCerts/cert.pem
  enforcer-parent/enforcer/src/test/resources/keystore/multipleCerts/mg.pem
  enforcer-parent/enforcer/src/test/resources/keystore/singleCert/cert.pem
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtGenerator/JwtGeneratorTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/EnforcerAPITestCase.java
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  router/src/main/resources/Dockerfile
  router/src/main/resources/Dockerfile.ubuntu
Labels: Type/New Feature

#3145 Moving from slack to Discord
  .github/ISSUE_TEMPLATE/config.yml
Labels: Type/Task
