Repository wso2/product-microgateway, pull requests merged in 2022-01, with the labels that each got.

#2599 Bump log4j-api from 2.16.0 to 2.17.1
  pom.xml
Labels: Type/Task, Priority/Normal

#2600 Prepare for 1.0.0-rc3 release
  integration/mock-backend-server/pom.xml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  release-note.html
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task, Priority/Normal

#2605 Prepare for next development iteration - 1.1.0-m1-SNAPSHOT
  adapter/pom.xml
  distribution/pom.xml
  enforcer-parent/commons/pom.xml
  enforcer-parent/enforcer/pom.xml
  enforcer-parent/pom.xml
  integration/mock-backend-server/pom.xml
  integration/pom.xml
  integration/test-integration/pom.xml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  pom.xml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  router/pom.xml
Labels: Type/Task

#2601 Bump go openapi strfmt version
  adapter/go.mod
  adapter/go.sum
Labels: Type/Task

#2602 Add operation level interceptor support
  adapter/internal/interceptor/interceptor.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/internal_dtos.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/model/api_operation.go
  adapter/internal/oasparser/model/constants.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api_internal_test.go
  adapter/internal/oasparser/model/swagger_internal_test.go
  integration/test-integration/src/test/resources/openAPIs/intercept_request_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/intercept_response_openAPI.yaml
  router/src/main/resources/interceptor/lib/interceptor.lua
Labels: Type/Improvement

#2579 Resolve issue with SSL Binary Throttle Data Publishing
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/endpoint/DataEndpointGroup.java
Labels: Type/Bug, ballerina-mgw

#2607 Fixing a goroutine creation for handling API events from GA .
  adapter/internal/ga/client.go
Labels: Type/Bug

#2597 Migrate ASB client to azure-sdk-for-go
  .github/workflows/main.yml
  .github/workflows/nightly-integration-test.yml
  adapter/go.mod
  adapter/go.sum
  adapter/internal/messaging/azure_listener.go
  adapter/pkg/messaging/azure_connection.go
  adapter/pkg/messaging/azure_listener.go
Labels: Type/Improvement, Priority/Normal

#2630 Move constants to a seperate package
  adapter/internal/api/apis_impl.go
  adapter/internal/api/restserver/config_restapi.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/constants/constants.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/mgw_swagger_internal_test.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/resource.go
  adapter/internal/oasparser/model/swagger.go
  adapter/internal/oasparser/model/swagger_test.go
  adapter/internal/oasparser/model/types.go
  adapter/internal/oasparser/operator/operator_test.go
Labels: Type/Task

#2611 int-tests: Add an interceptor test for apim mode
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/PublisherUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/StoreUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/CcInstance.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/ChoreoConnectImpl.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/withapim/CcStartupExecutorTwo.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/InterceptorWithMtlsTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
  integration/test-integration/src/test/resources/certs/ca-certificates.crt
  integration/test-integration/src/test/resources/configs/cc-special-scenarios-with-apim.toml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
  integration/test-integration/src/test/resources/openAPIs/intercept_request_path_level_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Type/Task, test-improvements

#2626 Update maven settings.xml
  .maven/settings.xml
Labels: Type/Improvement

#2619 Init support mediation operational policies
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/constants/constants.go
  adapter/internal/oasparser/envoyconf/internal_dtos.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/model/api_operation.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api_internal_test.go
  adapter/internal/oasparser/model/resource.go
  adapter/internal/oasparser/model/swagger_internal_test.go
  adapter/internal/oasparser/model/types.go
  adapter/pkg/discovery/api/wso2/discovery/api/Resource.pb.go
  api/proto/wso2/discovery/api/Resource.proto
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/Policy.java
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/PolicyConfig.java
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/RequestContext.java
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/ResourceConfig.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/Operation.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/OperationOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/OperationPolicies.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/OperationPoliciesOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/Policy.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/PolicyOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ResourceProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/ResponseObject.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/MediationPolicyFilter.java
Labels: Type/New Feature

#2637 Fix rename header policy
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/MediationPolicyFilter.java
Labels: Type/Bug

#2636 [3.2.x] Upgrade ballerina version to 1.2.24
  pom.xml
Labels: ballerina-mgw

#2639 Upgrade grpc.protobuf.version
  pom.xml
Labels: Type/Task

#2624 int-tests: Update existing ApimPreparer to read ApiRequests from jsons
  integration/test-integration/README.md
  integration/test-integration/readme.md
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/ApimResourceProcessor.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/dto/Api.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/PublisherUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/withapim/ApimClientsPreparer.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/withapim/ApimPreparer.java
  integration/test-integration/src/test/resources/apim/1/apiToVhosts.json
  integration/test-integration/src/test/resources/apim/1/apis/AdvancedThrottlingApi.json
  integration/test-integration/src/test/resources/apim/1/apis/ApplicationThrottlingApi.json
  integration/test-integration/src/test/resources/apim/1/apis/BlockedApi.json
  integration/test-integration/src/test/resources/apim/1/apis/EndpointWithTrailingSlashAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/ExistingApi.json
  integration/test-integration/src/test/resources/apim/1/apis/SubscriptionValidationApi.json
  integration/test-integration/src/test/resources/apim/1/apis/VHostAPI1.json
  integration/test-integration/src/test/resources/apim/1/apis/VHostAPI2.json
  integration/test-integration/src/test/resources/apim/1/apps/applications.json
  integration/test-integration/src/test/resources/apim/1/subscriptions/subscriptions.json
  integration/test-integration/src/test/resources/apimApisAppsSubs/apis.json
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Type/Task, test-improvements

#2633 Formalizing Error Logs in enforcer & adapter
  adapter/cmd/adapter/main.go
  adapter/go.mod
  adapter/go.sum
  adapter/internal/loggers/logger.go
  adapter/internal/messaging/messaging_test.go
  adapter/internal/messaging/revoked_token_listener.go
  adapter/pkg/config/log_types.go
  adapter/pkg/loggers/logger.go
  adapter/pkg/logging/log_constants.go
  adapter/pkg/logging/log_format.go
  adapter/pkg/logging/logging_internal_test.go
  adapter/pkg/logging/package_logs.go
  adapter/pkg/logging/root_logs.go
  enforcer-parent/commons/pom.xml
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/logging/CustomJsonLayout.java
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/logging/ErrorDetails.java
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/logging/ErrorLogPatternConverter.java
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/logging/LoggingConstants.java
  resources/conf/log4j2.properties
  resources/conf/log_config.toml
Labels: Type/Improvement, Priority/Normal

#2643 Fix being able to override an API without the override flag via apictl
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/server.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/APiDeployViaApictlTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/ApictlUtils.java
Labels: Type/Bug

#2644 Preparations for 1.1.0-m1 release
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  remove-containers.sh
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task
