Repository wso2/product-microgateway, pull requests merged in 2022-05, with the labels that each got.

#2903 Renaming config file
  .github/ISSUE_TEMPLATE/config.yml
Labels: Type/Task

#2875 Directory structure maker script addition.
  dev-scripts/directory-structure-maker/directory-structure-maker.md
  dev-scripts/directory-structure-maker/directory-structure-maker.sh
  dev-scripts/remove-containers.sh
  developer-guide.md
  pom.xml
Labels: Type/Task, Priority/Normal

#2907 Add organizationID=ALL query parameter to all the control plane requests
  adapter/internal/adapter/adapter.go
  adapter/internal/common/constants.go
  adapter/internal/eventhub/subscription.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/internal/synchronizer/keymanagers_fetcher.go
  adapter/internal/synchronizer/revoked_tokens_fetcher.go
  adapter/internal/synchronizer/throttle_data_fetcher.go
  adapter/pkg/adapter/adapter.go
  adapter/pkg/synchronizer/apis_fetcher.go
Labels: Type/Task, Choreo

#2914 Exclude sources and javadoc jars in enforcer container
  enforcer-parent/enforcer/src/main/assembly/assembly.xml
Labels: Type/Task

#2909 Removed unused swagger-parser and added javax-validation directly to enforcer
  enforcer-parent/enforcer/pom.xml
  pom.xml
Labels: Type/Task

#2916 Update interceptor open API file name by appending version
  resources/interceptor-service-open-api-v1.yaml
Labels: Type/Task

#2913 Apache Tomcat dependency version upgrades
  pom.xml
Labels: Type/Task

#2682 Change the REST API Request process
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/adapter/adapter.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/pkg/adapter/adapter.go
  adapter/pkg/synchronizer/apis_fetcher.go
  adapter/pkg/synchronizer/client_pool.go
  resources/conf/config.toml.template
Labels: Type/Task, Choreo

#2878 [main] Update fix for trailing stash and add tests
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithMultipleEnv.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/StandaloneBeforeTestSuite.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/AllHttpMethodsForWildcardTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/DefaultVersionApiTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/TrailingSlashTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apipolicy/APIPolicyTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
  integration/test-integration/src/test/resources/openAPIs/all_http_methods_for_wildcard_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/trailing_slash_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
Labels: Type/Task

#2915 Refactor error logs
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/swagger.go
Labels: Type/Improvement, Type/Task, Choreo

#2925 Exclude commons-fileupload in org.wso2.carbon.apimgt.common.jms dependency
  pom.xml
Labels: Type/Task

#2923 [choreo] Add config for revision update success call
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/notifier/deployment_notifier.go
  adapter/internal/synchronizer/apis_fetcher.go
  resources/conf/config.toml.template
Labels: Type/Improvement, Choreo

#2926 [choreo] Fix revision call
  adapter/internal/synchronizer/apis_fetcher.go
Labels: Type/Improvement, Choreo

#2882 Support enabling elk analytics from enforcer config
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/pkg/discovery/api/wso2/discovery/config/enforcer/analytics.pb.go
  api/proto/wso2/discovery/config/enforcer/analytics.proto
  enforcer-parent/enforcer/pom.xml
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/Analytics.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/AnalyticsOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/AnalyticsProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/DefaultAnalyticsEventPublisher.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/dto/AnalyticsDTO.java
  pom.xml
  resources/conf/config.toml.template
Labels: Type/Task

#2885 Change azure-sdk-for-go version to 0.4.0 and go version to be 1.18
  .github/workflows/main.yml
  adapter/go.mod
  adapter/go.sum
  adapter/internal/messaging/azure_listener.go
  adapter/pkg/messaging/azure_connection.go
  adapter/pkg/messaging/azure_listener.go
  adapter/scripts/build.sh
  developer-guide.md
Labels: Type/Task

#2928 Refactor error logs
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/model/common.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/swagger.go
Labels: Type/Improvement

#2920 Add config for revision update success call
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/notifier/deployment_notifier.go
  adapter/internal/synchronizer/apis_fetcher.go
  resources/conf/config.toml.template
Labels: Type/Improvement

#2899 Updating container base images and maven dependancies
  adapter/go.mod
  adapter/go.sum
  adapter/src/main/resources/Dockerfile
  adapter/src/main/resources/Dockerfile.ubuntu
  enforcer-parent/enforcer/src/main/resources/Dockerfile
  enforcer-parent/enforcer/src/main/resources/Dockerfile.ubuntu
  pom.xml
Labels: Type/Task, Choreo

#2924 Merging Feature/trailing slash branch with main
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithMultipleEnv.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/StandaloneBeforeTestSuite.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/AllHttpMethodsForWildcardTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/DefaultVersionApiTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/TrailingSlashTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apipolicy/APIPolicyTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
  integration/test-integration/src/test/resources/openAPIs/all_http_methods_for_wildcard_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/trailing_slash_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
Labels: Type/Improvement

#2889 Log Improvement to link adapter with the connected enforcer/router
  adapter/internal/discovery/xds/common/utils.go
  adapter/internal/discovery/xds/common/utils_test.go
  adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
  adapter/internal/discovery/xds/routercallbacks/router_callbacks.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/EnvVarConfig.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/AdapterConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiListDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationKeyMappingDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationPolicyDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ConfigDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/KeyManagerDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/RevokedTokenDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionPolicyDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ThrottleDataDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/common/XDSCommonUtils.java
  router/src/main/resources/Dockerfile
  router/src/main/resources/Dockerfile.ubuntu
Labels: Type/Improvement

#2930 gRPC health probe version upgrade
  pom.xml
Labels: Type/Task

#2940 Fix subsequent dynamic endpoint calls fail after the first one
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Constants.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackend2.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockServices.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/ResponseConstants.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/interceptor/InterceptorRequestFlowTestcase.java
  integration/test-integration/src/test/resources/openAPIs/api_policy_intercept_request_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/intercept_request_openAPI.yaml
  router/src/main/assembly/assembly.xml
  router/src/main/resources/interceptor/README.md
  router/src/main/resources/interceptor/lib/consts.lua
  router/src/main/resources/interceptor/lib/interceptor.lua
  router/src/main/resources/interceptor/lib/utils.lua
Labels: Type/Bug

#2937 Dependancy Upgrades for choreo branch
  adapter/go.mod
  adapter/go.sum
  adapter/src/main/resources/Dockerfile
  adapter/src/main/resources/Dockerfile.ubuntu
  enforcer-parent/enforcer/src/main/resources/Dockerfile
  enforcer-parent/enforcer/src/main/resources/Dockerfile.ubuntu
  pom.xml
Labels: Type/Task, Choreo

#2942 Adapter does not start if APIM responds with 204 status code
  adapter/internal/adapter/adapter.go
  adapter/pkg/synchronizer/apis_fetcher.go
Labels: Type/Bug

#2943 Fixes for oss index usage in dependency scan plugin
  enforcer-parent/pom.xml
  integration/pom.xml
  pom.xml
Labels: Type/Task

#2945 Bump ubuntu nighly build workflow go version
  .github/workflows/nightly-integration-test.yml
Labels: Type/Task

#2876 Log Improvement to link adapter with the connected enforcer/router
  adapter/internal/discovery/xds/common/utils.go
  adapter/internal/discovery/xds/common/utils_test.go
  adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
  adapter/internal/discovery/xds/routercallbacks/router_callbacks.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/EnvVarConfig.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/AdapterConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiListDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationKeyMappingDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationPolicyDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ConfigDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/KeyManagerDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/RevokedTokenDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionPolicyDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ThrottleDataDiscoveryClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/common/XDSCommonUtils.java
  router/src/main/resources/Dockerfile
  router/src/main/resources/Dockerfile.ubuntu
Labels: Type/Improvement
