Repository wso2/product-microgateway, pull requests merged in 2022-03, with the labels that each got.

#2663 int-tests: Add mock websocket server, client, and a basic testcase
  integration/mock-backend-server/pom.xml
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Constants.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendProd.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendSandbox.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockServices.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Utils.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/async/MockAsyncServer.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/async/websocket/WsServerFrameHandler.java
  integration/test-integration/pom.xml
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/ApimResourceProcessor.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/PublisherUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/websocket/WebSocketBasicTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/ApictlUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/websocket/WsClient.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/websocket/WsClientHandler.java
  integration/test-integration/src/test/resources/apim/1/apiToAsyncAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/WebSocketBasicAPI.json
  integration/test-integration/src/test/resources/apim/1/apps/applications.json
  integration/test-integration/src/test/resources/apim/1/subscriptions/subscriptions.json
  integration/test-integration/src/test/resources/asyncAPIs/websocket_basic_asyncAPI.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Type/Task, test-improvements

#2696 Analytics for Websockets
  api/proto/wso2/discovery/service/websocket/frame_service.proto
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/websocket/MgwWebSocketProto.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/websocket/WebSocketFrameRequest.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/websocket/WebSocketFrameRequestOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/websocket/WebSocketFrameResponse.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/service/websocket/WebSocketFrameResponseOrBuilder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsEventPublisher.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoAnalyticsForWSProvider.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoAnalyticsProvider.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/DefaultAnalyticsEventPublisher.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/AnalyticsConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/MetadataConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/HttpRequestHandler.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/dto/Decision.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/MetadataConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketMetaDataFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketResponseObserver.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketThrottleResponse.java
  envoy-filters/mgw-api/extensions/filters/http/mgw-wasm-websocket/v3/service.proto
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/filter.cc
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/filter.h
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/handler.h
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/handler_impl.cc
Labels: Type/Task

#2711 Operational policy improvements to align with APIM 4.1.0 beta
  adapter/internal/api/apis_process.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/model/api_operation.go
  adapter/internal/oasparser/model/api_yaml.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/policy_container.go
  adapter/internal/oasparser/model/policy_container_test.go
  adapter/internal/oasparser/model/resource.go
  adapter/pkg/discovery/api/wso2/discovery/api/Resource.pb.go
  api/proto/wso2/discovery/api/Resource.proto
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/PolicyConfig.java
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/opa/OPAConstants.java
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/opa/OPARequestGenerator.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/OperationPolicies.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/OperationPoliciesOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ResourceProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/MediationPolicyFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/opa/OPAClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/opa/OPADefaultRequestGenerator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
Labels: Type/Improvement, Priority/High

#2704 Add default version support
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/eventhub/subscription.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/internal_dtos.go
  adapter/internal/oasparser/envoyconf/listener_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/model/api_yaml.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/pkg/messaging/azure_listener.go
  adapter/pkg/messaging/event_types.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/DefaultVersionApiTestCase.java
  integration/test-integration/src/test/resources/apiYaml/default_version_v1.yaml
  integration/test-integration/src/test/resources/apiYaml/default_version_v2.yaml
  integration/test-integration/src/test/resources/openAPIs/default_version_v1_OpenAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/default_version_v2_OpenAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
Labels: Type/New Feature, Priority/High

#2717 Update log messages to include their severity levels.
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/utills/open_api_utils.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
Labels: Type/Task

#2714 Update carbon-apimgt to 4.1.0 alpha version and Update integration test apim image to 4.1.0 alpha
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/KeyManagerDiscoveryClient.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/PublisherUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/StoreUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/security/APIKeyTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/apikey/APIKeySubLevelThrottleTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/throttle/SubscriptionThrottlingTestCase.java
  integration/test-integration/src/test/resources/configs/vhost-deployment.toml
  integration/test-integration/src/test/resources/database/WSO2AM_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2CARBON_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2MB_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2METRICS_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2SHARED_DB.mv.db
  integration/test-integration/src/test/resources/dockerCompose/apim-in-common-network-docker-compose.yaml
  integration/test-integration/src/test/resources/keystore/client-truststore.jks
  integration/test-integration/src/test/resources/keystore/wso2carbon.jks
  pom.xml
  resources/adapter/security/truststore/controlplane.pem
  resources/docker-compose/apim/docker-compose.yaml
  resources/enforcer/security/truststore/wso2carbon.pem
  resources/k8s-artifacts/apim/apim-deployment.yaml
Labels: Type/Task, test-improvements

#2712 Preparations for 1.1.0-alpha release
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  remove-containers.sh
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#2720 OPA - Send token only if "sendAccessToken" is configured
  adapter/internal/oasparser/model/policy_container.go
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/opa/OPAConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/opa/OPADefaultRequestGenerator.java
Labels: Type/Improvement

#2721 Change dev version from beta to alpha2
  adapter/pom.xml
  distribution/pom.xml
  enforcer-parent/commons/pom.xml
  enforcer-parent/enforcer/pom.xml
  enforcer-parent/pom.xml
  integration/mock-backend-server/pom.xml
  integration/pom.xml
  integration/test-integration/pom.xml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  pom.xml
  remove-containers.sh
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  router/pom.xml
Labels: Type/Task

#2723 Update APIM 4.1.0 alpha certs in k8s configs
  resources/docker-compose/apim/conf/deployment.toml
  resources/docker-compose/apim/docker-compose.yaml
  resources/k8s-artifacts/apim/apim-config.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/adapter-truststore-secret.yaml
  resources/k8s-artifacts/choreo-connect/enforcer-truststore-secret.yaml
Labels: Type/Bug

#2727 Update azure-sdk-for-go asb client to 0.3.6
  adapter/go.mod
  adapter/go.sum
Labels: Type/Task

#2729 [debug/choreo-ga] Improve ASB logs
  adapter/pkg/messaging/azure_listener.go
Labels: Type/Task

#2732 [debug/choreo-ga] Revert to previous sdk version
  adapter/go.mod
  adapter/go.sum
Labels: Type/Task

#2739 Update router envoyproxy version to v1.20.2
  router/src/main/resources/Dockerfile
  router/src/main/resources/Dockerfile.ubuntu
Labels: Type/Task

#2735 Fix interceptor cluster name issue when apply with API Policies
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
Labels: Type/Bug

#2746 Add condition for filter policy events
  adapter/internal/messaging/notification_listener.go
Labels: Choreo

#2731 Add condition for filter policy events
  adapter/internal/messaging/notification_listener.go
Labels: Type/Improvement

#2748 Trim spaces in backend endpoints
  adapter/internal/oasparser/model/common.go
  adapter/internal/oasparser/model/open_api_internal_test.go
Labels: Type/Bug

#2760 Base image version upgrade
  adapter/src/main/resources/Dockerfile
  enforcer-parent/enforcer/src/main/resources/Dockerfile
Labels: Type/Task

#2759 Fix websocket compressed frames not being throttled
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketResponseObserver.java
Labels: Type/Bug

#2758 Upgrade azsb
  adapter/go.mod
  adapter/go.sum
Labels: Type/Task

#2754 API Policy Version support
  adapter/internal/api/apis_process.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/model/api_yaml.go
  adapter/internal/oasparser/model/api_yaml_test.go
  adapter/internal/oasparser/model/policy_container.go
  adapter/internal/oasparser/model/policy_container_test.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apipolicy/APIPolicyTestCase.java
  integration/test-integration/src/test/resources/apiYaml/api_policies.yaml
  integration/test-integration/src/test/resources/apiYaml/api_policy_intercept_request.yaml
  integration/test-integration/src/test/resources/apiYaml/api_policy_intercept_response.yaml
  integration/test-integration/src/test/resources/openAPIs/api_policy_openAPI.yaml
  integration/test-integration/src/test/resources/policies/addQueryParam_v1.gotmpl
  integration/test-integration/src/test/resources/policies/addQueryParam_v1.j2
  integration/test-integration/src/test/resources/policies/addQueryParam_v1.yaml
  integration/test-integration/src/test/resources/policies/ccAddHeader_v1.gotmpl
  integration/test-integration/src/test/resources/policies/ccAddHeader_v1.yaml
  integration/test-integration/src/test/resources/policies/ccCallInterceptorService_v1.gotmpl
  integration/test-integration/src/test/resources/policies/ccCallInterceptorService_v1.yaml
  integration/test-integration/src/test/resources/policies/ccChangeHTTPMethod_v1.gotmpl
  integration/test-integration/src/test/resources/policies/ccChangeHTTPMethod_v1.yaml
  integration/test-integration/src/test/resources/policies/ccRemoveHeader_v1.gotmpl
  integration/test-integration/src/test/resources/policies/ccRemoveHeader_v1.yaml
  integration/test-integration/src/test/resources/policies/customAddHeader_v1.gotmpl
  integration/test-integration/src/test/resources/policies/customAddHeader_v1.yaml
  integration/test-integration/src/test/resources/policies/customAddHeader_v2.gotmpl
  integration/test-integration/src/test/resources/policies/customAddHeader_v2.yaml
  integration/test-integration/src/test/resources/policies/opaPolicy_v1.gotmpl
  integration/test-integration/src/test/resources/policies/opaPolicy_v1.j2
  integration/test-integration/src/test/resources/policies/opaPolicy_v1.yaml
  integration/test-integration/src/test/resources/policies/rewriteResourcePath.gotmpl
  integration/test-integration/src/test/resources/policies/rewriteResourcePath.j2
  integration/test-integration/src/test/resources/policies/rewriteResourcePath_v1.gotmpl
  integration/test-integration/src/test/resources/policies/rewriteResourcePath_v1.j2
  integration/test-integration/src/test/resources/policies/rewriteResourcePath_v1.yaml
Labels: Type/Improvement

#2763 Fix abbreviated variable name - policyFullName
  adapter/internal/oasparser/model/policy_container.go
Labels: Type/Task

#2736 [int-tests] Websocket throttling tests and creation of admin policies via JSON
  integration/mock-backend-server/pom.xml
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/async/MockAsyncServer.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/async/websocket/WsServerFrameHandler.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/ApimResourceProcessor.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/AdminUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/JsonReader.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/PublisherUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/StoreUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/withapim/ApimPreparer.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/websocket/WebSocketBasicTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/websocket/WebSocketSecurityDisabledTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/websocket/throttle/WebsocketApiLevelThrottleTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/websocket/throttle/WebsocketApplicationThrottleTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/websocket/throttle/WebsocketSubscriptionThrottleTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/websocket/WsClient.java
  integration/test-integration/src/test/resources/apim/1/admin/throttle/advanced/3KbPerMin.json
  integration/test-integration/src/test/resources/apim/1/admin/throttle/advanced/5ReqPerMin.json
  integration/test-integration/src/test/resources/apim/1/admin/throttle/application/3KbPerMin.json
  integration/test-integration/src/test/resources/apim/1/admin/throttle/application/5ReqPerMin.json
  integration/test-integration/src/test/resources/apim/1/admin/throttle/subscription/5EventsPerMin.json
  integration/test-integration/src/test/resources/apim/1/apis/WebsocketApiLevelBandwidthThrottleAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/WebsocketApiLevelEventCountThrottleAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/WebsocketSubscriptionThrottleAPI.json
  integration/test-integration/src/test/resources/apim/1/apps/applications.json
  integration/test-integration/src/test/resources/apim/1/subscriptions/subscriptions.json
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Type/Task, test-improvements

#2762 Update carbon-apimgt and test related apim image to 4.1.0 beta
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/listener/TestNGListener.java
  integration/test-integration/src/test/resources/configs/vhost-deployment.toml
  integration/test-integration/src/test/resources/database/WSO2AM_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2CARBON_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2MB_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2METRICS_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2SHARED_DB.mv.db
  integration/test-integration/src/test/resources/dockerCompose/apim-in-common-network-docker-compose.yaml
  pom.xml
  resources/docker-compose/apim/conf/deployment.toml
  resources/docker-compose/apim/docker-compose.yaml
  resources/k8s-artifacts/apim/apim-deployment.yaml
Labels: Type/Task, test-improvements

#2728 Improve ASB logs
  adapter/pkg/messaging/azure_listener.go
Labels: Type/Task

#2769 Jackson.databind.version upgrade
  .trivyignore
Labels: Type/Task

#2764 [websocket] Send only the payload of a single frame at a time from enforcer to router
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketResponseObserver.java
Labels: Type/Bug

#2774 Preparations for 1.1.0-beta release
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  remove-containers.sh
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#2778 Fix for the error response of the blocked subscription
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/FaultCodeClassifier.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APISecurityConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
Labels: Type/Bug

#2777 Addition of control plane profile to the docker compose
  integration/test-integration/src/test/resources/dockerCompose/apim-in-common-network-docker-compose.yaml
  pom.xml
  resources/docker-compose/apim/docker-compose.yaml
  resources/k8s-artifacts/apim/apim-deployment.yaml
Labels: Type/Task

#2749 [Websocket] Improve Topic handling
  adapter/internal/oasparser/constants/constants.go
  adapter/internal/oasparser/model/async_api.go
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/RequestContext.java
  enforcer-parent/commons/src/test/java/org/wso2/choreo/connect/enforcer/commons/model/RequestContextTest.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/WebSocketFrameService.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/MediationPolicyFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketResponseObserver.java
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/build.sh
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/filter.cc
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/filter.h
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/handler_impl.cc
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/async/MockAsyncServer.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/async/websocket/WsBasicFrameHandler.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/async/websocket/WsHttpRequestHandler.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/async/websocket/WsTopicFrameHandler.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/websocket/WebSocketTopicTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/websocket/WsClient.java
  integration/test-integration/src/test/resources/apim/1/apiToAsyncAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/WebSocketTopicAPI.json
  integration/test-integration/src/test/resources/apim/1/apps/applications.json
  integration/test-integration/src/test/resources/apim/1/subscriptions/subscriptions.json
  integration/test-integration/src/test/resources/asyncAPIs/websocket_topic_asyncAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Type/Improvement

#2783 [int-tests] Update Interceptor test to include both header and reqBody update
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/InterceptorWithMtlsTestCase.java
  integration/test-integration/src/test/resources/openAPIs/intercept_request_path_level_openAPI.yaml
Labels: Type/Task

#2792 Upgrade alpine image version in adapter
  adapter/src/main/resources/Dockerfile
Labels: Type/Task

#2787 Corrected API count when deploying the APIs
  adapter/internal/synchronizer/apis_fetcher.go
Labels: Type/Bug

#2789 Add integration test for empty client request and update body from interceptor service
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/interceptor/InterceptorRequestFlowTestcase.java
Labels: Type/Task, test-improvements

#2786 Support Path Params in Rewrite Paths with API Policy
  adapter/internal/oasparser/model/common.go
  adapter/internal/oasparser/model/common_test.go
  adapter/internal/oasparser/model/resource.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apipolicy/APIPolicyTestCase.java
  integration/test-integration/src/test/resources/apiYaml/api_policies.yaml
  integration/test-integration/src/test/resources/openAPIs/api_policy_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
Labels: Type/Improvement

#2782 Masked the RevokedToken and log only with debug mode in revoked_token_listener.go
  adapter/internal/messaging/revoked_token_listener.go
  adapter/internal/utils/string_utils.go
  adapter/internal/utils/string_utils_test.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/RevokedTokenDiscoveryClient.java
Labels: Type/Bug

#2793 Updating APIM hostname
  resources/k8s-artifacts/apim/apim-config.yaml
  resources/k8s-artifacts/apim/apim-service.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-with-apim-ingress.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
  samples/istio/mtls-mode/README.md
  samples/istio/mtls-mode/gw_vs.yaml
  samples/istio/sidecar-mode/README.md
  samples/istio/sidecar-mode/gw_vs.yaml
Labels: Type/Bug

#2800 Updated jackson version. Hence deleting trivy entry
  .trivyignore
Labels: Type/Task

#2804 [int-tests] Add websocket topic oauth scope test and idle timeout test
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/withapim/CcStartupExecutorTwo.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/websocket/WebSocketScopeTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/websocket/WebSocketTimeoutTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/websocket/WsClient.java
  integration/test-integration/src/test/resources/apim/2/apiToAsyncAPI.json
  integration/test-integration/src/test/resources/apim/2/apis/WebSocketScopeAPI.json
  integration/test-integration/src/test/resources/apim/2/apis/WebSocketTimeoutAPI.json
  integration/test-integration/src/test/resources/apim/2/apps/applications.json
  integration/test-integration/src/test/resources/apim/2/subscriptions/subscriptions.json
  integration/test-integration/src/test/resources/asyncAPIs/websocket_scope_asyncAPI.yaml
  integration/test-integration/src/test/resources/configs/cc-special-scenarios-with-apim.toml
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Type/Task, test-improvements

#2802 Readme Update and APIM server role change to CP
  README.md
  integration/test-integration/src/test/resources/configs/vhost-deployment.toml
  resources/docker-compose/apim/conf/deployment.toml
  resources/k8s-artifacts/apim/apim-config.yaml
Labels: Type/Task

#2801 Updating apictl version to 4.1.0-rc1
  pom.xml
Labels: Type/Task

#2807 Update dependency versions of LICENSE-ADAPTER.txt
  resources/license/LICENSE-ADAPTER.txt
Labels: Type/Task

#2806 Test when interceptor service applied from both vendor extension and from API policy
  integration/test-integration/src/test/resources/openAPIs/api_policy_intercept_request_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/api_policy_intercept_response_openAPI.yaml
Labels: Type/Task, test-improvements

#2808 Handle analytics when OPA forbidden and when internal server with OPA
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/FaultCodeClassifier.java
Labels: Type/Bug

#2794 [Analytics] Publish analytics events for blocked API calls.
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/FaultCodeClassifier.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/UnsecuredAPIAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BlockedApiTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/websocket/WsClient.java
Labels: Type/Bug

#2810 Changing APIM port from 9443 to 9444
  resources/conf/config-for-eventhub.toml
  resources/docker-compose/apim/conf/deployment.toml
  resources/docker-compose/apim/docker-compose.yaml
Labels: Type/Task

#2805 Policy validation based on Policy Definition Action and Parameters
  adapter/config/parser.go
  adapter/internal/api/apis_impl.go
  adapter/internal/api/apis_process.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/constants/constants.go
  adapter/internal/oasparser/model/api_operation.go
  adapter/internal/oasparser/model/api_yaml.go
  adapter/internal/oasparser/model/async_api.go
  adapter/internal/oasparser/model/policy_container.go
  adapter/internal/oasparser/model/policy_container_test.go
  adapter/internal/oasparser/model/policy_layout.go
  adapter/internal/oasparser/model/resource.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/pkg/discovery/api/wso2/discovery/api/Resource.pb.go
  api/proto/wso2/discovery/api/Resource.proto
  api/proto/wso2/health/service/health.proto
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/Policy.java
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/RequestContext.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/Policy.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/PolicyOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ResourceProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/MediationPolicyFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/opa/OPAClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/opa/OPADefaultRequestGenerator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/HttpRequestHandler.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apipolicy/APIPolicyTestCase.java
  integration/test-integration/src/test/resources/apiYaml/api_policies.yaml
  integration/test-integration/src/test/resources/openAPIs/api_policy_openAPI.yaml
  integration/test-integration/src/test/resources/policies/ccAddHeaderNotSupportedAction_v1.gotmpl
  integration/test-integration/src/test/resources/policies/ccAddHeaderNotSupportedAction_v1.yaml
  integration/test-integration/src/test/resources/policies/ccAddHeaderNotSupportedParam_v1.gotmpl
  integration/test-integration/src/test/resources/policies/ccAddHeaderNotSupportedParam_v1.yaml
Labels: Type/Improvement

#2816 Check proto-gen changes in PR Check pipeline
  .github/workflows/main.yml
Labels: Type/Task

#2818 [1.1.0] Updated enforcer license text
  resources/license/LICENSE-ENFORCER.txt
Labels: Type/Task

#2798 Fix StatusRuntimeException cancelled before receiving half close
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/WebSocketFrameService.java
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/filter.cc
Labels: Type/Bug

#2823 Pass JWT transformer within methods
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/EnforcerConfig.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
Labels: Type/Bug

#2827 Remove webhook and SSE from supported API types
  adapter/internal/oasparser/model/api_yaml.go
Labels: Type/Bug

#2826 Remove additional log related to websocket stream
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/WebSocketFrameService.java
Labels: Type/Task

#2815 [Don't merge]Fix warning logs in router
  adapter/go.mod
  adapter/go.sum
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  resources/envoy.yaml
  router/src/main/resources/Dockerfile
Labels: Type/Task

#2830 Synchronize Default JWT transformer creation per issuer
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/EnforcerConfig.java
Labels: Type/Task
