Repository wso2/product-microgateway, pull requests merged in 2022-06, with the labels that each got.

#2877 [int-tests] Add path trailing slash test
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  integration/mock-backend-server/pom.xml
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Constants.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendProd.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Utils.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/dto/EchoResponse.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/AllHttpMethodsForWildcardTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/TrailingSlashTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
  integration/test-integration/src/test/resources/openAPIs/all_http_methods_for_wildcard_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/trailing_slash_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
Labels: Type/Task, Choreo

#2947 Merge branch feature/choreo-trailing-slash to branch choreo
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  integration/mock-backend-server/pom.xml
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Constants.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendProd.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Utils.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/dto/EchoResponse.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/AllHttpMethodsForWildcardTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/TrailingSlashTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
  integration/test-integration/src/test/resources/openAPIs/all_http_methods_for_wildcard_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/trailing_slash_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
Labels: Type/Bug, Choreo

#2955 [int-tests] Bump APIM version to 4.1.0
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/PublisherUtils.java
  pom.xml
Labels: Type/Task, test-improvements

#2946 Update proxy-wasm-sdk version to `c32d380ca6c9b1afac38a3841be99c37af2698bf`
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/BUILD
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/WORKSPACE
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/filter.cc
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/handler.h
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/handler_impl.cc
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/handler_impl.h
Labels: Type/Task

#2956 Upgrade internal JRE
  distribution/pom.xml
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
  distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
  pom.xml
  tests/pom.xml
  tests/src/test/resources/testng.xml
Labels: ballerina-mgw

#2936 Router request response logging - logs inside interceptors
  adapter/config/config_utils.go
  adapter/internal/auth/auth.go
  adapter/internal/interceptor/interceptor.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/utils/string_utils.go
  adapter/pkg/config/log_types.go
  resources/conf/log_config.toml
  resources/k8s-artifacts/choreo-connect/logconfig-toml-configmap.yaml
  router/src/main/resources/interceptor/lib/interceptor.lua
  router/src/main/resources/interceptor/lib/utils.lua
Labels: Type/New Feature, Docs/Has Impact

#2965 Adding JDK 11 related changes
  components/micro-gateway-cli/pom.xml
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  distribution/pom.xml
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/resources/bin/micro-gw
  distribution/src/main/assembly/linux_bin.xml
  distribution/src/main/assembly/macos_bin.xml
  distribution/src/main/assembly/windows_bin.xml
Labels: ballerina-mgw

#2966 Prepare for 3.2.4 release
  README.md
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/jwt/generator/MGWJWTGeneratorInvoker.java
  distribution/LICENSE-RUNTIME.txt
  distribution/LICENSE-TOOLKIT.txt
  distribution/resources/bin/gateway
  distribution/resources/version.txt
  release-notes.html
  samples/sample-jwt-generator/pom.xml
Labels: ballerina-mgw

#2964 Add gRPC keep alive configurations
  adapter/internal/adapter/adapter.go
  router/src/main/resources/Dockerfile
  router/src/main/resources/Dockerfile.ubuntu
Labels: Type/Task

#2963 Add gRPC keep alive configurations
  adapter/internal/adapter/adapter.go
  router/src/main/resources/Dockerfile
  router/src/main/resources/Dockerfile.ubuntu
Labels: Type/Task, Choreo

#2967 Include Error Logging in developer guide
  developer-guide.md
Labels: Type/Docs

#2959 Edge proxy mode configuration added
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/oasparser/envoyconf/listener.go
  resources/conf/config-for-eventhub.toml
  resources/conf/config.toml
  resources/conf/config.toml.template
  resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
  resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
Labels: Type/Improvement

#2974 Using loopback IP address instead of localhost in gRPC health probe
  adapter/src/main/resources/check_health.sh
  enforcer-parent/enforcer/src/main/resources/check_health.sh
Labels: Type/Bug

#2975 Adding Interceptor sample service with WSO2 Micro Integrator
  samples/interceptors/README.md
  samples/interceptors/wso2-micro-integrator/InterceptorServiceWithMI/InterceptorServiceWithMICompositeExporter/.gitignore
  samples/interceptors/wso2-micro-integrator/InterceptorServiceWithMI/InterceptorServiceWithMICompositeExporter/pom.xml
  samples/interceptors/wso2-micro-integrator/InterceptorServiceWithMI/InterceptorServiceWithMIConfigs/artifact.xml
  samples/interceptors/wso2-micro-integrator/InterceptorServiceWithMI/InterceptorServiceWithMIConfigs/pom.xml
  samples/interceptors/wso2-micro-integrator/InterceptorServiceWithMI/InterceptorServiceWithMIConfigs/src/main/synapse-config/api/Choreo-Connect_Interceptor_Service.xml
  samples/interceptors/wso2-micro-integrator/InterceptorServiceWithMI/InterceptorServiceWithMIDockerExporter/.gitignore
  samples/interceptors/wso2-micro-integrator/InterceptorServiceWithMI/InterceptorServiceWithMIDockerExporter/CompositeApps/InterceptorServiceWithMICompositeExporter-1.0.0.car
  samples/interceptors/wso2-micro-integrator/InterceptorServiceWithMI/InterceptorServiceWithMIDockerExporter/Dockerfile
  samples/interceptors/wso2-micro-integrator/InterceptorServiceWithMI/InterceptorServiceWithMIDockerExporter/ReadMe.html
  samples/interceptors/wso2-micro-integrator/InterceptorServiceWithMI/InterceptorServiceWithMIDockerExporter/Resources/client-truststore.jks
  samples/interceptors/wso2-micro-integrator/InterceptorServiceWithMI/InterceptorServiceWithMIDockerExporter/Resources/wso2carbon.jks
  samples/interceptors/wso2-micro-integrator/InterceptorServiceWithMI/InterceptorServiceWithMIDockerExporter/deployment.toml
  samples/interceptors/wso2-micro-integrator/InterceptorServiceWithMI/InterceptorServiceWithMIDockerExporter/pom.xml
  samples/interceptors/wso2-micro-integrator/InterceptorServiceWithMI/pom.xml
  samples/interceptors/wso2-micro-integrator/README.md
  samples/interceptors/wso2-micro-integrator/copy-certs.sh
  samples/interceptors/wso2-micro-integrator/docker-compose.yaml
Labels: Type/Docs

#2978 Update docs on create Router docker image with interceptor lua changes
  router/src/main/resources/interceptor/README.md
Labels: Type/Docs
