Repository wso2/product-microgateway, pull requests merged in 2022-10, with the labels that each got.

#3092 [int-tests] Update int tests for standalone mode git sync to use gitea
  .gitignore
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/ChoreoConnectImpl.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithSourceControl.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/SourceWatcherTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpClientRequest.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/SourceControlUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
  integration/test-integration/src/test/resources/configs/cc-with-source-control.toml
  integration/test-integration/src/test/resources/dockerCompose/git-service.yaml
  integration/test-integration/src/test/resources/dockerVolumeMounts/gitea/gitea/conf/app.ini
  integration/test-integration/src/test/resources/dockerVolumeMounts/gitea/gitea/gitea.db
  integration/test-integration/src/test/resources/git-artifacts/update/petstore.zip
  integration/test-integration/src/test/resources/git-artifacts/updated/petstore/Definitions/swagger.yaml
  integration/test-integration/src/test/resources/git-artifacts/zip/petstore.zip
  integration/test-integration/src/test/resources/git-artifacts/zip/petstore1/Definitions/swagger.yaml
  integration/test-integration/src/test/resources/git-artifacts/zip/petstore1/README.md
  integration/test-integration/src/test/resources/git-artifacts/zip/petstore1/api.yaml
  integration/test-integration/src/test/resources/git-artifacts/zip/petstore1/api_meta.yaml
  integration/test-integration/src/test/resources/git-artifacts/zip/petstore1/deployment_environments.yaml
Labels: Type/Task

#3099 [3.2.x] Upgrade ballerina version to 1.2.33
  pom.xml
Labels: hacktoberfest-accepted, ballerina-mgw

#3097 [int-tests] Avoid creating more than 25 APIs in a single run of ApimPreparer
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/ApimResourceProcessor.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/withapim/ApimStartupExecutor.java
Labels: Type/Task

#3096 Remove unused env var `apim_admin_pwd`
  integration/test-integration/src/test/resources/dockerCompose/cc-cacert-mounted-mtls.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#3090 Fix new line issue when certs are created in a Windows platform
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/JWTUtils.java
Labels: Type/Bug

#3083 Add common utils to GQL feature
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/GraphQLAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/graphql/GraphQLPayloadUtils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/graphql/GraphQLQueryAnalysisFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/graphql/analyzer/QueryMutationAnalyzer.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/graphql/utils/GraphQLProcessorUtils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/graphql/utils/GraphQLSchemaDefinitionUtils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/HttpRequestHandler.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/graphql/GraphQLScopeTestCase.java
  pom.xml
Labels: Type/Improvement

#3108 [3.2.x] Upgrade Call Home Core version to 1.0.14
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  pom.xml
Labels: hacktoberfest-accepted, ballerina-mgw

#3101 Create CODEOWNERS
  CODEOWNERS
Labels: ballerina-mgw

#3110 Upgrade dependency versions
  pom.xml
Labels: Type/Task

#3109 upgrade dependency versions
  pom.xml
Labels: Type/Task

#3113 Update enforcer dependencies
  pom.xml
Labels: Type/Task

#3112 Update enforcer dependencies
  pom.xml
Labels: Type/Task

#3115 Update adapter packages and grpc health probe
  adapter/go.mod
  adapter/go.sum
  pom.xml
Labels: Type/Task

#3105 Compression filter addition
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/oasparser/envoyconf/compression_filter.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/http_filters.go
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendProd.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Utils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/APiDeployViaApictlTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/router/EnvoyHttpFilterTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/EnvoyHttpFilterTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/GzipCompressionTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
  integration/test-integration/src/test/resources/apim/2/apis/CompressionTestAPI.json
  integration/test-integration/src/test/resources/apim/2/apps/applications.json
  integration/test-integration/src/test/resources/apim/2/subscriptions/subscriptions.json
  integration/test-integration/src/test/resources/configs/cc-special-scenarios-with-apim.toml
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
  pom.xml
  resources/conf/config.toml.template
Labels: Type/New Feature

#3119 Update adapter dependencies and grpc health probe
  adapter/go.mod
  adapter/go.sum
  pom.xml
Labels: Type/Task

#3103 Code coverage support
  .github/workflows/codecov.yml
  .github/workflows/main.yml
  adapter/scripts/build.sh
  dev-scripts/code-coverage/prepare-files-after-int-tests.sh
  dev-scripts/code-coverage/prepare-files-before-int-tests.sh
  enforcer-parent/commons/pom.xml
  enforcer-parent/enforcer/pom.xml
  integration/test-integration/pom.xml
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/CcInstance.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/ChoreoConnectImpl.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
  pom.xml
Labels: Type/Task

#3067 Jmx monitoring for enforcer
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/dto/ThreadPoolConfig.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/dto/ThreadPoolConfigMBean.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/jmx/JMXAgent.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/jmx/JMXUtils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/jmx/MBeanManagementFactory.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/jmx/MBeanRegistrator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/metrics/jmx/api/ExtAuthMetricsMXBean.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/metrics/jmx/impl/ExtAuthMetrics.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/AuthServer.java
Labels: Type/Improvement

#3117 Enable security for prototyped APIs
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/PrototypedAPITestCase.java
Labels: Choreo

#3093 Fix apikey failure when header key is in uppercase
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/GraphQLAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/Utils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/MediationPolicyFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleDataHolder.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/security/APIKeyTestCase.java
  integration/test-integration/src/test/resources/openAPIs/api_key_swagger_security_openAPI.yaml
Labels: Type/Bug
