Repository wso2/product-microgateway, pull requests merged in 2022-02, with the labels that each got.

#2647 int-test: Fix intermittent test failure when undeploying API
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithMultipleEnv.java
Labels: Type/Task, test-improvements

#2635 Refactor processing of the api.yaml file
  adapter/internal/api/apis_impl.go
  adapter/internal/api/apis_process.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/constants/constants.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/internal/oasparser/model/api_env.go
  adapter/internal/oasparser/model/api_operation.go
  adapter/internal/oasparser/model/api_yaml.go
  adapter/internal/oasparser/model/common.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/open_api_internal_test.go
  adapter/internal/oasparser/model/project_structs.go
  adapter/internal/oasparser/model/swagger.go
  adapter/internal/oasparser/model/swagger_internal_test.go
  adapter/internal/oasparser/model/swagger_test.go
  adapter/internal/oasparser/model/types.go
  adapter/internal/oasparser/operator/operator_test.go
  adapter/internal/synchronizer/apis_fetcher.go
Labels: Type/Task, Priority/Normal

#2646 int-tests: Enable pointing to an OpenAPI definition when creating APIs via JSON
  integration/test-integration/README.md
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/ApimResourceProcessor.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/PublisherUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/StoreUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BackendSecurityTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BasicEventsTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BlockedApiTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/ExistingApiTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/SubscriptionValidationTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/jwtValidator/JwtAndScopeTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/throttle/AdvanceThrottlingTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/throttle/ApplicationThrottlingTestCase.java
  integration/test-integration/src/test/resources/apim/1/apiToOpenAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/AdvancedThrottlingAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/ApplicationThrottlingAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/BackendSecurityAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/BlockedAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/ExistingAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/JwtScopeAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/SubscriptionValidationAPI.json
  integration/test-integration/src/test/resources/apim/1/apps/applications.json
  integration/test-integration/src/test/resources/apim/1/subscriptions/subscriptions.json
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
Labels: Type/Task, test-improvements

#2642 [3.2.x] Upgrade ballerina version to 1.2.25
  pom.xml
Labels: ballerina-mgw

#2641 [3.2.x] Update certificate validity period and comment
  distribution/resources/ballerinaTruststore.p12
  tests/src/test/resources/ballerinaTruststore.p12
  tests/src/test/resources/distributedThrottling/wso2carbon.jks
  tests/src/test/resources/testng.xml
  tests/src/test/resources/wso2carbon.jks
Labels: ballerina-mgw

#2648 Add adapter side AsyncAPI implementation
  adapter/internal/api/apis_process.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/constants/constants.go
  adapter/internal/oasparser/model/api_yaml.go
  adapter/internal/oasparser/model/async_api.go
  adapter/internal/oasparser/model/async_api_test.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/project_structs.go
  adapter/internal/oasparser/operator/operator.go
  adapter/internal/oasparser/operator/operator_test.go
  adapter/internal/oasparser/utills/open_api_utills_test.go
  adapter/internal/oasparser/utills/open_api_utils.go
  adapter/test-resources/envoycodegen/asyncapi_websocket.yaml
Labels: Type/New Feature

#2651 int-tests: withapim: Update API Key, retry and timout tests to deploy APIs via JSON
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/RetryAndTimeoutTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/apikey/APIKeyAppLevelThrottleTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/apikey/APIKeyBlockedAPITestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/apikey/APIKeyTestCase.java
  integration/test-integration/src/test/resources/apim/1/apiToOpenAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/APIKeyAppLevelThrottleAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/APIKeyBlockedAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/APIKeyTestAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/RetryAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/TimeoutAPI.json
  integration/test-integration/src/test/resources/apim/1/apps/applications.json
  integration/test-integration/src/test/resources/apim/1/subscriptions/subscriptions.json
  integration/test-integration/src/test/resources/openAPIs/api_key_blocked_openAPI.yaml
Labels: Type/Task, test-improvements

#2658 Adapter changes for debugging go-amqp library
  adapter/pkg/messaging/azure_listener.go
  adapter/scripts/build.sh
  adapter/src/main/resources/Dockerfile
  adapter/src/main/resources/Dockerfile.ubuntu
Labels: Type/Improvement

#2659 Temporarily Remove /apis endpoint call in choreo branch
  adapter/internal/discovery/xds/server.go
  adapter/internal/eventhub/subscription.go
  adapter/internal/ga/api_event_listener.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/types.go
  adapter/pkg/discovery/api/wso2/discovery/api/api.pb.go
  api/proto/wso2/discovery/api/api.proto
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/APIConfig.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/Api.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsUtils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/UnsecuredAPIAuthenticator.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/EnforcerAPITestCase.java
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Choreo

#2653 Request body passing support
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/oasparser/constants/constants.go
  adapter/internal/oasparser/envoyconf/http_filters.go
  adapter/internal/oasparser/envoyconf/internal_dtos.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/swagger.go
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/RequestContext.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/HttpRequestHandler.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendProd.java
  integration/test-integration/src/main/java/org/wso2/choreo/connect/tests/CustomFilter.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/filter/BodyPassDisabledTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/filter/CustomFilterTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
  integration/test-integration/src/test/resources/configs/jwt-generator-config.toml
  integration/test-integration/src/test/resources/openAPIs/openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/request_body_pass_disabled_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
  resources/conf/config.toml.template
Labels: Type/Improvement

#2656 Handling Operation Policy Spec and Definition
  adapter/internal/api/apis_impl.go
  adapter/internal/api/apis_process.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/model/api_operation.go
  adapter/internal/oasparser/model/api_yaml.go
  adapter/internal/oasparser/model/api_yaml_test.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/policy_container.go
  adapter/internal/oasparser/model/policy_container_test.go
  adapter/internal/oasparser/model/project_structs.go
  adapter/internal/oasparser/model/resource.go
  adapter/internal/oasparser/utills/open_api_utills_test.go
  adapter/internal/oasparser/utills/open_api_utils.go
  adapter/pkg/discovery/api/wso2/discovery/api/Resource.pb.go
  adapter/scripts/build.sh
  api/proto/wso2/discovery/api/Resource.proto
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/Policy.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/Policy.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/PolicyOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ResourceProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/MediationPolicyFilter.java
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Improvement

#2661 Refactor error logs in adapter
  adapter/config/logger.go
  adapter/config/parser.go
  adapter/internal/adapter/adapter.go
  adapter/internal/api/apis_impl.go
  adapter/internal/api/apis_process.go
  adapter/internal/api/restserver/config_restapi.go
  adapter/internal/auth/auth.go
  adapter/internal/discovery/xds/consul.go
  adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
  adapter/internal/discovery/xds/routercallbacks/router_callbacks.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/eventhub/subscription.go
  adapter/internal/ga/client.go
  adapter/internal/interceptor/interceptor.go
  adapter/internal/messaging/km_listener.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/notifier/deployment_notifier.go
  adapter/internal/oasparser/envoyconf/access_loggers.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/pkg/logging/log_format.go
  adapter/pkg/logging/logging_internal_test.go
  adapter/pkg/logging/package_logs.go
Labels: Type/Improvement

#2664 Preparations for 1.1.0-m2 release
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  remove-containers.sh
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#2665 Fix review comments - Operational Policies
  adapter/internal/api/apis_process.go
  adapter/internal/oasparser/model/api_yaml.go
  adapter/internal/oasparser/model/policy_container.go
Labels: Type/Task

#2666 Refactor error logs in enforcer
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/logging/ErrorDetails.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AccessLoggingService.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/DefaultAnalyticsEventPublisher.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/keymgt/KeyManagerHolder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyHandler.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/AuthServer.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleEventListener.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/databridge/publisher/ThrottleDataPublisher.java
Labels: Type/Task, Priority/Normal

#2654 Add source version control for the adapter
  .gitignore
  adapter/config/default_config.go
  adapter/config/parser.go
  adapter/config/types.go
  adapter/go.mod
  adapter/go.sum
  adapter/internal/adapter/adapter.go
  adapter/internal/api/apis_impl.go
  adapter/internal/api/restserver/config_restapi.go
  adapter/internal/loggers/logger.go
  adapter/internal/sourcewatcher/sourcewatcher.go
  adapter/pkg/auth/auth.go
  adapter/pkg/auth/auth_test.go
  adapter/pkg/loggers/logger.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/Constants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/JWTUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/CcInstance.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/ChoreoConnectImpl.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/gitservice/GitService.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithSourceControl.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/SourceWatcherTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/SourceControlUtils.java
  integration/test-integration/src/test/resources/configs/cc-with-source-control.toml
  integration/test-integration/src/test/resources/dockerCompose/git-service.yaml
  integration/test-integration/src/test/resources/git-artifacts/directory/petstore/Definitions/swagger.yaml
  integration/test-integration/src/test/resources/git-artifacts/directory/petstore/README.md
  integration/test-integration/src/test/resources/git-artifacts/directory/petstore/api.yaml
  integration/test-integration/src/test/resources/git-artifacts/directory/petstore/api_meta.yaml
  integration/test-integration/src/test/resources/git-artifacts/directory/petstore/deployment_environments.yaml
  integration/test-integration/src/test/resources/git-artifacts/update/petstore.zip
  integration/test-integration/src/test/resources/git-artifacts/zip/petstore.zip
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
  resources/conf/config.toml.template
Labels: Type/New Feature

#2679 Add correlation logs to enforcer
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/logging/CustomJsonLayout.java
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/logging/LoggingConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/HttpRequestHandler.java
  resources/conf/log4j2.properties
Labels: Type/Task, Priority/Normal

#2681 Preparations for 1.1.0-m3 release
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  remove-containers.sh
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#2684 [test-case fix] Waiting time increase for source control related tests
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithSourceControl.java
Labels: Type/Task

#2685 Fix issue with source watcher startup
  adapter/internal/adapter/adapter.go
  adapter/internal/sourcewatcher/sourcewatcher.go
Labels: Type/Improvement

#2690 Update gitlab docker image
  integration/test-integration/src/test/resources/dockerCompose/git-service.yaml
Labels: Type/Task

#2691 Upgrade azure-go-sdk
  adapter/go.mod
  adapter/go.sum
Labels: Type/Bug, Priority/High

#2700 Run `go mod tidy` after asb-sdk upgrade
  adapter/go.mod
  adapter/go.sum
Labels: Type/Bug, Priority/Highest

#2698 Improve DNS resolving rate
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  resources/conf/config.toml.template
Labels: Type/Improvement

#2697 Improve DNS resolving rate
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  resources/conf/config.toml.template
Labels: Type/Improvement

#2702 Preparations for 1.1.0-m4 release
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  pom.xml
  remove-containers.sh
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#2650 get mock impl from oas examples
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/constants/constants.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/model/api_operation.go
  adapter/internal/oasparser/model/api_yaml.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/open_api_internal_test.go
  adapter/internal/oasparser/model/swagger.go
  adapter/internal/oasparser/model/swagger_internal_test.go
  adapter/pkg/discovery/api/wso2/discovery/api/mocked_api_config.pb.go
  api/proto/wso2/discovery/api/mocked_api_config.proto
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/MockedApiConfig.java
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/MockedContentExamples.java
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/MockedResponseConfig.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/MockedApiConfig.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/MockedApiConfigOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/MockedApiConfigProto.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/MockedContentConfig.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/MockedContentConfigOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/MockedContentExample.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/MockedContentExampleOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/MockedResponseConfig.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/MockedResponseConfigOrBuilder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/ResponseObject.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/Utils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/GeneralErrorCodeConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/MediationPolicyFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/MockImplUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/mockEndpoint/MockApiTestCase.java
  integration/test-integration/src/test/resources/apiYaml/mock_impl_test.yaml
  integration/test-integration/src/test/resources/openAPIs/mock_endpoint_openAPI.yaml
Labels: Type/New Feature
