Repository wso2/product-microgateway, pull requests merged in 2022-09, with the labels that each got.

#3054 Add timestamp check for revision ids
  adapter/internal/ga/client.go
Labels: Type/Task, Choreo

#3065 Update snakeyaml version
  pom.xml
Labels: Type/Task

#3066 Update snakeyaml version
  pom.xml
Labels: Type/Task

#3041 upgrade azure sdk
  adapter/go.mod
  adapter/go.sum
Labels: Type/Task, Choreo

#3050 Stop copying certs to /home/wso2/security directory in enforcer image
  enforcer-parent/enforcer/src/main/assembly/assembly.xml
Labels: Choreo

#3070 Fix scope parsing error when multiple scopes provided in an array
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/ScopesAsArrayTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/throttle/SubscriptionThrottlingTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TokenUtil.java
  integration/test-integration/src/test/resources/openAPIs/scopes_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
Labels: Type/Bug

#3055 Log original path in router access log using dynamic meta data
  adapter/internal/oasparser/envoyconf/access_loggers.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/RouterAccessLogConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
  resources/conf/log_config.toml
  resources/k8s-artifacts/choreo-connect/logconfig-toml-configmap.yaml
Labels: Type/Improvement

#3061 Log original path in router access log using dynamic meta data
  adapter/internal/oasparser/envoyconf/access_loggers.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/RouterAccessLogConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
  resources/conf/log_config.toml
  resources/k8s-artifacts/choreo-connect/logconfig-toml-configmap.yaml
Labels: Choreo

#3078 int-test: Confirm the case change done to headers by envoy
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendProd.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Utils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/router/EnvoyHttpFilterTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
  integration/test-integration/src/test/resources/openAPIs/openAPI.yaml
Labels: Type/Task

#3077 Validate subscription in API key based on "APIM APIkey" issuer
  adapter/config/default_config.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/pkg/discovery/api/wso2/discovery/config/enforcer/config.pb.go
  api/proto/wso2/discovery/config/enforcer/config.proto
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/Config.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/ConfigOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/ConfigProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyHandler.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/JWTUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithBackendTlsAndCorsDisabledWithOPA.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithMultipleEnv.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/security/APIKeyTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/security/SubscriptionValidationTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/ApictlUtils.java
  integration/test-integration/src/test/resources/configs/cors-disabled-config.toml
  integration/test-integration/src/test/resources/configs/multiple-env-config.toml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
  resources/conf/config.toml.template
Labels: Type/Bug

#3086 Fix :path when endpoint with no basepath
  adapter/src/main/resources/Dockerfile
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/EndpointCluster.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/Utils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  enforcer-parent/enforcer/src/main/resources/Dockerfile
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendProd.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/NoBasepathEndpointTestCase.java
  integration/test-integration/src/test/resources/openAPIs/no_basepath_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
Labels: Type/Bug, Type/Improvement

#3072 Update frequent user operations related error logs to debug log level
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyHandler.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
Labels: Type/Improvement, Choreo

#3087 Update frequent user operations related error logs to debug log level
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyHandler.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
Labels: Type/Improvement

#3074 Dependency version upgrades
  adapter/go.mod
  adapter/go.sum
  pom.xml
Labels: Type/Task

#3073 Dependency version upgrades
  adapter/go.mod
  adapter/go.sum
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyHandler.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  pom.xml
Labels: Choreo

#3037 Add OpenTelemetry OTLP exporter support for publishing traces
  enforcer-parent/enforcer/pom.xml
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/TracerFactory.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/TracingConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/AzureExporter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/JaegerExporter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/OTLPExporter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/ZipkinExporter.java
  pom.xml
  resources/conf/config.toml.template
Labels: Type/New Feature
