Repository wso2/product-microgateway, pull requests merged in 2022-08, with the labels that each got.

#2983 Enable adding polices at operation level
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/constants/constants.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/internal_dtos.go
  adapter/internal/oasparser/envoyconf/listener_test.go
  adapter/internal/oasparser/envoyconf/routes_configs.go
  adapter/internal/oasparser/envoyconf/routes_utils_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/internal/oasparser/model/api_operation.go
  adapter/internal/oasparser/model/async_api.go
  adapter/internal/oasparser/model/common.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/policy_container.go
  adapter/internal/oasparser/model/policy_container_test.go
  adapter/internal/oasparser/model/policy_layout.go
  adapter/internal/oasparser/model/resource.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/MediationPolicyFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/opa/OPAClient.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/opa/OPADefaultRequestGenerator.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Utils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithBackendTlsAndCorsDisabledWithOPA.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/AllHttpMethodsForWildcardTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/TrailingSlashTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apipolicy/APIPolicyPerOperationTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apipolicy/APIPolicyTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/websocket/WebSocketTopicTestCase.java
  integration/test-integration/src/test/resources/apiYaml/api_policies.yaml
  integration/test-integration/src/test/resources/apiYaml/api_policies_invalid_param_id.yaml
  integration/test-integration/src/test/resources/apiYaml/api_policy_per_operation.yaml
  integration/test-integration/src/test/resources/openAPIs/api_policy_invalid_param_id_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/api_policy_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/api_policy_per_operation_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/trailing_slash_openAPI.yaml
  integration/test-integration/src/test/resources/policies/ccAddHeader_v1.yaml
  integration/test-integration/src/test/resources/policies/ccChangeHTTPMethod_v1.yaml
  integration/test-integration/src/test/resources/policies/ccRemoveHeader_v1.yaml
  integration/test-integration/src/test/resources/policiesInvalid/ccAddHeaderNotSupportedAction_v1.gotmpl
  integration/test-integration/src/test/resources/policiesInvalid/ccAddHeaderNotSupportedAction_v1.yaml
  integration/test-integration/src/test/resources/policiesInvalid/ccAddHeaderNotSupportedParam_v1.gotmpl
  integration/test-integration/src/test/resources/policiesInvalid/ccAddHeaderNotSupportedParam_v1.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
Labels: Type/Improvement, Docs/Has Impact

#3015 upgrade azsb to v1.0.2
  adapter/go.mod
  adapter/go.sum
  adapter/pkg/messaging/azure_listener.go
Labels: Type/Task

#3023 [MGW] [3.2.x] Add gson dependency to micro-gateway-tools
  components/micro-gateway-tools/pom.xml
Labels: ballerina-mgw

#3025 Prepare for 3.2.5 release
  README.md
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java
  components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/jwt/generator/MGWJWTGeneratorInvoker.java
  distribution/LICENSE-RUNTIME.txt
  distribution/LICENSE-TOOLKIT.txt
  distribution/resources/bin/gateway
  distribution/resources/version.txt
  release-notes.html
  samples/sample-jwt-generator/pom.xml
Labels: ballerina-mgw

#3005 [CORS] Support providing origins with wildcard subdomains.
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/security/CorsTestCase.java
  integration/test-integration/src/test/resources/configs/jwt-generator-config.toml
  integration/test-integration/src/test/resources/openAPIs/cors_openAPI.yaml
Labels: Type/Improvement

#3029 Dependency version upgrades for apache tomcat embed core
  pom.xml
Labels: Type/Task, Priority/Normal

#3012 Updating issue templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation_template.md
  .github/ISSUE_TEMPLATE/feature_form.yml
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/ISSUE_TEMPLATE/improvement_form.yml
  .github/ISSUE_TEMPLATE/issue_form.yml
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/ISSUE_TEMPLATE/task_form.yml
Labels: Type/Task

#3020 Create API artifacts directory in adapter docker image
  adapter/src/main/resources/Dockerfile
  adapter/src/main/resources/Dockerfile.ubuntu
  enforcer-parent/enforcer/src/main/resources/Dockerfile
  enforcer-parent/enforcer/src/main/resources/Dockerfile.ubuntu
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#3030 [main] Fix iat and exp values in backend JWT
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/pkg/discovery/api/wso2/discovery/config/enforcer/jwt_generator.pb.go
  api/proto/wso2/discovery/config/enforcer/jwt_generator.proto
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/JWTGenerator.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/JWTGeneratorOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/JWTGeneratorProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/BackendJwtUtils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/JWTUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtGenerator/JwtGeneratorTestCase.java
  resources/conf/config.toml.template
Labels: Type/Bug

#3038 go.mod updated for revision id related changes
  .trivyignore
  adapter/go.mod
  adapter/go.sum
Labels: Type/Task, Choreo

#3032 [main] Prevent x-envoy headers being sent to the backend
  adapter/internal/oasparser/envoyconf/http_filters.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/routes_configs.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/router/EnvoyHttpFilterTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/EnvoyHttpFilterTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/ExistingApiTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
  integration/test-integration/src/test/resources/apim/1/apis/EnvoyHttpFilterAPI.json
  integration/test-integration/src/test/resources/apim/1/apps/applications.json
  integration/test-integration/src/test/resources/apim/1/subscriptions/subscriptions.json
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Type/Bug

#3034 Add sample MI project for REST to SOAP conversion
  .gitignore
  samples/rest-to-soap-conversion/PhoneVerification/.project
  samples/rest-to-soap-conversion/PhoneVerification/PhoneVerificationCompositeExporter/.project
  samples/rest-to-soap-conversion/PhoneVerification/PhoneVerificationCompositeExporter/pom.xml
  samples/rest-to-soap-conversion/PhoneVerification/PhoneVerificationConfigs/.project
  samples/rest-to-soap-conversion/PhoneVerification/PhoneVerificationConfigs/artifact.xml
  samples/rest-to-soap-conversion/PhoneVerification/PhoneVerificationConfigs/pom.xml
  samples/rest-to-soap-conversion/PhoneVerification/PhoneVerificationConfigs/src/main/resources/metadata/PhoneVerify_metadata.yaml
  samples/rest-to-soap-conversion/PhoneVerification/PhoneVerificationConfigs/src/main/resources/metadata/PhoneVerify_swagger.yaml
  samples/rest-to-soap-conversion/PhoneVerification/PhoneVerificationConfigs/src/main/synapse-config/api/PhoneVerify.xml
  samples/rest-to-soap-conversion/PhoneVerification/README.md
  samples/rest-to-soap-conversion/PhoneVerification/pom.xml
Labels: Type/Docs

#3039 Remove trivy ignore entry for adapter health probe
  .trivyignore
Labels: Choreo

#3031 [main] Fix error when auth header has bearer twice
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/JwtTestCase.java
Labels: Type/Bug

#3045 Update revision timestamp check
  adapter/internal/ga/client.go
Labels: Type/Task, Choreo

#3044 Dependency version upgrades
  pom.xml
Labels: Type/Task

#3033 Suppress x-envoy headers and cluster header being sent to the backend service
  adapter/internal/oasparser/envoyconf/http_filters.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/router/EnvoyHttpFilterTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/EnvoyHttpFilterTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
  integration/test-integration/src/test/resources/apimApisAppsSubs/apis.json
  integration/test-integration/src/test/resources/apimApisAppsSubs/applications.json
  integration/test-integration/src/test/resources/apimApisAppsSubs/subscriptions.json
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Choreo

#3046 Revert temporary changes added in #3026
  adapter/internal/ga/client.go
Labels: Type/Task, Choreo

#3049 Bump : slf4j-ext, gson, netty
  pom.xml
Labels: Choreo

#3053 [main] int-tests: Invoke mockbackend in QSG test
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/QSGAndSwaggerTestCase.java
  integration/test-integration/src/test/resources/git-artifacts/directory/petstore/Definitions/swagger.yaml
  integration/test-integration/src/test/resources/git-artifacts/update/petstore.zip
  integration/test-integration/src/test/resources/git-artifacts/zip/petstore.zip
Labels: Type/Task

#3052 int-tests: Invoke mockbackend in QSG
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/QSGAndSwaggerTestCase.java
Labels: Type/Task, Choreo

#3024 Addition of sample WebSocket API project
  samples/apiProjects/SampleWebsocketApi/Definitions/asyncapi.yaml
  samples/apiProjects/SampleWebsocketApi/README.md
  samples/apiProjects/SampleWebsocketApi/api.yaml
Labels: Type/Docs, Docs/Has Impact
