Repository wso2/product-microgateway, pull requests merged in 2022-07, with the labels that each got.

#2981 Add support for custom throttle properties in key template based throttling
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleDataHolder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
  integration/test-integration/src/main/java/org/wso2/choreo/connect/tests/CustomFilter.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/filter/CustomFilterTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/throttle/KeyTemplateThrottlingTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
  integration/test-integration/src/test/resources/apim/2/apis/KeyTemplateThrottlingAPI.json
  integration/test-integration/src/test/resources/apim/2/apps/applications.json
  integration/test-integration/src/test/resources/apim/2/subscriptions/subscriptions.json
  integration/test-integration/src/test/resources/configs/cc-special-scenarios-with-apim.toml
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Labels: Type/Improvement

#2953 HTTP2 support in router
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/oasparser/constants/constants.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/model/common.go
  adapter/internal/oasparser/model/mgw_swagger.go
  integration/mock-backend-server/pom.xml
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Constants.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockServices.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/http2/EchoHttp2ServerHandler.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/http2/EchoHttpServerHandler.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/http2/Http2ClearTextEchoHandler.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/http2/Http2ClearTextEchoHandlerBuilder.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/http2/Http2MockBackend.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/http2/Http2OrHttpHandler.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/http2/Http2ServerInitializer.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithBackendTlsAndCorsDisabledWithOPA.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/http2/Http2ClearTextApiTestCase2.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/http2/Http2SecuredApiTestCase2.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/Http2ClearTextApiTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/Http2DownstreamToHttp1UpstreamTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/Http2SecuredApiTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Http2ClientRequest.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
  integration/test-integration/src/test/resources/apim/1/apiToOpenAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/Http1API.json
  integration/test-integration/src/test/resources/apim/1/apis/Http2ClearTextAPI.json
  integration/test-integration/src/test/resources/apim/1/apis/Http2SecuredAPI.json
  integration/test-integration/src/test/resources/apim/1/apps/applications.json
  integration/test-integration/src/test/resources/apim/1/subscriptions/subscriptions.json
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls-with-opa-server.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
  integration/test-integration/src/test/resources/openAPIs/http2_clear_text_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/http2_secured_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
  integration/test-integration/src/test/resources/testng-cc-with-apim.xml
  resources/conf/config.toml.template
  resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
  samples/openAPI-definitions/http2_sample.yaml
Labels: Type/New Feature

#2996 Bug fixes for Backend JWT generation
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/pkg/discovery/api/wso2/discovery/config/enforcer/jwt_generator.pb.go
  api/proto/wso2/discovery/config/enforcer/jwt_generator.proto
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/JWTGenerator.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/JWTGeneratorOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/JWTGeneratorProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/BackendJwtUtils.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/JWTUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtGenerator/JwtGeneratorTestCase.java
  pom.xml
  resources/conf/config.toml.template
Labels: Choreo

#2987 Find connected adapters enforcers to a given adapter
  adapter/internal/discovery/xds/common/utils.go
  adapter/internal/discovery/xds/common/utils_test.go
  adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
  adapter/internal/discovery/xds/routercallbacks/router_callbacks.go
Labels: Type/Improvement

#2991 CC not starting with WSL issue fixed
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/JWTUtils.java
Labels: Type/Bug

#2998 Add dev script to build docker image for profiling CC memory/cpu
  dev-scripts/cc-router-debug-docker-image/README.md
  dev-scripts/cc-router-debug-docker-image/build-cc-router-debug-docker-image.sh
  dev-scripts/directory-structure-maker/README.md
Labels: Type/Docs

#3014 Fix init & build commands fail issue
  distribution/resources/bin/micro-gw.bat
Labels: ballerina-mgw

#3004 [main] Fix GroupId unmarshalling and update go profiling host to 127.0.0.1
  adapter/internal/api/restserver/config_restapi.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/messaging/notification_listener.go
  adapter/pkg/discovery/api/wso2/discovery/subscription/application.pb.go
  adapter/pkg/eventhub/types/types.go
  adapter/pkg/messaging/event_types.go
  api/proto/wso2/discovery/subscription/application.proto
  developer-guide.md
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/subscription/Application.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/subscription/ApplicationOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/subscription/ApplicationProto.java
Labels: Type/Bug

#3021 Update ingress TLS secrets
  resources/k8s-artifacts/choreo-connect/choreo-connect-ingress-tls-secret.yaml
Labels: Type/Bug

#3007 Add authority header to interceptor service calls
  adapter/internal/interceptor/interceptor.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/mgw_swagger_internal_test.go
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Constants.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockInterceptorServer.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Utils.java
  router/src/main/resources/interceptor/lib/interceptor.lua
Labels: Type/Bug
