Repository wso2/product-microgateway, pull requests merged in 2022-12, with the labels that each got.

#3153 Expose sandbox endpoint via a new vhost
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/swagger_test.go
  adapter/internal/oasparser/operator/operator_test.go
  adapter/pkg/synchronizer/types.go
  adapter/test-resources/envoycodegen/api_basic.yaml
  adapter/test-resources/envoycodegen/openapi_basic.yaml
  adapter/test-resources/envoycodegen/swagger_with_prod_sand_extensions.yaml
  resources/conf/config.toml.template
Labels: Type/New Feature, Choreo

#3144 Bugfix/jwks
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
Labels: Type/Bug

#3149 JWKS for choreo branch
  adapter/config/default_config.go
  adapter/config/parser.go
  adapter/config/types.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/pkg/discovery/api/wso2/discovery/config/enforcer/jwt_generator.pb.go
  adapter/pkg/discovery/api/wso2/discovery/config/enforcer/keypair.pb.go
  api/proto/wso2/discovery/config/enforcer/jwt_generator.proto
  api/proto/wso2/discovery/config/enforcer/keypair.proto
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/JWTGenerator.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/JWTGeneratorOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/JWTGeneratorProto.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/KeyPairProto.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/Keypair.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/KeypairOrBuilder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/DefaultAnalyticsEventPublisher.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/EnforcerConfig.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/AnalyticsConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/JwtConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/jwks/BackendJWKSDto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/jwks/JWKSRequestHandler.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/issuer/HttpTokenServerHandler.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/RestServer.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/RestServerInitializer.java
  enforcer-parent/enforcer/src/test/java/org/wso2/choreo/connect/enforcer/backend/jwt/BackendJwksTest.java
  enforcer-parent/enforcer/src/test/java/org/wso2/choreo/connect/enforcer/backend/jwt/BackendJwtTest.java
  enforcer-parent/enforcer/src/test/resources/keystore/mg.key
  enforcer-parent/enforcer/src/test/resources/keystore/mg.pem
  enforcer-parent/enforcer/src/test/resources/keystore/multipleCerts/cert.pem
  enforcer-parent/enforcer/src/test/resources/keystore/multipleCerts/mg.pem
  enforcer-parent/enforcer/src/test/resources/keystore/singleCert/cert.pem
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtGenerator/JwtGeneratorTestCase.java
  router/src/main/resources/Dockerfile
  router/src/main/resources/Dockerfile.ubuntu
Labels: Type/New Feature, Choreo

#3156 Update go-control-plane version as v0.10.3 and add rate limit xds files
  adapter/go.mod
  adapter/go.sum
  adapter/pkg/discovery/protocol/server/sotw/v3/server.go
  adapter/pkg/discovery/protocol/server/v3/server.go
Labels: Type/Task, Choreo

#3160 Environment based access token validation
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APISecurityConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/GatewayEnvTokenTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TokenUtil.java
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
Labels: Type/Improvement, Choreo

#3162 Fix issue installing go lint
  adapter/scripts/build.sh
Labels: Type/Task

#3166 Force to use bazel version 5.4.0
  envoy-filters/.bazelversion
  envoy-filters/mgw-source/filters/.bazelversion
Labels: Type/Task

#3164 Enable kid property on JWT header
  pom.xml
Labels: Choreo

#3170 [Choreo] Force to use bazel version 5.4.0
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/.bazelversion
Labels: Type/Task, Choreo

#3163 Rate limit JWKS endpoint
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/http_filters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtGenerator/JwtGeneratorTestCase.java
  integration/test-integration/src/test/resources/configs/jwt-generator-config.toml
  resources/conf/config.toml.template
Labels: Type/Task, Choreo

#3169 Notify CC chat when nightly build failed
  .github/workflows/nightly-integration-test.yml
Labels: Type/Task

#3173 [choreo] Add env related error code to FaultCodeClassifier
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/FaultCodeClassifier.java
Labels: Type/Bug, Choreo

#3142 [choreo] Rate-limit service support
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/http_filters.go
  adapter/internal/oasparser/envoyconf/internal_dtos.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/model/api_operation.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api_internal_test.go
  adapter/internal/oasparser/model/swagger_internal_test.go
  adapter/internal/oasparser/model/types.go
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendProd.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/ResponseConstants.java
  integration/test-integration/pom.xml
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/mockbackend/MockBackendServer.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithBackendTlsAndCorsDisabled.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithJwtConfigAndTransformer.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/APiDeployViaApictlTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/ratelimit/ApiLevelRatelimitTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/ratelimit/OperationLevelRatelimitTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/ratelimit/RateLimitUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/ApictlUtils.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
  integration/test-integration/src/test/resources/apiYaml/operation_level_ratelimit_api.yaml
  integration/test-integration/src/test/resources/apiYaml/ratelimit_api.yaml
  integration/test-integration/src/test/resources/configs/jwt-generator-config.toml
  integration/test-integration/src/test/resources/dockerCompose/apim-in-common-network-docker-compose.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  integration/test-integration/src/test/resources/openAPIs/operation_level_ratelimit_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/ratelimit_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
  pom.xml
  resources/conf/config.toml.template
  resources/conf/rate-limiter-config.yaml
Labels: Choreo

#3171 Force to use bazel version 5.4.0
  envoy-filters/.bazelversion
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/.bazelversion 
Labels: Type/Task

#3174 Fix error downloading apictl in Mac M1 for integration tests
  integration/test-integration/pom.xml
Labels: Type/Task
