Repository wso2/product-microgateway, pull requests merged in 2022-04, with the labels that each got.

#2832 Return error right at the beginning for apictl deploy/undeploy commands when control plane is enabled
  adapter/internal/api/apis_impl.go
  adapter/internal/api/restserver/config_restapi.go
Labels: Type/Bug

#2833 Bug fix: Default versioned APIs would be called when a versioned API is expected if it has the resource /*
  adapter/internal/discovery/xds/server.go
Labels: Type/Bug

#2836 [Int-Tests] Wait for OPA server startup using health check in Int Tests
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/MediationPolicyFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/opa/OPAClient.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apipolicy/APIPolicyTestCase.java
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls-with-opa-server.yaml
  integration/test-integration/src/test/resources/keystore/client-truststore.jks
Labels: Type/Task, test-improvements

#2838 [1.1.0] Performance Test Details
  performance/benchmarks/cpus-1/images/percentile.png
  performance/benchmarks/cpus-1/images/response_time_0ms.png
  performance/benchmarks/cpus-1/images/throughput.png
  performance/benchmarks/cpus-1/summary.csv
  performance/benchmarks/cpus-1/summary.md
  performance/benchmarks/cpus-2/images/percentile.png
  performance/benchmarks/cpus-2/images/response_time_0ms.png
  performance/benchmarks/cpus-2/images/throughput.png
  performance/benchmarks/cpus-2/summary.csv
  performance/benchmarks/cpus-2/summary.md
Labels: Type/Task

#2841 Update missing envoy config yaml update in Ubuntu Dockerfile
  router/src/main/resources/Dockerfile.ubuntu
Labels: Type/Task

#2840 Preparations for RC1 release
  integration/test-integration/src/test/resources/dockerCompose/apim-in-common-network-docker-compose.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls-with-opa-server.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  release-note.html
  remove-containers.sh
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/apim/apim-deployment.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  resources/license/LICENSE-ENFORCER.txt
Labels: Type/Task

#2842 Add integration tests for custom OPA request generator
  integration/test-integration/src/main/java/org/wso2/choreo/connect/tests/CustomOPARequestGenerator.java
  integration/test-integration/src/main/resources/META-INF/services/org.wso2.choreo.connect.enforcer.commons.opa.OPARequestGenerator
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/ChoreoConnectImpl.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithBackendTlsAndCorsDisabledWithOPA.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apipolicy/APIPolicyTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
  integration/test-integration/src/test/resources/apiYaml/api_policies.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls-with-opa-server.yaml
  integration/test-integration/src/test/resources/dockerVolumeMounts/opa-volume/policies/custom-policy.rego
  integration/test-integration/src/test/resources/openAPIs/api_policy_openAPI.yaml
  integration/test-integration/src/test/resources/policies/customOpaPolicy_v1.gotmpl
  integration/test-integration/src/test/resources/policies/customOpaPolicy_v1.yaml
  integration/test-integration/src/test/resources/policies/customOpaPolicy_v2.gotmpl
  integration/test-integration/src/test/resources/policies/customOpaPolicy_v2.yaml
Labels: Type/Task, test-improvements

#2846 Fixing API delete issue in standalone mode
  adapter/internal/discovery/xds/server.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
Labels: Type/Bug

#2844 Handle error when pulling from remote and format code
  adapter/internal/sourcewatcher/sourcewatcher.go
Labels: Type/Bug

#2856 Update Sample Filter to add wso2_public maven repository.
  samples/filters/sample-filter/pom.xml
Labels: Type/Improvement

#2854 Version name changes relevant to the 1.2.0 m1 release
  adapter/pom.xml
  distribution/pom.xml
  enforcer-parent/commons/pom.xml
  enforcer-parent/enforcer/pom.xml
  enforcer-parent/pom.xml
  integration/mock-backend-server/pom.xml
  integration/pom.xml
  integration/test-integration/pom.xml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls-with-opa-server.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  pom.xml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  router/pom.xml
Labels: Type/Task

#2863 Update k8s config changes for log configs
  resources/k8s-artifacts/choreo-connect/log4j2-configmap.yaml
  resources/k8s-artifacts/choreo-connect/logconfig-toml-configmap.yaml
Labels: Type/Task

#2868 TestContainers version upgrade
  integration/mock-backend-server/src/main/resources/Dockerfile
  pom.xml
Labels: Type/Task, Priority/Normal

#2851 Remove cluster header name from request to backend
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/ExistingApiTestCase.java
  integration/test-integration/src/test/resources/apim/1/apis/ExistingAPI.json
Labels: Type/Bug

#2869 [int-tests] Update tests to use API-M with a port offset of 1 same as cc dist
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/throttle/SubscriptionThrottlingTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TokenUtil.java
  integration/test-integration/src/test/resources/automation.xml
  integration/test-integration/src/test/resources/configs/cc-special-scenarios-with-apim.toml
  integration/test-integration/src/test/resources/configs/controlplane-enabled-config.toml
  integration/test-integration/src/test/resources/configs/vhost-deployment.toml
  integration/test-integration/src/test/resources/dockerCompose/apim-in-common-network-docker-compose.yaml
Labels: Type/Task, test-improvements

#2821 Fixing increased memory Consumption on connectivity issues
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/upload_files_timer.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/usagedata_uploader.bal
Labels: ballerina-mgw

#2874 [int-tests] Remove addtional test file
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/InternalKeyHeaderTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/apikey/InternalKeyHeaderTestCase.java
Labels: Type/Task

#2865 Add fixes related to handling trailing slash in path
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
Labels: Type/Bug, Choreo

#2887 Upgrade x/crypto package in go.mod
  adapter/go.mod
  adapter/go.sum
Labels: Type/Task

#2888 Upgrade x/crypto package in go.mod
  adapter/go.mod
  adapter/go.sum
Labels: Type/Task

#2884 Change azure-sdk-for-go version to 0.4.0 and go version to be 1.18
  .github/workflows/main.yml
  adapter/go.mod
  adapter/go.sum
  adapter/internal/messaging/azure_listener.go
  adapter/pkg/messaging/azure_connection.go
  adapter/pkg/messaging/azure_listener.go
  adapter/scripts/build.sh
  developer-guide.md
Labels: Type/Task, Choreo

#2897 [samples] Add mock impl openapi
  samples/openAPI-definitions/mock-impl-sample.yaml
Labels: Type/Task

#2900 Updating base images and maven dependancies
  adapter/go.mod
  adapter/go.sum
  adapter/src/main/resources/Dockerfile
  adapter/src/main/resources/Dockerfile.ubuntu
  enforcer-parent/enforcer/src/main/resources/Dockerfile.ubuntu
  pom.xml
Labels: Type/Task

#2892 Adding Repos
  .github/ISSUE_TEMPLATE/config.yaml
  pom.xml
Labels: Type/Bug

#2902 Fix invocationContext field in interceptor OpenAPI
  resources/interceptor-service-open-api.yaml
  samples/interceptors/ballerina/cc-sample-xml-interceptor/types.bal
  samples/interceptors/golang/go-interceptor-server-generated/api/swagger.yaml
  samples/interceptors/golang/go-interceptor-server-generated/go/model_request_handler_request_body.go
  samples/interceptors/java/spring-server-generated/src/main/java/io/swagger/model/RequestHandlerRequestBody.java
  samples/interceptors/nodejs/nodejs-interceptor-server-generated/api/openapi.yaml
Labels: Type/Bug, Docs/Has Impact
