Repository wso2/product-microgateway, pull requests merged in 2023-12, with the labels that each got.

#3470 Resource path content length validation
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/oasparser/model/swagger.go
  adapter/internal/oasparser/model/swagger_internal_test.go
  adapter/internal/oasparser/model/types.go
  resources/conf/config.toml.template
Labels: Choreo

#3465 Add JDK17 support for Microgateway
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/resources/bin/micro-gw
Labels: ballerina-mgw

#3469 Add downstream tls configs
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/oasparser/envoyconf/listener.go
  resources/conf/config.toml.template
Labels: Type/Improvement
