Repository wso2/product-microgateway, pull requests merged in 2023-05, with the labels that each got.

#3347 [choreo] Add environmentId to analytics events
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/pkg/discovery/api/wso2/discovery/api/api.pb.go
  adapter/pkg/synchronizer/types.go
  api/proto/wso2/discovery/api/api.proto
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/APIConfig.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/Api.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoAnalyticsProvider.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/MetadataConstants.java
  pom.xml
Labels: Choreo

#3349 [choreo] add gateway accessibility type to configs
  adapter/config/default_config.go
  adapter/config/parser.go
  adapter/config/types.go
  adapter/internal/adapter/adapter.go
  adapter/internal/common/constants.go
  adapter/internal/ga/api_event_listener.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/pkg/messaging/event_types.go
  resources/conf/config.toml.template
Labels: Choreo

#3350 [choreo] fix: rename gateway accessibility type map json tag name
  adapter/pkg/messaging/event_types.go
Labels: Choreo

#3351 fix: use RetrieveRuntimeArtifacts endpoint to fetch APIs in RetryFetchingAPIs when dynamic environments are enabled
  adapter/internal/adapter/adapter.go
Labels: Choreo

#3353 Upgrade Apache Tomcat version
  pom.xml
Labels: Type/Task

#3354 Upgrade Alpine version of Enforcer
  enforcer-parent/enforcer/src/main/resources/Dockerfile
Labels: Type/Task

#3358 [choreo] Add dynamic environment support with global adapter
  adapter/internal/adapter/adapter.go
  adapter/internal/ga/client.go
Labels: Choreo

#3359 Limit retries to fetch the runtime artifacts.
  adapter/internal/synchronizer/apis_fetcher.go
Labels: Type/Task, Choreo

#3360 [choreo] upgrade envoy version to 1.24.7
  router/src/main/resources/Dockerfile
Labels: Type/Task, Choreo

#3363 [choreo] Include Environment name in GA API event
  adapter/internal/ga/api_event_listener.go
  adapter/internal/ga/client.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/pkg/discovery/api/wso2/discovery/ga/api.pb.go
  api/proto/wso2/discovery/ga/api.proto
Labels: Type/Task, Choreo

#3365 [choreo] bug fix: call StartConsumeGAAPIChannel when the startup APIs list is completed
  adapter/internal/adapter/adapter.go
Labels: Type/Task, Choreo

#3364 Change log level of subscription validation failure
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
Labels: Affected/3.2.0, ballerina-mgw
