Repository wso2/product-microgateway, pull requests merged in 2023-08, with the labels that each got.

#3409 Merge branch 'choreo-add-vhost-to-event' to 'choreo'
  adapter/pkg/discovery/protocol/cache/v3/resource.go
  adapter/pkg/messaging/event_types.go
Labels: Type/Task, Choreo

#3370 Merge feature/dynamic-env with choreo
  adapter/pkg/discovery/protocol/cache/v3/resource.go
Labels: Type/Task, Choreo

#3411 Temporarily disable organization Purge ASB topic subscription
  adapter/pkg/messaging/azure_connection.go
Labels: Type/Task, Choreo

#3415 Implement semantic version based intelligent routing for APIs
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/discovery/xds/semantic_versioning.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/pkg/loggers/logger.go
  adapter/pkg/semanticversion/semantic_version.go
Labels: Choreo

#3416 Load Adapter Certificates from the System Certificates
  adapter/pkg/tlsutils/tls_utils.go
Labels: Type/Task, Choreo

#3417 Update sample with the status code change
  samples/interceptors/ballerina/README.md
  samples/interceptors/ballerina/cc-sample-xml-interceptor/interceptor-service-open-api_service.bal
  samples/interceptors/ballerina/cc-sample-xml-interceptor/types.bal
Labels: Type/Docs

#3420 [choreo] Temporarily add env variable to duplicate vhost with organization ID
  adapter/internal/discovery/xds/server.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/APIFactory.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/EnvVarConfig.java
Labels: Type/Task, Choreo

#3424 Bug fix: Microsoft jwks payload is not pulled due to inavailablility of algorithm
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/JWTUtils.java
  enforcer-parent/enforcer/src/test/java/org/wso2/choreo/connect/enforcer/util/JWTUtilsTest.java
Labels: Type/Bug, Choreo

#3426 Integration test pom file change to display the test logs
  .github/workflows/main.yml
  integration/test-integration/pom.xml
Labels: Choreo
