Repository wso2/product-microgateway, pull requests merged in 2023-07, with the labels that each got.

#3395 Support JSON Access Log format
  adapter/internal/oasparser/envoyconf/access_loggers.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/pkg/config/log_types.go
  resources/conf/log_config.toml
Labels: Type/Improvement, Choreo

#3396 Rename JSON keys of the access log
  adapter/pkg/config/log_types.go
  resources/conf/log_config.toml
Labels: Type/Task, Choreo

#3398 [Improvement] Improve Logs to Include the Local adapter label assigned.
  adapter/internal/ga/client.go
Labels: Type/Task, Choreo

#3400 Access log api UUID from enforcer
  adapter/pkg/config/log_types.go
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/RequestContext.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/ResponseObject.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/RouterAccessLogConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/cors/CorsFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/HttpRequestHandler.java
  resources/conf/log_config.toml
Labels: Type/Improvement, Choreo

#3401 [choreo] Temporary changes for migrating to new vhost format
  adapter/internal/discovery/xds/server.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/APIFactory.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/EnvVarConfig.java
Labels: Type/Task, Choreo

#3376 Implement semantic version based intelligent routing for APIs
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/discovery/xds/semantic_versioning.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/pkg/loggers/logger.go
  adapter/pkg/semanticversion/semantic_version.go
Labels: Type/Task, Choreo

#3407 Move semantic version comparison to package
  adapter/internal/discovery/xds/semantic_versioning.go
  adapter/pkg/semanticversion/semantic_version.go
Labels: Type/Task, Choreo

#3406 Update analytics publisher client version
  pom.xml
Labels: Choreo
