Repository wso2/product-microgateway, pull requests merged in 2023-09, with the labels that each got.

#3429 Accept special chars in resource path of the Open API
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/ratelimit/ApiLevelRatelimitTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/ratelimit/OperationLevelRatelimitTestCase.java
  integration/test-integration/src/test/resources/apiYaml/operation_level_ratelimit_api.yaml
  integration/test-integration/src/test/resources/apiYaml/ratelimit_api.yaml
  integration/test-integration/src/test/resources/openAPIs/operation_level_ratelimit_openAPI.yaml
  integration/test-integration/src/test/resources/openAPIs/ratelimit_openAPI.yaml
Labels: Choreo

#3425 Aud claim addition in backend JWTs
  .github/workflows/main.yml
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/types.go
  adapter/pkg/discovery/api/wso2/discovery/api/api.pb.go
  adapter/pkg/discovery/api/wso2/discovery/api/backend_jwt_configuration.pb.go
  api/proto/wso2/discovery/api/api.proto
  api/proto/wso2/discovery/api/backend_jwt_configuration.proto
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/APIConfig.java
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/BackendJWTConfiguration.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/Api.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiProto.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/BackendJWTConfiguration.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/BackendJWTConfigurationOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/BackendJWTConfigurationProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/issuer/JWTIssuerImpl.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/ResponseConstants.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithBackendTlsAndCorsDisabled.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtGenerator/BackendJWTWithAudClaimTestcase.java
  integration/test-integration/src/test/resources/apiYaml/backendJWT_with_aud_claim.yaml
  integration/test-integration/src/test/resources/openAPIs/backend_security_with_aud_claim.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
  pom.xml
Labels: Type/Improvement, Choreo

#3430 Remove /health and /ready from Access Logs
  adapter/internal/oasparser/envoyconf/access_loggers.go
  adapter/pkg/config/log_types.go
  integration/mock-backend-server/src/main/resources/Dockerfile
  resources/conf/log_config.toml
Labels: Type/Improvement, Choreo

#3431 Template envoy.yaml in Router Dockerfile
  adapter/src/main/resources/Dockerfile
  enforcer-parent/enforcer/src/main/resources/Dockerfile
  router/src/main/assembly/assembly.xml
  router/src/main/resources/Dockerfile
  router/src/main/resources/docker-entrypoint.sh
  router/src/main/resources/envoy.yaml.template
Labels: Choreo

#3433 Update host regex to filter kube probe logs
  adapter/internal/oasparser/envoyconf/access_loggers.go
Labels: Type/Task, Choreo

#3434 Rate limiter health check
  adapter/internal/adapter/adapter.go
  adapter/pkg/health/health.go
  router/src/main/resources/Dockerfile
  router/src/main/resources/docker-entrypoint.sh
Labels: Type/Improvement

#3435 Bug fix: NPE when a user manually sends the key manager registration without apim property inside environment
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/keymgt/KeyManagerHolder.java
Labels: Choreo

#3437 Bug fix: Path Parameter forwarding issue when semantic versioning is enabled.
  adapter/internal/discovery/xds/semantic_versioning.go
Labels: Type/Bug, Choreo
