Repository wso2/product-microgateway, pull requests merged in 2023-03, with the labels that each got.

#3282 Update dependancies
  adapter/go.mod
  adapter/go.sum
  enforcer-parent/enforcer/pom.xml
  integration/mock-backend-server/pom.xml
  pom.xml
Labels: Type/Task

#3288 Updating crypto version
  adapter/go.mod
  adapter/go.sum
Labels: Type/Task

#3277 Remove sandbox cluster creation
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/internal_dtos.go
  adapter/internal/oasparser/envoyconf/listener_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/QSGAndSwaggerTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/circuitBreakers/CircuitBreakersTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/endpoints/BackendSecurityTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/endpoints/ProductionSandboxTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/retry/RetryTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/timeouts/TimeoutTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/vhost/VhostAPICtlTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BackendSecurityTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/ExistingApiTestCase.java
Labels: Choreo

#3296 Removing ca certs maintained for the Router
  resources/security/ca-certificates.crt
  router/src/main/assembly/assembly.xml
  router/src/main/resources/Dockerfile
Labels: Type/Task

#3294 Updating APIM version to rc1
  adapter/internal/oasparser/envoyconf/compression_filter.go
  enforcer-parent/enforcer/src/test/resources/keystore/multipleCerts/cert.pem
  enforcer-parent/enforcer/src/test/resources/keystore/singleCert/cert.pem
  integration/test-integration/pom.xml
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/security/APIKeyTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
  integration/test-integration/src/test/resources/database/WSO2AM_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2CARBON_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2SHARED_DB.mv.db
  integration/test-integration/src/test/resources/dockerCompose/apim-in-common-network-docker-compose.yaml
  integration/test-integration/src/test/resources/keystore/client-truststore.jks
  integration/test-integration/src/test/resources/keystore/wso2carbon.jks
  pom.xml
  resources/adapter/security/truststore/controlplane.pem
  resources/conf/config.toml.template
  resources/docker-compose/apim/docker-compose.yaml
  resources/enforcer/security/truststore/wso2carbon.pem
  resources/k8s-artifacts/apim/apim-deployment.yaml
  resources/k8s-artifacts/choreo-connect/adapter-truststore-secret.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  resources/k8s-artifacts/choreo-connect/enforcer-truststore-secret.yaml
Labels: Type/Task

#3229 [Choreo] Enable Backend JWT per Api
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/types.go
  adapter/pkg/discovery/api/wso2/discovery/api/api.pb.go
  api/proto/wso2/discovery/api/api.proto
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/APIConfig.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/Api.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithJwtConfig.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtGenerator/JwtGeneratorTestCase.java
  integration/test-integration/src/test/resources/apiYaml/per_api_jwt.yaml
  integration/test-integration/src/test/resources/openAPIs/per_api_jwt_openAPI.yaml
Labels: Choreo

#3297 Fixing websocket analytics
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoAnalyticsForWSProvider.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/DefaultAnalyticsEventPublisher.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/metrics/MetricsUtils.java
Labels: Type/Bug

#3299 Add performance results of version 1.2.0
  performance/benchmarks/cpus-1/images/percentile.png
  performance/benchmarks/cpus-1/images/response_time_0ms.png
  performance/benchmarks/cpus-1/images/throughput.png
  performance/benchmarks/cpus-1/summary.csv
  performance/benchmarks/cpus-1/summary.md
  performance/benchmarks/cpus-2/images/percentile.png
  performance/benchmarks/cpus-2/images/response_time_0ms.png
  performance/benchmarks/cpus-2/images/throughput.png
  performance/benchmarks/cpus-2/summary.csv
  performance/benchmarks/cpus-2/summary.md
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#3301 Build APIM Docker image instead of pulling from DockerHub
  dev-scripts/code-coverage/prepare-files-before-int-tests.sh
  distribution/src/main/assembly/assembly.xml
  integration/test-integration/src/test/resources/dockerCompose/apim-in-common-network-docker-compose.yaml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/apim/dockerfiles/apim/Dockerfile
  resources/docker-compose/apim/dockerfiles/apim/docker-entrypoint.sh
  resources/k8s-artifacts/apim/apim-deployment.yaml
Labels: Type/Task

#3305 Updating analytics publisher client version
  pom.xml
  samples/analytics-custom-data-provider/pom.xml
Labels: Type/Task

#3303 Fix critical and high fossa scan issues
  .fossa.yml
  adapter/go.mod
  adapter/go.sum
  enforcer-parent/enforcer/pom.xml
  pom.xml
Labels: Choreo

#3311 Bump golang.org/x/net from 0.4.0 to 0.7.0
  adapter/go.mod
  adapter/go.sum
Labels: Choreo

#3312 [choreo] Upgrade grpc-health-probe version
  pom.xml
Labels: Choreo

#3309 Remove unnecessary headers associated with rate limit filter
  adapter/internal/oasparser/envoyconf/http_filters.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/ratelimit/ApiLevelRatelimitTestCase.java
Labels: Type/Task, Choreo

#3314 Update Dev Scripts for 1.2.0 U2 and Debug Images
  dev-scripts/cc-router-debug-docker-image/README.md
  dev-scripts/directory-structure-maker/README.md
  dev-scripts/directory-structure-maker/directory-structure-maker.sh
  dev-scripts/directory-structure-maker/docker-image-builder.sh
  dev-scripts/private-registry-images/build-private-registry-images.sh
  integration/test-integration/pom.xml
Labels: Type/Task

#3313 Remove sandbox cluster creation
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/internal_dtos.go
  adapter/internal/oasparser/envoyconf/listener_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/QSGAndSwaggerTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/circuitBreakers/CircuitBreakersTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/endpoints/BackendSecurityTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/endpoints/ProductionSandboxTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/retry/RetryTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/timeouts/TimeoutTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/vhost/VhostAPICtlTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BackendSecurityTestCase.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/ExistingApiTestCase.java
Labels: Choreo

#3322 Bug fix: Old API deployment fails due to not having the throttlingLimit Property
  adapter/internal/oasparser/model/api_yaml.go
  adapter/internal/oasparser/model/api_yaml_test.go
  adapter/internal/oasparser/model/types.go
  integration/test-integration/src/test/resources/apiYaml/operation_level_ratelimit_api.yaml
Labels: Type/Bug, Choreo

#3323 Upgrade Ballerina platform version to 1.2.37
  pom.xml
Labels: ballerina-mgw

#3325 [Choreo] Fix for rate-limit undefined scenario
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/types.go
  integration/test-integration/src/test/resources/openAPIs/operation_level_ratelimit_openAPI.yaml
Labels: Type/Bug, Priority/Normal, Choreo

#3328 upgrade envoy version to 1.24.2 and remove deprecated methods
  adapter/internal/discovery/xds/consul.go
  adapter/internal/ga/client_test.go
  adapter/internal/oasparser/envoyconf/access_loggers.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/http_filters.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/listener_test.go
  adapter/internal/oasparser/envoyconf/response_mapper.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/MetadataConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/interceptor/InterceptorRequestFlowTestcase.java
  resources/envoy.yaml
  router/src/main/resources/Dockerfile
Labels: Type/Improvement, Choreo
