Repository wso2/product-microgateway, pull requests merged in 2023-02, with the labels that each got.

#3220 Authentication Token should be passed to the backend if the security is disabled
  dev-scripts/remove-containers.sh
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/extensions/DisableSecurityTestCase.java
  integration/test-integration/src/test/resources/dockerCompose/backend-service-gql.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls-with-opa-server.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-cacert-mounted-mtls.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  integration/test-integration/src/test/resources/openAPIs/disable_security_openAPI.yaml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#3234 [main] Adapter base image version upgrade
  adapter/src/main/resources/Dockerfile
Labels: Type/Task, Priority/Normal

#3228 [3.2.x] Add change to remove file if it is already uploaded
  components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/upload_files_timer.bal
Labels: ballerina-mgw

#3237 [choreo] Adding KM notification support via ASB
  adapter/internal/messaging/km_listener.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/messaging/notification_listener_test.go
  adapter/pkg/eventhub/types/types.go
  adapter/pkg/messaging/event_types.go
  adapter/test-resources/keymgt-events/add_km1.txt
  adapter/test-resources/keymgt-events/add_km2.txt
  adapter/test-resources/keymgt-events/delete_km2.txt
  adapter/test-resources/keymgt-events/update_km2.txt
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/keymgt/KeyManagerHolder.java
Labels: Choreo

#3235 [choreo] Base images and dependency version upgrades
  adapter/src/main/resources/Dockerfile
  enforcer-parent/enforcer/pom.xml
  enforcer-parent/enforcer/src/main/resources/Dockerfile
  pom.xml
Labels: Type/Task, Priority/Normal

#3212 Add changes for dynamic environment support in choreo
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/adapter/adapter.go
  adapter/internal/common/constants.go
  adapter/internal/ga/api_event_listener.go
  adapter/internal/messaging/notification_listener.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/pkg/messaging/event_types.go
  adapter/pkg/synchronizer/apis_fetcher.go
  resources/conf/config.toml.template
Labels: Type/Task, Choreo

#3204 backend JWT kid property and JWKS rate limiting
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/discovery/xds/marshaller.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/http_filters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/pkg/discovery/api/wso2/discovery/config/enforcer/jwt_generator.pb.go
  api/proto/wso2/discovery/config/enforcer/jwt_generator.proto
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/JWTGenerator.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/JWTGeneratorOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/config/enforcer/JWTGeneratorProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtGenerator/JwtGeneratorTestCase.java
  integration/test-integration/src/test/resources/configs/jwt-generator-config.toml
  pom.xml
  resources/conf/config.toml.template
Labels: Type/Improvement

#3226 Move Enforcer docker image from Ubuntu to Alpine
  enforcer-parent/enforcer/src/main/resources/Dockerfile
Labels: Type/Task

#3244 Fix intermittent test failures in build pipeline
  adapter/go.mod
  adapter/internal/synchronizer/api_fetcher_test.go
Labels: Type/Bug, Choreo

#3240 Update API Manager version to v4.2.0-beta
  enforcer-parent/enforcer/pom.xml
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoAnalyticsForWSProvider.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoAnalyticsProvider.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/MetadataConstants.java
  integration/test-integration/src/test/resources/database/WSO2AM_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2CARBON_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2MB_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2SHARED_DB.mv.db
  integration/test-integration/src/test/resources/dockerCompose/apim-in-common-network-docker-compose.yaml
  pom.xml
  resources/docker-compose/apim/docker-compose.yaml
  resources/k8s-artifacts/apim/apim-deployment.yaml
Labels: Type/Task

#3249 Fix CORS failure when invoking APIs with API Policies
  adapter/go.mod
  adapter/go.sum
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apipolicy/APIPolicyPerOperationTestCase.java
  pom.xml
Labels: Type/Bug

#3251 [main] Enforcer and Adapter base image update
  adapter/src/main/resources/Dockerfile
  enforcer-parent/enforcer/src/main/resources/Dockerfile
Labels: Type/Task, Priority/Normal

#3254 [3.2.x] Add swagger-core dependency to the POM
  components/micro-gateway-cli/pom.xml
  pom.xml
Labels: ballerina-mgw

#3258 Support mTLS authentication for GraphQL APIs
  adapter/internal/discovery/xds/server.go
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/GraphQLAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/graphql/GraphQLQueryAnalysisFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
Labels: Type/Bug

#3259 [choreo] bug fix: set xds cache under a common label for dynamic environments
  adapter/internal/discovery/xds/server.go
Labels: Choreo

#3261 Adding otlp tracing support for Envoy
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/listener_test.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
Labels: Type/Improvement

#3262 Remove Ubuntu images
  .github/workflows/main.yml
  .github/workflows/nightly-integration-test.yml
  adapter/pom.xml
  adapter/scripts/build.sh
  adapter/src/main/assembly/assembly.xml
  adapter/src/main/resources/Dockerfile.ubuntu
  build-ubuntu-multi-platform-images.sh
  enforcer-parent/enforcer/pom.xml
  enforcer-parent/enforcer/src/main/assembly/assembly.xml
  enforcer-parent/enforcer/src/main/resources/Dockerfile.ubuntu
  router/src/main/resources/Dockerfile.ubuntu
Labels: Type/Task

#3263 Template envoy.yaml in Router Dockerfile
  adapter/src/main/resources/Dockerfile
  enforcer-parent/enforcer/src/main/resources/Dockerfile
  router/src/main/assembly/assembly.xml
  router/src/main/resources/Dockerfile
  router/src/main/resources/docker-entrypoint.sh
  router/src/main/resources/envoy.yaml.template
Labels: Type/Task

#3267 Adding tls server name to check_health
  adapter/src/main/resources/check_health.sh
  enforcer-parent/enforcer/src/main/resources/check_health.sh
Labels: Type/Bug

#3268 [choreo] bug fix: API not deleted with event, when setting xds cache under a common label for dynamic environments
  adapter/internal/discovery/xds/server.go
Labels: Choreo

#3265 Preparing for 1.2.0-beta release
  dev-scripts/remove-containers.sh
  integration/test-integration/src/test/resources/dockerCompose/cc-cacert-mounted-mtls.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#3271 Correct developer version as 1.2.0-beta2-SNAPSHOT
  adapter/pom.xml
  distribution/pom.xml
  enforcer-parent/commons/pom.xml
  enforcer-parent/enforcer/pom.xml
  enforcer-parent/pom.xml
  integration/mock-backend-server/pom.xml
  integration/pom.xml
  integration/test-integration/pom.xml
  pom.xml
  router/pom.xml
Labels: Type/Task

#3273 Fixing issues in custom data provider
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/DefaultAnalyticsEventPublisher.java
  samples/analytics-custom-data-provider/pom.xml
Labels: Type/Bug

#3274 Update License text files for 1.2.0 Beta
  resources/license/LICENSE-ADAPTER.txt
  resources/license/LICENSE-ENFORCER.txt
  resources/license/LICENSE-ROUTER.txt
Labels: Type/Task

#3279 Adding .fossa.yml to skip samples
  .fossa.yml
  enforcer-parent/enforcer/pom.xml
  pom.xml
Labels: Type/Task
