Repository wso2/product-microgateway, pull requests merged in 2023-06, with the labels that each got.

#3371 Set the key type in Auth Context for mTLS
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/mtls/MTLSAuthenticator.java
Labels: Type/Improvement

#3373 [choreo] log fix: print discovery response size for ga discovery response
  adapter/internal/ga/client.go
Labels: Type/Task, Choreo

#3375 Update json-smart, callhome and ballerina platform versions
  components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
  components/micro-gateway-core/src/main/ballerina/Ballerina.toml
  pom.xml
Labels: ballerina-mgw

#3380 [choreo] Upgrade github.com/lestrrat-go/jwx version
  adapter/go.mod
  adapter/go.sum
Labels: Type/Task, Choreo

#3382 [choreo] Dynamically validate environment name in audience claim
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/pkg/discovery/api/wso2/discovery/api/api.pb.go
  api/proto/wso2/discovery/api/api.proto
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/APIConfig.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/Api.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
Labels: Type/Task, Choreo

#3390 Fix Integration Test - Update expired mTLS cert
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
  integration/test-integration/src/test/resources/certs/client_certificate.crt
  integration/test-integration/src/test/resources/certs/rootCA.crt
  integration/test-integration/src/test/resources/keystore/client-keystore.jks
  integration/test-integration/src/test/resources/keystore/invalid-client-keystore.jks
Labels: Type/Task

#3278 Aws lambda support for Choreo-Connect
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/constants/constants.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/http_filters.go
  adapter/internal/oasparser/envoyconf/internal_dtos.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/routes_configs.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/internal/oasparser/model/api_yaml.go
  adapter/internal/oasparser/model/common.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/mgw_swagger_dummy.go
  adapter/internal/oasparser/model/mgw_swagger_internal_test.go
  adapter/internal/oasparser/model/resource.go
  adapter/pkg/discovery/api/wso2/discovery/api/api.pb.go
  adapter/test-resources/envoycodegen/awslambda_api.yaml
  api/proto/wso2/discovery/api/api.proto
  enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/APIConfig.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/Api.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiOrBuilder.java
  enforcer-parent/enforcer/src/main/gen/org/wso2/choreo/connect/discovery/api/ApiProto.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/Constants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/MockImplUtils.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Constants.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/EchoService.java
  integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockServices.java
  integration/mock-backend-server/src/main/resources/echo-service.pem
  integration/mock-backend-server/src/main/resources/echo-service.pkcs12
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithAwsLambdaBackend.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/awsLambda/AwsLambdaSupportTestCase.java
  integration/test-integration/src/test/resources/apiYaml/aws_lambda_api.yaml
  integration/test-integration/src/test/resources/certs/rootCA.crt
  integration/test-integration/src/test/resources/configs/aws-lambda-config.toml
  integration/test-integration/src/test/resources/dockerCompose/aws-lambda.yaml
  integration/test-integration/src/test/resources/openAPIs/aws_lambda_openAPI.yaml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
  resources/conf/config.toml.template
  router/src/main/resources/interceptor/lib/interceptor.lua
Labels: Type/New Feature

#3386 Include API UUID in Access logs
  adapter/internal/oasparser/envoyconf/internal_dtos.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/pkg/config/log_types.go
  resources/conf/log_config.toml
Labels: Choreo
