Repository wso2/product-microgateway, pull requests merged in 2023-10, with the labels that each got.

#3428 Add Prometheus Support for Choreo Connect
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/go.mod
  adapter/go.sum
  adapter/internal/adapter/adapter.go
  adapter/pkg/metrics/metrics.go
  adapter/pkg/metrics/types.go
  enforcer-parent/enforcer/pom.xml
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/metrics/jmx/api/ExtAuthMetricsMXBean.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/metrics/jmx/impl/ExtAuthMetrics.java
  enforcer-parent/enforcer/src/main/resources/prometheus-jmx-config.yml
  integration/test-integration/pom.xml
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithPrometheusMetricsEnabled.java
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/metrics/PrometheusMetricEndpointsTestCase.java
  integration/test-integration/src/test/resources/configs/prometheus-metrics-enabled.toml
  integration/test-integration/src/test/resources/dockerCompose/cc-prometheus-metrics.yaml
  integration/test-integration/src/test/resources/dockerVolumeMounts/metricConfigs/prometheus-jmx-config.yml
  integration/test-integration/src/test/resources/testng-cc-standalone.xml
  pom.xml
  resources/conf/config.toml.template
Labels: Choreo

#3441 [3.2.x] Upgrade internal JRE version to jdk8u382
  distribution/pom.xml
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  distribution/resources/bin/micro-gw
  distribution/resources/bin/micro-gw.bat
  distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
  distribution/src/main/assembly/macos_bin.xml
  tests/pom.xml
Labels: Type/Improvement, ballerina-mgw

#3449 Adding apiUUID List to API ReFetching
  adapter/internal/adapter/adapter.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/pkg/synchronizer/apis_fetcher.go
Labels: Choreo

#3452 Adding necessary data populations for Moesif Integration
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/AnalyticsConstants.java
Labels: Type/Improvement
