Repository wso2/product-microgateway, pull requests merged in 2023-01, with the labels that each got.

#3175 Remove padding from the KID value in backendJWT
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
  pom.xml
Labels: Type/Improvement, Choreo

#3177 [main] Dependency version upgrades
  enforcer-parent/enforcer/pom.xml
  pom.xml
Labels: Type/Task

#3183 [xDS]: Increase channel capacity in sotw v3 server
  adapter/pkg/discovery/protocol/server/sotw/v3/server.go
Labels: Type/Improvement

#3158 Stopped publishing analytics logs for JWKS requests
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/DefaultAnalyticsEventPublisher.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/AnalyticsConstants.java
Labels: Type/Bug

#3184 [Choreo][xDS]: Increase channel capacity in sotw v3 server
  adapter/pkg/discovery/protocol/server/sotw/v3/server.go
Labels: Type/Improvement, Choreo

#3176 Testkey handler flushes channel after writing response
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/issuer/HttpTokenServerHandler.java
Labels: Type/Bug, Choreo

#3187 Fixing test failures
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
Labels: Type/Task

#3188 Base Image Update for Adapter and Enforcer
  adapter/src/main/resources/Dockerfile
  enforcer-parent/enforcer/src/main/resources/Dockerfile
  resources/k8s-artifacts/choreo-connect/choreo-connect-service.yaml
Labels: Type/Improvement

#3192 [main] Dependency version upgrades
  pom.xml
Labels: Type/Task, Priority/Normal, java

#3191 Preparing for 1.2.0-m1 release
  dev-scripts/code-coverage/prepare-files-before-int-tests.sh
  dev-scripts/remove-containers.sh
  integration/test-integration/pom.xml
  integration/test-integration/src/test/resources/dockerCompose/cc-cacert-mounted-mtls.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task

#3193 Updating dependancy versions
  adapter/go.mod
  adapter/go.sum
  pom.xml
Labels: Type/Task

#3197 Updating APIM version
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/throttle/KeyTemplateThrottlingTestCase.java
  integration/test-integration/src/test/resources/database/WSO2AM_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2CARBON_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2MB_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2METRICS_DB.mv.db
  integration/test-integration/src/test/resources/database/WSO2SHARED_DB.mv.db
  integration/test-integration/src/test/resources/dockerCompose/apim-in-common-network-docker-compose.yaml
  pom.xml
  resources/docker-compose/apim/docker-compose.yaml
  resources/k8s-artifacts/apim/apim-deployment.yaml
Labels: Type/Task

#3205 [choreo] Dependency version upgrades
  pom.xml
Labels: Type/Task, Priority/Normal, Choreo

#3185 [Choreo][xDS]: Log improvement to track request type in enforcer callbacks
  adapter/internal/discovery/xds/common/utils.go
  adapter/internal/discovery/xds/common/utils_test.go
Labels: Choreo

#3208 Merge envInfo by deployed revision
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/synchronizer/api_fetcher_test.go
  adapter/internal/synchronizer/apis_fetcher.go
Labels: Type/Bug

#3210 [Choreo] Adapter: update azsb and grpc health probe
  adapter/go.mod
  adapter/go.sum
  pom.xml
Labels: Type/Task

#3214 Upgrade jmx_prometheus_javaagent to 0.17.2
  distribution/LICENSE-RUNTIME.txt
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
  pom.xml
Labels: ballerina-mgw

#3209 [main] Dependency version upgrades
  pom.xml
Labels: Type/Task, Priority/Normal, java

#3216 Update Envoy version to v1.24.1
  adapter/go.mod
  adapter/go.sum
  adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
  adapter/internal/discovery/xds/routercallbacks/router_callbacks.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/http_filters.go
  adapter/internal/oasparser/envoyconf/response_mapper.go
  adapter/pkg/discovery/protocol/server/sotw/v3/server.go
  adapter/pkg/discovery/protocol/server/v3/server.go
  dev-scripts/remove-containers.sh
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/MetadataConstants.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/filter.cc
  envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/filter.h
  integration/test-integration/src/test/resources/dockerCompose/backend-service-gql.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-tls-with-opa-server.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
  integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-cacert-mounted-mtls.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  pom.xml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/envoy.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
  router/src/main/resources/Dockerfile
Labels: Type/Improvement

#3219 Preparing for 1.2.0-alpha release
  dev-scripts/remove-containers.sh
  enforcer-parent/enforcer/src/main/resources/Dockerfile
  integration/test-integration/src/test/resources/dockerCompose/cc-cacert-mounted-mtls.yaml
  integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
  resources/docker-compose/apim/docker-compose.yaml
  resources/docker-compose/docker-compose.yaml
  resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
  resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Labels: Type/Task
