Repository wso2/product-microgateway, pull requests merged in 2024-08, with the labels that each got.

#3550 Add go control plane validation for routes, clusters and endpoints
  adapter/internal/oasparser/envoyconf/access_loggers.go
  adapter/internal/oasparser/envoyconf/dns_resolver.go
  adapter/internal/oasparser/envoyconf/http_filters.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
Labels: Type/Improvement

#3561 Add envoy config route validations for emoticons and substrings
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
Labels: Type/Improvement

#3573 [Chore] Fix issue when security is disabled and testing from WS Console
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/UnsecuredAPIAuthenticator.java
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/InternalAPIKeyUtils.java
Labels: Type/Bug

#3575 [Choreo] Remove unused constants from the routes_with_clusters file
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
Labels: Choreo
