Repository wso2/product-microgateway, pull requests merged in 2024-01, with the labels that each got.

#3474 Fix prometheus version issue
  distribution/LICENSE-RUNTIME.txt
  distribution/resources/bin/gateway
  distribution/resources/bin/gateway.bat
Labels: ballerina-mgw

#3477 Validate the request timestamp in the event DTO which is published to analytics
  components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
Labels: ballerina-mgw

#3479 Fix security related issues with basic auth flow
  components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
  components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/basic_auth_handler.bal
Labels: ballerina-mgw

#3481 [choreo] Bump grpc health probe version
  pom.xml
Labels: Choreo

#3475 Supporting whitelisted organizations to access any environment with Production tokens
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
Labels: Type/Improvement, Choreo

#3482 [choreo] Upgrade github.com/lestrrat-go/jwx version
  adapter/go.mod
  adapter/go.sum
Labels: Choreo

#3483 Add a log to indicate errors related to JWKS request in enforcer
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
Labels: Type/Task

#3485 Internal-endpoint-testing: handle x-choreo-test-session-id header cors config
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/oasparser/envoyconf/constants.go
  adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/security/CorsTestCase.java
Labels: Choreo

#3488 [Choreo] Addition of info log to recognise the rate-limit level
  adapter/internal/discovery/xds/rate_limiter_cache.go
  adapter/internal/oasparser/model/mgw_swagger.go
Labels: Choreo
