Repository wso2/product-microgateway, pull requests merged in 2024-03, with the labels that each got.

#3495 Chunk fetching APIs from Control Plane on startup
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/adapter/adapter.go
  adapter/internal/api/apis_impl.go
  adapter/internal/common/types.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/synchronizer/apis_fetcher.go
  adapter/pkg/adapter/adapter.go
  adapter/pkg/utils/slice_utils.go
  adapter/pkg/utils/slice_utils_test.go
  resources/conf/config.toml.template
Labels: Type/Improvement, Type/Task

#3496 Set backend JWT enduser from sub claim
  enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
Labels: Type/Bug, Choreo

#3497 [Choreo] Update rate-limiter to the latest version
  rate-limiter/src/main/resources/Dockerfile
Labels: Choreo

#3501 Bug fix: Secondary Logformat entries are not shown when the access log format is json
  adapter/internal/oasparser/envoyconf/access_loggers.go
Labels: Type/Bug, Choreo

#3503 Make typed_dns_resolver_config configurable in Envoy Cluster configuration
  adapter/config/default_config.go
  adapter/config/parser.go
  adapter/config/types.go
  adapter/internal/oasparser/envoyconf/dns_resolver.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  resources/conf/config.toml.template
Labels: Type/Task, Choreo
